### ISSUE TITLE
Fix update.windows for the new DeckhouseRelease update logic

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#10000]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.65.0

### Expected Behavior

We need the next logic:
- `Manual` - we don't respect update.windows at all
- `AutoPatch` - we use update.windows for Patches approval, but Minor release have to be approved manually
- `Auto`  - Patches are installed immediately, Minors respect update.windows

### Actual Behavior

At the moment, we have some mistakes in the logic. For example, for AutoPatch mode with window
```yaml
    update:
      mode: AutoPatch
      windows:
      - from: "10:00"
        to: "11:00"
```

 I have the next situation:
```
# kubectl get deckhousereleases.deckhouse.io
NAME      PHASE        TRANSITIONTIME   MESSAGE
v1.77.0   Superseded   15h
v1.77.1   Skipped      15h
v1.77.2   Deployed     15h
v1.78.0   Pending      159m             Release is waiting for the update window: 05 Oct 24 10:00 UTC
```

### Steps To Reproduce

1. put release channel and update settings to the mc deckhouse
```
spec:
  settings:
    bundle: Default
    logLevel: Info
    releaseChannel: Stable
    update:
      mode: AutoPatch
      windows:
      - from: "10:00"
        to: "11:00"
```

2. Use initial DeckhouseRelease
```
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  annotations:
    dryrun: "true"
  name: v1.77.0
spec:
  version: v1.77.0
```

3. Apply next DeckhouseReleases
```yaml
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  annotations:
    dryrun: "true"
  name: v1.77.1
spec:
  version: v1.77.1
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  annotations:
    dryrun: "true"
  name: v1.77.2
spec:
  version: v1.77.2
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  annotations:
    dryrun: "true"
  name: v1.78.0
spec:
  version: v1.78.0
```
