### ISSUE TITLE
[ingress-nginx] Add cache feature

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#103]
It is convenient when you want to use ingress-nginx controller as an edge-server and provide efficient access to static content.

Main problems:
1. Add the way to configure cache main parameters (via global configuration snippets or by patching ingress controller).
2. Provide an ability to persist the cache (via either host path or even a persistent volume).

These links can help:
* [Link](https://github.com/aledbf/ingress-nginx/commit/e3faa80aa96474c25c90c74dfd6a472b626bb719) to the branch of nginx-ingress with cache support.

**Comment by nabokihms** [comment]
The plan is:

1. Add a new option to IngressNginxController CRD
```yaml
cacheList:
  type: array
  items: 
    type: object
    required: ["name", "size"]
    properties:
      name: 
        type: string
      size:
        type: string
      ...(and other options)
```
Example:
```yaml
cacheList:
- name: myCache
   stale: true
   size: 10m
```   

2. Mount host path directory: /var/run/d8-ingress-controller-cache to the controller pods (using hostpath directive).

3. Compose HTTP snippet for all ingress-controllers with cache enabled and add it to the configmap. For example, it looks like:
```
http-snippet: |
  proxy_cache_path     /var/run/d8-ingress-controller-cache/myCache levels=1:2 keys_zone=myCache:10m max_size=10m;
```      

After that, users will be able to use the cache with a configuration snippet:
```
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache myCache;
      proxy_cache_valid 404 10m;
      proxy_cache_use_stale error timeout updating http_404 http_500 http_502 http_503 http_504;
```
(this is the only problem, we have no user-friendly interface to connect a cache to the location, but let's go with the snippet, it is fine)
