### ISSUE TITLE
Add support of calculation default values in hook tests.

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#10459]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When we write hook tests, hook openapi default values cannot calculated, same as default values in the CRDs used in tests.

### Proposed Solution

Enrich tests values storage with openapi default values.
Add proper support of the CRDs in hooks tests.

### Additional Information

We tests crd deschedulers.deckhouse.io/v1alpha2

```
apiVersion: deckhouse.io/v1alpha2
kind: Descheduler
metadata:
  name: test4
spec:
  nodeLabelSelector:
    matchExpressions:
    - key: node.deckhouse.io/group
      operator: In
      values: ["test1", "test2"]
  strategies:
    highNodeUtilization:
      enabled: true
```

We expect to see in the values storage:

```
apiVersion: deckhouse.io/v1alpha2
kind: Descheduler
metadata:
  name: test4
spec:
  nodeLabelSelector:
    matchExpressions:
    - key: node.deckhouse.io/group
      operator: In
      values: ["test1", "test2"]
  strategies:
    highNodeUtilization:
      enabled: true
      thresholds:
        cpu: 20
        memory: 20
        pods: 20
```

Thresholds will be set to default values due to CRD spec.
But we cannot see thresholds section in the calculated values:

```
apiVersion: deckhouse.io/v1alpha2
kind: Descheduler
metadata:
  name: test4
spec:
  nodeLabelSelector:
    matchExpressions:
    - key: node.deckhouse.io/group
      operator: In
      values: ["test1", "test2"]
  strategies:
    highNodeUtilization:
      enabled: true
```
