### ISSUE TITLE
[refactoring] Replace all deprecated logger methods

### ISSUE THREAD

**Issue by ldmonster** [deckhouse/deckhouse#10522]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to replace all deprecated methods to unify code style and clean logger implementation

### Proposed Solution

Remove staticcheck linter restriction and replace all methods
[golangcilint](https://github.com/deckhouse/deckhouse/blob/main/.golangci.yaml)
```yaml
  # TODO: replace deprecated methods
  # ignore deprecated 
  # https://staticcheck.dev/docs/checks/#SA1019
  staticcheck:
     checks: ["all","-SA1019"]
```

#### Use slog Attrs when refactoring methods
```go
// old method
logger.Infof("user with id '%d' and name '%s' created", user.id, user.name)
// refactored method
logger.Info("user created",slog.Int64("id",user.id), slog.String("name",user.name))
```
