### ISSUE TITLE
[caps] Single-master node controlled by CAPS self deletes after time

### ISSUE THREAD

**Issue by haosb** [deckhouse/deckhouse#10557]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Then we bootstrap cluster with 1 master node and give CAPS to control over node; we can see after time that node is being cleared with cleanup_static_node script.

### Proposed Solution

Single-master node is not self-deletes, like the multi-master scenario.

### Additional Information

```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: master
spec:
  nodeTemplate:
    labels:
      node-role.kubernetes.io/control-plane: ""
      node-role.kubernetes.io/master: ""
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  nodeType: Static
  staticInstances:
    count: 3
    labelSelector:
      matchLabels:
        role: master
---
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: master-1
  annotations:
    static.node.deckhouse.io/skip-bootstrap-phase: ""
  labels:
    role: master
spec:
  address: "10.241.32.27"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
```
