### ISSUE TITLE
[log-shipper] Customize CEF encoding fields

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#10555]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

1. Device vendor, version and product are strings that uniqly identify the sending device. Users want log-shipper to specify values that will identify their application, not a log-shipper instance ([as we do now](https://github.com/deckhouse/deckhouse/blob/de6b4cfea3c6c47ba2a9e3a475552797d6b61739/modules/460-log-shipper/hooks/internal/vector/destination/socket.go#L83-L85)), because it is too generic.
2. Some SIEM systems wait defined names for extension to automatically parse these fields, e.g., [Arcsight](https://www.microfocus.com/documentation/arcsight/arcsight-smartconnectors-8.3/cef-implementation-standard/). Users may need to use their own keys for extensions.

### Proposed Solution

As for device settings, we can give users an ability to change them on the cluster log destination level, e.g,
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLogDestination
metadata:
  name: siem-kafka
spec:
  type: Kafka
  kafka:
    topic: logs
    bootstrapServers: [my-cluster-kafka-brokers.kafka:9092]
    encoding:
      codec: CEF
      cef:
        deviceVendor: MyCompany
        deviceProduct: MyProduct
        deviceVersion: v0.0.1
```

but for extensions, I think, we need to add all `extraLabels` to logs [as we do for Loki](https://github.com/deckhouse/deckhouse/blob/de6b4cfea3c6c47ba2a9e3a475552797d6b61739/modules/460-log-shipper/hooks/internal/vector/destination/loki.go#L65-L88).

In this case the following snippet will rename the message field to msg field:
```yaml
extraLabels:
  msg: {{ message }}
  message: ""
```
