### ISSUE TITLE
[multitenancy-manager] Fix AuthorizationRule naming

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#10657]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.66.X

### Expected Behavior

Project should be created

### Actual Behavior

Project will fail with:
```
    message: "failed to install the release: 1 error occurred:\n\t* AuthorizationRule.deckhouse.io
      \"group_kvs\" is invalid: metadata.name: Invalid value: \"group_kvs\": a lowercase
      RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or
      '.', and must start and end with an alphanumeric character (e.g. 'example.com',
      regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\n\n"
```

### Steps To Reproduce

Create Project
```
apiVersion: deckhouse.io/v1alpha2
kind: Project
metadata:
  name: test-validation
spec:
  description: test-validation for group with /
  projectTemplateName: default
  parameters:
    resourceQuota:
      requests:
        cpu: 5
        memory: 5Gi
        storage: 1Gi
      limits:
        cpu: 5
        memory: 5Gi
    podSecurityProfile: Baseline
    extendedMonitoringEnabled: true
    administrators:
    - subject: Group
      name: "/Group_KVS"
```

### Additional Information

Group with slash could be passed from keycloak
We uses [norimalize](https://github.com/deckhouse/deckhouse/blob/main/modules/160-multitenancy-manager/images/multitenancy-manager/default/default.yaml#L141) with Group name for object metadata.name. It doesn't work with special symbols

Have to fix [this function](https://github.com/deckhouse/deckhouse/blob/main/modules/160-multitenancy-manager/images/multitenancy-manager/templates/_helpers.tpl#L36) to replace `_` with `-`
