### ISSUE TITLE
[admission-policy-engine] Verify image signature

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#10833]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have to check image signature with public key or signature

### Proposed Solution

Add new policy to the [security policies](https://github.com/deckhouse/deckhouse/blob/ada1fde3f7b70a9c51201efbcd4c4c8218aa37a9/modules/015-admission-policy-engine/crds/security-policy.yaml#L96)

Public API should be something like:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: mypolicy
spec:
  enforcementAction: Deny
  policies:
    verifyImages:
      - imageReferences:
          - "ghcr.io/repo/test-verify-image*" # use repo as string prefix or wildcard? I guess string prefix is better
        keys:
        - publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8nXRh950IZbRj8Ra/N9sbqOPZrfM
                5/KAQN0/KjHcorm/J5yctVd7iEcnessRQjU917hmKO6JWVGHpDguIyakZA==
                -----END PUBLIC KEY-----                
          rekor:
             ignoreTlog: true
             url: https://rekor.sigstore.dev
```

### Additional Information

Should be something like [this](https://kyverno.io/docs/writing-policies/verify-images/sigstore/#verifying-image-signatures)

Possible solutions:
  - Rewrite outdated [provider](https://github.com/sigstore/cosign-gatekeeper-provider)
  - Integrate [ratify](https://ratify.dev/)
