### ISSUE TITLE
[deckhouse][network-policies] Add NetworkPolicies for all deckhouse components

### ISSUE THREAD

**Issue by haosb** [deckhouse/deckhouse#10997]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some of clients want to use *Deny policy* out of the box and create policies only for required apps. And to make this feature available we need to make default policies what will give access to Kubernetes and Deckhouse components.
Example: from deckhouse components to other deckhouse components and to kube-api-server, kube-dns.

### Proposed Solution

We made this config for cilium, but we will not use `CiliumClusterWideNetworkPolicy` in the future releases and for other CNIs what would be a problem, and we don't have `heritage: deckhouse` label at some components, like Istio operator pod:

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: deny-all-allow-d8-kube-system
spec:
  description: "Deny all traffic by default, allowing specific traffic for D8 and kube-system."
  endpointSelector: {}

  ingress:
  - fromEndpoints:
    - matchLabels:
        heritage: deckhouse
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system

  egress:
  - toEndpoints:
    - matchLabels:
        heritage: deckhouse
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
```

I think, what we need to create `NetworkPolicy` like that, because all d8 ns have this option:
```
    - namespaceSelector:
        matchLabels:
          heritage: deckhouse
```

### Additional Information

Should we have allowed option for sidecars, like istio in clients ns?
