### ISSUE TITLE
[kube-dns] Add the ability to use regular expressions in domain entries

### ISSUE THREAD

**Issue by VaLosev** [deckhouse/deckhouse#11050]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

At the moment, in the `settings.hosts` section of the [ModuleConfig kube-dns](https://deckhouse.ru/products/kubernetes-platform/documentation/v1/modules/kube-dns/configuration.html#parameters-hosts), you need to separately list each domain and its IP, even if 1 IP will be used for several domains.

### Proposed Solution

If the cluster has technical domains that are used by the same LoadBalancer, then each time a new technical domain is added, it is necessary to make changes to the ModuleConfig.

To simplify this procedure, it is suggested to consider the possibility of using regular expressions in the `settings.hosts.domain` field.

For example, a domain of the form `*.example.com`.
So that all requests for domains of this template can be sent to 1 IP.

```
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: kube-dns
spec:
  version: 1
  enabled: true
  settings:
    hosts:
    - domain: *.example.com
      ip: 192.168.0.1
```
