### ISSUE TITLE
[alertamanger] Failed to resolve alertmanager-operated service in logs alertmanager pod when HA enabled 

### ISSUE THREAD

**Issue by trofimovdals** [deckhouse/deckhouse#11115]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.66

### Expected Behavior

No errors

### Actual Behavior

When we have alertmanager in HA with multiple pods, one replica with error:
At the same time, the functionality works
```
ts=2024-12-17T13:56:07.743Z caller=cluster.go:698 level=info component=cluster msg="gossip settled; proceeding" elapsed=10.004169318s
ts=2024-12-17T13:56:12.744Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-webhook-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-webhook-0.alertmanager-operated:9094: lookup alertmanager-webhook-0.alertmanager-operated on 10.222.0.10:53: no such host\n\n"
ts=2024-12-17T13:56:27.743Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-webhook-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-webhook-0.alertmanager-operated:9094: lookup alertmanager-webhook-0.alertmanager-operated on 10.222.0.10:53: no such host\n\n"
```

### Steps To Reproduce

1.
```
kubectl apply -f - <<EOF
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: webhook
spec:
  type: Internal
  internal:
    route:
      groupBy: ['job']
      groupWait: 30s
      groupInterval: 5m
      repeatInterval: 12h
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
      webhookConfigs:
      - url: 'https://webhook.site/9617efee-f396-45a6-986d-f64cbb7f3b81/'
EOF
```
2. Check `highAvailability: true` in moduleConfig Prometheus
