### ISSUE TITLE
[control-plane-manager] No root certificates for kube-apiserver on CentOS

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#112]
kube-apiserver pod spec has such mounts:
```
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
```
However, certificates are located in different paths on CentOS.

```
[root@**** ~]# ls -lah /usr/share/ca-certificates/
total 4.0K
drwxr-xr-x   2 root root    6 Sep 28 15:09 .
drwxr-xr-x. 95 root root 4.0K Sep 28 15:12 ..
```
