### ISSUE TITLE
Move rbac.yaml file to the module.yaml

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#11318]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Keep everything in the one point of truth

### Proposed Solution

Move content of the rbac.yaml to the module.yaml

1.
```
subsystems:
  - a
  - b
  - c
```
keep on the first indent level

2. get rid of `module`, use `name` instead

3. automatically discovery crds with apiGroup `deckhouse.io` in the `crds/` directory. Other desired crds describe like this:

`module.yaml
```yaml
name: admission-policy-engine
weight: 15
...
rbac:
  crds:
    - path: modules/015-admission-policy-engine/crds/native/*.yaml
      allowedResources:
        - group: templates.gatekeeper.sh
          resources:
            - constrainttemplates
```
