### ISSUE TITLE
[documentation] build conversions documentation

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#11684]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Build human-readable instructions for conversions

### Proposed Solution

Generate single `conversions.yaml` file with go-generate:
1) Add generator [here](https://github.com/deckhouse/deckhouse/tree/c8c5d31c6a54958ca9a50671594fa9b499dd6bae/tools/helm_generate)
2) Build file from all `openapi/conversions` like:
```yaml
"user-authn":
  - version: 2
    description:
      ru: "todo"
      en: "todo"
  - version: 3
    description:
      ru: "todo"
      en: "todo"
"ingress-nginx":
  - version: 2
    description:
      ru: "todo"
      en: "todo"
  - version: 3
    description:
      ru: "todo"
      en: "todo"
```
