### ISSUE TITLE
[log-shipper] Add processing UserAgent=null in audit logs from log-shipper

### ISSUE THREAD

**Issue by trofimovdals** [deckhouse/deckhouse#11779]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.66

### Expected Behavior

We have userAgent in all audit.log or processing userAgent=null
No transform errors

### Actual Behavior

If basicAuditPolicyEnabled: true we have audit policy and with userAgent=null in some audit logs
```
cat /var/log/kube-audit/audit.log | grep d8-log-shipper |  jq '.userAgent' | sort | uniq -c | sort -nr
     46 "kube-rbac-proxy/v0.0.0 (linux/amd64) kubernetes/$Format"
     44 null
     14 "recommender/v0.0.0 (linux/amd64) kubernetes/$Format"
      9 "kubelet/v1.30.8 (linux/amd64) kubernetes/0000000"
      8 "kubectl/v1.30.8 (linux/amd64) kubernetes/0000000"
```
We see this from `jq 'select(.user.username == "system:serviceaccount:d8-log-shipper:log-shipper" and (.userAgent == null))' /var/log/kube-audit/audit.log`
they all have `"verb": "list"` and generated by log-shipper pods, probably, vector not set userAgent in header
If we create
```
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLoggingConfig
metadata:
  name: kubelet-audit-logs
spec:
  type: File
  file:
    include:
    - /var/log/kube-audit/audit.log
  logFilter:
  - field: userAgent  
    operator: Regex
    values: ["kubelet.*"]
  destinationRefs:
  - loki-storage
```
We get error in log-shipper pods
`2025-01-27T11:33:32.751817Z ERROR transform{component_kind="transform" component_id=transform/source/kubelet-audit-logs/03_log_filter component_type=filter component_name=transform/source/kubelet-audit-logs/03_log_filter}: vector::internal_events::conditions: VRL condition execution failed. error=function call error for "match" at (0:46): expected string, got null error_type="script_failed" stage="processing" internal_log_rate_limit=true`
maybe should modify logFilter: add check .userAgent != null

### Logs

```shell

```

**Comment by trofimovdals** [comment]
Workaround
```
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLoggingConfig
metadata:
  name: kubelet-audit-logs
spec:
  destinationRefs:
  - kafka-audit
  file:
    include:
    - /var/log/kube-audit/audit.log
  logFilter:
  - field: userAgent
    operator: Exists
  - field: userAgent
    operator: Regex
    values:
    - kubelet.*
  type: File
```
