### ISSUE TITLE
[admission-policy-engine]Broken config.json for trivy-provider in case of anonymous access in container registry

### ISSUE THREAD

**Issue by hugik-88** [deckhouse/deckhouse#12000]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.64+

### Expected Behavior

There is a webhook **modules/015-admission-policy-engine/hooks/trivy_provider_registry_secrets.go** for generating config.json from the deckhouse-registry secret
We expect a transformation of this secret 
```bash
kubectl -n d8-admission-policy-engine get secrets deckhouse-registry -oyaml
```
```yml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzb21lcmVwby5yZWciOnt9fX0=
kind: Secret
...
type: kubernetes.io/dockerconfigjson
```
to 
```bash
kubectl -n d8-admission-policy-engine get secrets trivy-provider-registry-secret -oyaml
```
```yml
apiVersion: v1
data:
  config.json: eyJhdXRocyI6eyJzb21lcmVwby5yZWciOnt9fX0=
kind: Secret
...
type: Opaque
```

### Actual Behavior

But in reality
```bash
kubectl -n d8-admission-policy-engine get secrets deckhouse-registry -oyaml
```
```yml
apiVersion: v1
data:
   config.json: eyJhdXRocyI6eyJzb21lcmVwby5yZWciOnt9fX0=
kind: Secret
...
type: kubernetes.io/dockerconfigjson
```
to 
```bash
kubectl -n d8-admission-policy-engine get secrets trivy-provider-registry-secret -oyaml
```
```yml
apiVersion: v1
data:
  config.json: eyJhdXRocyI6eyJzb21lcmVwby5yZWciOnsiYXV0aCI6Ik9nPT0ifX19
kind: Secret
...
type: Opaque
```
```bash
kubectl -n d8-system exec svc/deckhouse-leader -- deckhouse-controller module values admission-policy-engine | head -n12
denyVulnerableImages:
  enabled: true
  registrySecrets: []
internal:
  bootstrapped: true
  denyVulnerableImages:
    dockerConfigJson:
      auths:
        somerepo.reg:
          auth: Og==
```
Instead of empty authorization we have an "Og=="

### Additional Information

Discussion and additional context in [thread](https://loop.flant.ru/flant/pl/sgyakgiip7no9rp7q6ye6dcidy)

### Logs

```shell

```
