### ISSUE TITLE
[candi] [yandex-cloud] Yandex Cloud has added an additional routing table on nodes with two interfaces operating in interconnect mode and with new Ubuntu 24, which breaks requests to the kube-api

### ISSUE THREAD

**Issue by DaNnNiS** [deckhouse/deckhouse#12243]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.65.6

### Expected Behavior

When adding nodes with Ubuntu 24.04.2 (vanilla) OS with two network interfaces in interconnect mode to the cluster, requests to kube-api from api-proxy go through normally and do not produce errors. A separate routing table `table 101` is not added in `/etc/netplan/50-cloud-init.yaml`.

### Actual Behavior

When adding nodes with Ubuntu 24.04.2 (vanilla) OS with two network interfaces in interconnect mode to the cluster, a separate routing table table 101 is added in '/etc/netplan/50-cloud-init.yaml', which causes requests from api-proxy to kube-api to break. The api-proxy can reach the kubelet but does not receive a response. At this point, '/etc/netplan/50-cloud-init.yaml' looks as follows:
```
network:
  version: 2
  ethernets:
    eth0:
      match:
        macaddress: "d0:0d:55:8b:8a:38"
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
      set-name: "eth0"
    eth1:
      match:
        macaddress: "d0:1d:55:8b:8a:38"
      dhcp4: true
      dhcp4-overrides:
        use-routes: true
        route-metric: 200
      dhcp6: false
      set-name: "eth1"
      routes:
      - table: 101
        to: "0.0.0.0/0"
        via: "192.168.0.1"
      - scope: "link"
        table: 101
        to: "192.168.0.0/18"
      routing-policy:
      - table: 101
        from: "192.168.0.62"
```

A new ip rule is being added:
```
# ip rule list
0:      from all lookup local
32765:  from 192.168.0.27 lookup 101 proto static
32766:  from all lookup main
32767:  from all lookup default
```
and route table
```
# ip route show table 101
default via 192.168.0.1 dev eth1 proto static onlink
192.168.0.0/18 dev eth1 proto static scope link
```

### Steps To Reproduce

1. Bootstrap the cluster on Yandex cloud with imageID `fd8bqstt334fta084rj8` with master ng
```
masterNodeGroup:
  instanceClass:
    cores: 8
    diskSizeGB: 50
    etcdDiskSizeGb: 60
    externalSubnetIDs:
    - <SubnetID>
    - <SubnetID>
    - <SubnetID>
    imageID: fd8bqstt334fta084rj8
    memory: 24576
    platform: standard-v3
  replicas: 3
  zones:
  - ru-central1-a
```
and with mc istio
```
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  finalizers:
  - modules.deckhouse.io/module-config
spec:
  enabled: true
  settings:
    alliance:
      ingressGateway:
        inlet: LoadBalancer
        nodeSelector:
          node-role.deckhouse.io/frontend: ""
        serviceAnnotations:
          yandex.cpi.flant.com/listener-subnet-id: <subnet-id>
          yandex.cpi.flant.com/target-group-network-id: <target-group-network-id>
        tolerations:
        - effect: NoExecute
          key: dedicated.deckhouse.io
          operator: Equal
          value: frontend
    dataPlane:
      trafficRedirectionSetupMode: CNIPlugin
    federation:
      enabled: true
    globalVersion: "1.19"
    multicluster:
      enabled: true
    sidecar:
      resourcesManagement:
        mode: Static
```

### Additional Information

api-proxy pod's logs:
```
# kubectl -n d8-istio logs api-proxy-56d654c69d-zgtjb --tail 100
http: 2025/02/14 10:52:24 Server is starting to listen on  0.0.0.0:4443 ...
http: 2025/02/14 10:52:27 10.111.0.1:45476 GET kube-probe/1.28 /healthz
http: 2025/02/14 10:52:34 Readiness probe error: Get "https://kubernetes.default.svc.mesh/version": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

```
Remote api host `istio-api-proxy-apps.tech` for IstioMulticluster `wezen-a` has failed healthcheck by d8 monitoring hook.

Reproducing (run from deckhouse pod):
TOKEN="$(deckhouse-controller module values istio -o json | jq -r --arg ah istio-api-proxy-apps.tech '.istio.internal.multiclusters[] | select(.apiHost == $ah) | .apiJWT')"
curl -H "Authorization: Bearer $TOKEN" https://istio-api-proxy-apps.tech/version
```

### Logs

```shell

```
