### ISSUE TITLE
[admission-policy-engine] exclude namespaces from Security/Operation Policy

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#12275]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.67.0

### Expected Behavior

Can deploy policies with excluded names

### Actual Behavior

error `"spec.match.namespaceSelector" must validate one and only one schema (oneOf). Found 2 valid alternatives`

### Steps To Reproduce

try to create
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: OperationPolicy
metadata:
  name: test-2
spec:
  enforcementAction: Deny
  match:
    namespaceSelector:
      labelSelector:
        matchLabels:
          kubernetes.io/metadata.name: my-project
      excludeNames: ["foo", "bar"]
  policies:
    requiredResources:
      requests:
        - cpu
```

### Additional Information

it's because of
```
                oneOf:
                        - required: [matchNames]
                        - required: [excludeNames]
                        - required: [labelSelector]
```

we have to remove `excludeNames` from here
also have to check, can matchNames and labelSelector works together or not? Probably have to remove the whole `oneOf` section

### Logs

```shell

```
