### ISSUE TITLE
[deckhouse-controller] put disableConfirmation from module.yaml to the Module CR

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#12310]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Add metadata to the Module CR to show in the UI

### Proposed Solution

if module.yaml has the following fields
```
disable:
  confirmation: true|false
  message: "string"
```

we have to duplicate them to the Module CR properties field:
```
apiVersion: deckhouse.io/v1alpha1
kind: Module
properties:
  disable:
    confirmation: true|false
    message: "string"
...
```
