### ISSUE TITLE
[deckhouse-controller] Add ModuleSettingsDefinition CRD

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#12509]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need an openapi spec for module settings to easy parse them in the deckhouse UI

### Proposed Solution

Add the new CRD: `ModuleSettingsDefinition`
It looks very similar to the CustomResourceDefinition.

On every `Downloaded` module, which openapi spec we have, we should do the next actions:
- If CR `ModuleSettingsDefinition/$module_name` does not exist - create it
- Append openapi spec version (based on x-config-version) to the CR
- Write the whole openapi module spec to the CR

Example
```yaml
apiVersion: deckhouse.io/v1
kind: ModuleSettingsDefinition
metadata:
  labels:
    app.kubernetes.io/name: deckhouse
    app.kubernetes.io/part-of: deckhouse
    heritage: deckhouse
  name: node-manager
spec:
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            allowedBundles:
              description: |
                Names of available bashible OS bundles to reduce helm release size.
              type: array
              items:
                type: string
            allowedKubernetesVersions:
              type: array
              items:
                type: string
            earlyOomEnabled:
              type: boolean
              default: true
    - name: v2
      schema:
        openAPIV3Schema:
          properties:
            earlyOomEnabled:
              type: boolean
              default: true
```

don't copy `x-` prefixed fields

### Additional Information

As a next step, I guess, we also can add conversions here
