### ISSUE TITLE
[user-authn] DexAuthenticator with digit name fails

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#12546]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.68.3

### Expected Behavior

DexAuthenticator must renders gracefully.

### Actual Behavior

```
ModuleRun:main:user-authn:doStartup:ReloadAllModules:failures 1:run helm install: helm upgrade failed: failed to create resource: PodDisruptionBudget in version "v1" cannot be handled as a PodDisruptionBudget: json: cannot unmarshal number into Go struct field LabelSelector.spec.selector.matchLabels of type string
```

### Steps To Reproduce

1. Create DexAuthenticator with digital name
```yaml
apiVersion: deckhouse.io/v1
kind: DexAuthenticator
metadata:
  name: 111111
  namespace: default
spec:
  applicationDomain: foo.bar.com
  applicationIngressCertificateSecretName: ingress-tls
  applicationIngressClassName: nginx
  highAvailability: false
```

2. Deckhouse will fail

### Additional Information

Guess we have to add ` | quote` here:
- [one](https://github.com/deckhouse/deckhouse/blob/main/modules/150-user-authn/templates/dex-authenticator/deployment.yaml#L55)
- [two](https://github.com/deckhouse/deckhouse/blob/main/modules/150-user-authn/templates/dex-authenticator/deployment.yaml#L76)
- [three](https://github.com/deckhouse/deckhouse/blob/main/modules/150-user-authn/templates/dex-authenticator/deployment.yaml#L81)

### Logs

```shell

```
