### ISSUE TITLE
[nodeuser] Incorrect manifest validation for the resource nodeUser

### ISSUE THREAD

**Issue by AndrewGodGivens** [deckhouse/deckhouse#12630]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.68.4

### Expected Behavior

If you forget the passwordHash in the nodeUser resource and defined public key by `sshPublicKeys`, the validator complains about the absence of sshPublicKey 
```
The NodeUser "example-user" is invalid:
* <nil>: Invalid value: "": "spec" must validate one and only one schema (oneOf). Found none valid
* spec.passwordHash: Required value
```

### Actual Behavior

"The validator should not complain about the absence of the sshPublicKey parameter when the public key is defined through sshPublicKeys."
```
The NodeUser "example-user" is invalid:
* <nil>: Invalid value: "": "spec" must validate one and only one schema (oneOf). Found none valid
* spec.sshPublicKey: Required value
* spec.passwordHash: Required value
```

### Steps To Reproduce

You can apply this manifest for reproduce this bug:
```
apiVersion: deckhouse.io/v1
kind: NodeUser
metadata:
  name: example-user
spec:
  isSudoer: true
  nodeGroups:
  - '*'
  sshPublicKeys:
  - ssh-rsa example-key
  uid: 30001
```

### Logs

```shell

```
