### ISSUE TITLE
[cloud-provider-vcd] Check the number of static IP addresses before converge

### ISSUE THREAD

**Issue by borg-z** [deckhouse/deckhouse#13304]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.69.3

### Expected Behavior

```
masterNodeGroup:
  instanceClass:
    etcdDiskSizeGb: 10
    mainNetworkIPAddresses: 
    - 10.14.0.10
    rootDiskSizeGb: 50
    storageProfile: ""
    sizingPolicy: ""
    template: """
  replicas: 3
```

With this configuration, dhctl should generate an error about the mismatch between the number of IPs and replicas.

We already have a similar check:

https://github.com/deckhouse/deckhouse/blob/c04e1baeb51160743a3b014245bccff1c3ca21cb/dhctl/pkg/config/meta.go#L145

### Actual Behavior

dhctl will try to create 3 VMs with the same IPs (10.14.0.10, 10.14.0.10, 10.14.0.10)

### Logs

```shell

```
