### ISSUE TITLE
[log-shipper] multiline parser Custom type

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1342]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is hard to cover all possible multiline variants because their number is only limited by people's imagination.

### Proposed Solution

Provide the Custom multiline parse type with the VRL support.

Example:
```yaml
multiparser:
  type: Custom
  custom:
    starts_when: |
      matched, err = match(.message, r'^\{'); 
      if err != null { false; } else { matched; } 
```
We have a config validation feature so it should not be a problem.

### Additional Information

https://deckhouse.io/en/documentation/v1/modules/460-log-shipper/cr.html#clusterloggingconfig-v1alpha1-spec-multilineparser
