### ISSUE TITLE
[log-shipper] Labels filter support

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1343]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is no way to filter log lines by their labels.

### Proposed Solution

Provide a way to drop or keep lines by their labels. The syntax should be the same as for the logFilter option.

Example:
```yaml
labelsFilter:
- field: pod
  operator: Exists
- field: container
  operator: In
  values: ["nginx", "python"]
- field: namespace
  operator: Regex
  values: ["^prod-.*$"]
```   

### Additional Information

Only log message filter is implemented right now
https://deckhouse.io/en/documentation/v1/modules/460-log-shipper/cr.html#clusterloggingconfig-v1alpha1-spec-logfilter
