### ISSUE TITLE
[dhctl] Non-obvious logic on InitConfiguration generation

### ISSUE THREAD

**Issue by haosb** [deckhouse/deckhouse#14009]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.68.15

### Expected Behavior

I think we need to cancel installation and show error in validation phase or just contintue, but with warning logs.

### Actual Behavior

When we are using `config.yml` with non closed `InitConfiguration` section bootstrap continues, but `InitConfiguration` generates with empty `deckhouse` field, that lead components to use default CE Deckhouse registry and install from it. 

### Steps To Reproduce

Use `InitConfiguration` section at `config.yml` like this with commented `---`:
```
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: redacted:EE
  registryDockerCfg: redacted
# ---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    bundle: Default
    releaseChannel: Alpha
    logLevel: Info
    update:
      mode: Manual
---
```

After we can see at `bootstrap.log`:
```
2025-06-17 10:07:57 - Init configuration not found use empty: 
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse: {}
```

### Additional Information

It is really difficult to figure out why installation errors, and difficult to find missing `---` because of long `InitConfiguration` section if CA certificate is present.

### Logs

```shell

```
