### ISSUE TITLE
[trivy][console] The count of vulnerabilities does not match in the console and grafana dashboard

### ISSUE THREAD

**Issue by DaNnNiS** [deckhouse/deckhouse#14082]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.69.10

### Expected Behavior

If there are vulnerabilities in the cluster, their count in the cluster can be viewed in the grafana dashboard `Trivy Image Vulnerability Overview`, the count of vulnerabilities in the Grafana dashboard coincides with the count of vulnerabilities in the `Vulnerability reports` page in the d8-console.

### Actual Behavior

If there are vulnerabilities in the cluster, the count of vulnerabilities in the dashboard graphane "Trivy Image Vulnerability Overview" differs from the count of vulnerabilities in the "Vulnerability reports" page. The Trivy Image Vulnerability Overview dashboard counts the number of CVEs, and the d8 console indicates the actual count of vulnerabilities in the cluster.

### Steps To Reproduce

1. Enable the operator-trivy module
2. Apply the manifest
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
3. Check the number of vulnerabilities in grafana dashboard "Trivy Image Vulnerability Overview" and in d8-console on the "Vulnerability Reports" page

### Logs

```shell

```
