### ISSUE TITLE
[log-shipper] Rate limit option for clusterlogdestinations

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1452]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is no way to control the throughput of logs to log destinations. It may lead to overloading the sink or to increasing cloud storage costs. Nobody wants to accidentally pay a heavy bill at the end of a month.

### Proposed Solution

1. Implement a rate-limit option for clusterlogdestinations based on the `throttle` transform - https://vector.dev/docs/reference/configuration/transforms/throttle/#rate-limiting
2. Alert if the discarded events rate is above zero (`events_discarded_total` metric)

**Comment by nabokihms** [comment]
The idea is to add option to the clusterlogdestination CRD
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLogDestination
metadata:
  name: loki
spec:
  type: Loki
  ...
  rateLimit:
    linesPerMinute: 100
```

This should generate the following transform and attach it to the destination.
```json
{
  "d8_tf_dest_id_transform": {
      "type": "throttle",
      "inputs": [...],
      "exclude": null,
      "threshold": 100,
      "window_secs": 60
  }
}
```
