### ISSUE TITLE
taints missing in nodegroup frontend GKE

### ISSUE THREAD

**Issue by evstratbg** [deckhouse/deckhouse#1669]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.32.9

### Expected Behavior

Frontend nodegroup has taints, while bootstrapping a cluster in GKE

### Actual Behavior

Frontend nodegroup has no taints

### Steps To Reproduce

Add taints to GKE example resources 
https://deckhouse.io/ru/gs/gcp/step5.html

as here
https://deckhouse.io/ru/gs/yandex/step5.html

**Comment by evstratbg** [comment]
this is the manifest from quickstart, ready for production, `taints` field is missing

```
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: frontend
spec:
  cloudInstances:
    classReference:
      kind: GCPInstanceClass
      name: frontend
    # the minimum number of instances for the group in each zone
    minPerZone: 2
    # the maximum number of instances for the group in each zone
    maxPerZone: 3
    # you might consider changing this
    zones:
    - europe-west3-a
  disruptions:
    approvalMode: Automatic
  nodeTemplate:
    # similar to the standard metadata.labels field
    labels:
      node-role.deckhouse.io/frontend: ""
  nodeType: CloudEphemeral
```


so, this is the correct manifest

```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: frontend
spec:
  cloudInstances:
    classReference:
      kind: GCPInstanceClass
      name: frontend
    # the minimum number of instances for the group in each zone
    minPerZone: 2
    # the maximum number of instances for the group in each zone
    maxPerZone: 3
    # you might consider changing this
    zones:
    - europe-west3-a
  disruptions:
    approvalMode: Automatic
  nodeTemplate:
    # similar to the standard metadata.labels field
    labels:
      node-role.deckhouse.io/frontend: ""
    taints:
    - effect: NoExecute
      key: dedicated.deckhouse.io
      value: frontend
  nodeType: CloudEphemeral
```
