### ISSUE TITLE
[ingress-nginx] Canary releases are not working as expected

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#1772]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.33.2

### Expected Behavior

Canary ingresses work.

### Actual Behavior

Canary releases are not rendering in the nginx configuration and therefore do not work.

### Steps To Reproduce

1. Deploy Ingress resource
2. Deploy similar Ingress resource but with canary enabled

ingress.yaml

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://dev-auth.dev-auth-production.svc.cluster.local/
    nginx.ingress.kubernetes.io/hsts: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "1"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: site-nginx
  namespace: site-test-2
spec:
  rules:
  - host: test-2.site.test.net
    http:
      paths:
      - backend:
          service:
            name: site
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: '*.test-2.site.test.net'
    http:
      paths:
      - backend:
          service:
            name: site
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - test-2.site.test.net
    - '*.test-2.site.test.net'
    secretName: tls-secret-v1-5
```

ingress-canary.yaml

```yaml

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://dev-auth.dev-auth-production.svc.cluster.local/
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-cookie: site_canary
    nginx.ingress.kubernetes.io/hsts: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "1"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: site-nginx-canary
  namespace: site-test-2
spec:
  rules:
  - host: test-2.site.test.net
    http:
      paths:
      - backend:
          service:
            name: site-canary
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: '*.test-2.site.test.net'
    http:
      paths:
      - backend:
          service:
            name: site-canary
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - test-2.site.test.net
    - '*.test-2.site.test.net'
    secretName: tls-secret-v1-5
```
