### ISSUE TITLE
Openapi case tests don't work with x-required-for-helm

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#186]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v.1.24.17

### Expected Behavior

I want to write negative openapi case test for testing skipped properties which contains in `x-required-for-helm` object spec.
These tests should pass.

### Actual Behavior

Tests fail

### Steps To Reproduce

1. Values file:
```
x-extend:
  schema: config-values.yaml
type: object
x-required-for-helm:
- internal
properties:
  internal:
    type: object
    additionalProperties: false
    default: {}
    x-required-for-helm:
    - adapterPem
    - adapterKey
    - adapterCA
    - prometheusAPIClientTLS
    properties:
      adapterPem:
        x-examples: ["YjY0ZW5jX3N0cmluZwo="]
        type: string

      adapterCA:
        x-examples: ["YjY0ZW5jX3N0cmluZwo="]
        type: string

      adapterKey:
        x-examples: [ "YjY0ZW5jX3N0cmluZwo=" ]
        type: string

      prometheusAPIClientTLS:
        default: {}
        additionalProperties: false
        x-required-for-helm:
          - certificate
          - key
        type: object
        properties:
          certificate:
            x-examples: [ "YjY0ZW5jX3N0cmluZwo=" ]
            type: string

          key:
            x-examples: [ "YjY0ZW5jX3N0cmluZwo=" ]
            type: string

      customMetrics:
        type: object
        default: {}
        additionalProperties: false
        properties:
          daemonset:
            type: object
            default: { }
            x-examples: [ {"name":{"cluster":"query", "namespaced": {"ns", "query"}}} ]
            additionalProperties: true

          ## skip similar objects (for pods, service...) here
```

2. Openapi cases tests file:
```
positive:
  values: []

negative:
  values:
  - internal:
      prometheusAPIClientTLS:
        certificate: cert
        key: key
      customMetrics:
        daemonset: { }
	# skip similar objects
```
3. Add files (or replaces) in some module
4. Run openapi test cases
