### ISSUE TITLE
[istio] default Sidecar CR to limit data-plane's view in their namespaces

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#1906]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are two reasons:
* in large setups with lots of namespaces there could be problems with resources to handle all the services in every istio-proxy sidecar.
* there is an [issue](https://github.com/istio/istio/issues/20703) in istio with [staled solution](https://github.com/istio/istio/issues/37331) — istio renders for External Services with ports listener "0.0.0.0:*port*" which catch all the traffic to the port. It is a problem for services out of istio registry. The solution could help ceasing impact of External Services.

### Proposed Solution

To create a module setting like isolateDataPlaneInItsNamespacec (🤮 , false by default) which enables Sidecar in d8-istio namespace:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
  - hosts:
    - "./*"
    - "d8-istio/*"
```
