### ISSUE TITLE
[*] VPA: configure and store defaults in values

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#2084]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is common practise in Helm Charts not to hardcode values in manifests, but to supply them in values.  Thus, chart default values are stored separately from manifests, and are not hardcoded. Along with that users are able to override values.

PR #1918 with refactoring of VPA and resources offers an approach of a hardcode in 100+ files. While it brings huge value to Deckhouse itself, the maintenance of this code will consume plenty a of time and is against well-known practices from 12-factor architecture. To name some issues:

- If some, but not many, clusters will require to tweak resources, we will have to bring them through patch-release cycle and wait for them to appear on a proper release channel. A configuration change triggers release process.
- Values in the aforementioned PR are duplicated in VPA `minAllowed` and Pod `requests`. The deduplication of the declaration of values was a subject matter on review and resulted in template helpers. If resources were specified in values, there would not be such a question.

### Proposed Solution

I see two ways.

#### Way 1: Put values to config

Assuming we use d8-system/ConfigMap/deckhouse, for each controller in every module I suggest to introduce all the means to control resources. And with that I suggest storing default values in openapi specs for the values. 

Config example:

```yaml
moduleName: |
  resources:
    controller1:
      container1:
        min:
          cpu: ...
          memory: ...
        max:         # ignored if VPA is off
          cpu: ...
          memory: ...
      container2:
        min:
          cpu: ...
          memory: ...
        max:          # ignored if VPA is off
          cpu: ...
          memory: ...
    controller2:
      ...
```

The downside is the verbosity of config, though all these resources are optional. The is nothing we can do with the size of the problem anyway.

#### Way 2: let user edit VPA and ensure it is not overwritten by deckhouse

Probably we can let users edit VPA directly and support an annotation (e.g. "something.deckhouse.io/mutable") what will prevent it from restoring by Deckhouse. The downside is the violation of deckhouse control.
