### ISSUE TITLE
[user-authn][kubeconfig-generator] Don't append server CA for public certificate providers

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#213]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.17

### Expected Behavior

clusters section shouldn't contain certificate-authority-data:
```
clusters:
- cluster:
    server: https://api.mycluster.example.com
  name: main
```

### Actual Behavior

clusters section contains certificate-authority-data and this data could expire:
```
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJT...
    server: https://api.mycluster.example.com
  name: main
```
