### ISSUE TITLE
[istio] let global mutating webhook inject sidecars to individual pods

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#2257]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are mutating webhooks for specific revisions. They are able to inject handle pods with specific rev label `istio.io/rev: v1x13`. We need the same solution for a global revision.

### Proposed Solution

Add a mutating rule with the selector:
```
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: In
      values:
      - "true"
    - key: istio.io/rev
      operator: DoesNotExist
```
