### ISSUE TITLE
cannot login to any dex-authed endpoints after cluster bootstrap

### ISSUE THREAD

**Issue by andycmaj** [deckhouse/deckhouse#226]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

unsure. used https://deckhouse.io/en/gs/aws

### Expected Behavior

expected to be able to login to d8 services once they are available using user and password shown in bootstrapping wizard:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/97470/136475853-41fbb653-f45c-4c94-8fe9-30188c8601d3.png">

possibly this is a documentation bug? i might have made incorrect assumptions when changing the admin password in config.yaml

### Actual Behavior

error message returned from dex. endpoint:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/97470/136475894-968d0356-1478-44b4-9617-9ddb3377441d.png">

### Steps To Reproduce

using default AWS configs from getting started on AWS wizard, i did, however change the admin password:

```
# section containing the parameters of the static user
# version of the Deckhouse API
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: admin
spec:
  # user e-mail
  email: admin@whaleshark.dev
  # this is a hash for generated password: t3m0unpswb
  # you might consider changing this
  password: 'new_password'
```

i also tried with the password from this config section
