### ISSUE TITLE
[node-manager] Nodes update windows

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#239]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

As for now, users stick to the Manual approval mode for their productions because it is more predictable. However, manually updating a massive amount of nodes is painful. What users really do now is changing the approval mode from Manual to Automatic every time a new update is released. It is not convenient to do it all the time.

### Proposed Solution

Provide a mechanism similar to https://github.com/deckhouse/deckhouse/issues/185.

The example of a NodeGroup:
```yaml
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: test
spec:
  nodeType: Static
  disruptions:
    approvalMode: Automatic
    automatic:
      windows: 
      - from: "8:00"
        to: "15:00"
        days:
          - Tue
          - Sat
```

### Additional Information

Do not forget about 
1. The `NodeIsNotUpdating` alert.
2. Bashible random checksum updates
