### ISSUE TITLE
[istio] don't let sidecar stopping before application containers

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#2401]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is an [issue](https://github.com/istio/istio/issues/7136) that all containers are being stopped simultaneously during Pod termination. After istio-proxy terminates, the application can't stop properly without connectivity.

### Proposed Solution

Permanently add to IstioOperator:
```
spec:
  values:
    sidecarInjectorWebhook:
      templates:
        d8-hold-istio-proxy-termination-until-application-stops: |
          spec:
            containers:
            - name: istio-proxy
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "curl -X POST localhost:15000/drain_listeners?inboundonly; while [ $(netstat -plunt | grep tcp | grep -v envoy | grep -v pilot-agent | wc -l | xargs) -ne 0 ]; do sleep 1; done"]
```
Then add a doc entry about `inject.istio.io/templates=sidecar,d8-hold-istio-proxy-termination-until-application-stops` annotation. Or maybe add a module parameter like `holdIstioProxyTerminationUntilApplicationStops`.
