### ISSUE TITLE
[log-shipper] Structured config for transforms

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#2487]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Deckhouse uses [Vector](https://vector.dev) under the hood to collect logs. For log line transformations, the Vector team introduced its rust-like language called [VRL](https://vector.dev/docs/reference/vrl/).

The main problem with VRL is that it is not stable and bulletproof yet robust. Users still need the flexibility to modify their logs before sending them to the storage and some protection from shooting their own legs.

### Proposed Solution

Introduce YAML-based structured configuration for simple log transformations similar to [Prometheus relabel config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config). This config structure may be less flexible, but it aged well and is still in use as a standard for metrics transformations.

***
Case 1: Drop some labels to reduce cardinality (solves Loki cases).

```yaml
modifyLogs:
- sourceLabels: ["pod", "pod_ip"]
  action: LabelDrop
```

Case 2: Filter logs by labels
```yaml
modifyLogs:
- sourceLabels: ["container"]
  action: Drop
  regex: "^nginx-.*"
- sourceLabels: ["pod"]
  action: Keep
  regex: "^web-worker-.*"
```

Case 3: Rename a label `timestamp` -> `@timestamp`
```yaml
modifyLogs:
- sourceLabels: ["timestamp"]
  action: Replace
  targetLabel: "@timestamp"
- sourceLabels: ["timestamp"]
  action: LabelDrop
```

Case 4: Flatten nested fields
```yaml
modifyLogs:
- sourceLabels: ["pod_labels.app"]
  action: Replace
  targetLabel: "app"
- sourceLabels: ["pod_labels.heritage"]
  action: Replace
  targetLabel: "heritage"
- sourceLabels: ["pod_labels"]
  action: LabelDrop
```

Case 5: Default value
```yaml
modifyLogs:
- sourceLabels: ["pod_labels.app"]
  action: Replace
  regex: "^$"
  replacement: "unknown"
  targetLabel: "pod_labels.app"
```

***
This is an example of what can be achieved with implementing the default relabeling config. However, our relabeling config can be extended with more actions.

Extended case 1: Parse message.

```yaml
modifyLogs:
- sourceLabels: ["message"]
  action: ParseJSON
  depth: 5 # max_depth to reduce highly nested json impact
  targetLabel: "message"
```

Extended case 2: Multiline.

```yaml
modifyLogs:
- sourceLabels: ["message"]
  action: Merge
  regex: '^[^\s\t]'
  when: "starts"
```

### Additional Information

Related https://github.com/deckhouse/deckhouse/issues/1350
Related https://github.com/deckhouse/deckhouse/issues/434
Related #606
