### ISSUE TITLE
[upmeter] status page not working when auth.password is in use

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#2498]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

main

### Expected Behavior

status page should load statuses.

### Actual Behavior

status page uses localhost to request statuses

<img width="877" src="https://user-images.githubusercontent.com/1055474/190351799-56f4d458-5c43-4912-839e-a93d0d7338b0.png">

### Steps To Reproduce

1. Disable user-authn module and set custom password for status page:
```
  upmeter: |
    auth:
      status:
        password: mypassword
  upmeterEnabled: "true"
  userAuthnEnabled: "false"
```
2. Open status page.
