### ISSUE TITLE
[log-shipper] Problems with CRD.

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#254]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.25.4

### Expected Behavior

CRD should validate this mistake
```yaml
---
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLogDestination
metadata:
  name: opendistro
spec:
  type: Elasticsearch
  loki:
    endpoint: http://172.16.176.248:9200
```

### Actual Behavior

CRD ignore error and cause problems with hooks.
