### ISSUE TITLE
[log-shipper] Extend namespace selector for ClusterLoggingConfig

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#269]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases it would be great to remove some namespaces from cluster without deploying additional ClusterLoggingConfigs or PodLoggingConfigs.

### Proposed Solution

Add to ClusterLoggingConfigs ability to exclude namespaces 
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLoggingConfig
metadata:
  name: all-logs
spec:
  type: KubernetesPods
  destinationRefs:
    - loki-storage
  kubernetesPods:
    namespaceSelector:
      notNames:
        - kube-system
        - d8-system
```

**Comment by gyrter** [comment]
I found better idea - add metadataFilter like logFilter
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLoggingConfig
metadata:
  name: test-source
spec:
  type: KubernetesPods
  kubernetesPods:
    namespaceSelector:
      matchNames:
      - tests-whispers
    labelSelector:
      matchLabels:
        app: test
      matchExpressions:
        - key: "tier"
          operator: "In"
          values: ["cache"]
  logFilter:
  - field: foo
    operator: Exists
  - field: fo
    operator: DoesNotExist
  - operator: In
    field: foo
    values:
    - wvrr
  - operator: NotIn
    field: foo
    values:
    - wvrr
  - operator: Regex
    field: foo
    values:
    - ^wvrr
  - operator: NotRegex
    field: foo
    values:
    - ^wvrr
  metadataFilter:
  - operator: In
    field: container
    values:
    - nginx
  destinationRefs:
    - test-es-dest
```
