### ISSUE TITLE
Use a list of instance types when creating a NodeGroup

### ISSUE THREAD

**Issue by dspv** [deckhouse/deckhouse#2708]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

I wish to have a mixed instance types because sometimes some instances types are unavailable and I think it's not cool to create a nodeGroup per instance type. I want to specify a list of instance types when creating a nodeGroup.

### Proposed Solution

Here's basic example I wish to have it working

```
spec:
  diskSizeGb: 50
  diskType: gp3
  instanceTypes: 
     - r5.large
     - m5.large
     - c5.large
     - m5a.large
     - m5ad.large
```
