### ISSUE TITLE
[log-shipper] Generated config can contain same names for sources and sinks

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#277]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.26.0

### Expected Behavior

Unique names for vector pipeline.

### Actual Behavior

Module generates bad configs

### Steps To Reproduce

Apply `ClusterLoggingConfig` and `ClusterLogDestination` with same names
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLoggingConfig
metadata:
  name: loki
spec:
  type: KubernetesPods
  destinationRefs:
    - loki
---
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLogDestination
metadata:
  name: loki
spec:
  type: Loki
  loki:
    endpoint: http://loki.loki:3100
```

### Additional Information

Problem issued [here](https://github.com/deckhouse/deckhouse/issues/255#issuecomment-966147137)
