### ISSUE TITLE
[cni-cilium] L7 CiliumNetworkPolicies do not work

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#2806]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.38.0

### Expected Behavior

Filter the traffic based on L7 rules.

### Actual Behavior

All traffic in namespaces containing L7 policies is dropped even if the audit-policy mode is enabled.
It seems problematic because it can accidentally cause DOS in environments where users do not imply to cause any harm, e.g., production environments.

### Steps To Reproduce

1. Deploy policy to the `d8-user-authn` namespace:
```shell
kubectl -n d8-user-authn -f - <<EOF
  apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: http-ingress-visibility
  spec:
    endpointSelector:
      matchLabels: {}
    ingress:
    - fromEntities:
      - all
    - toPorts:
      - ports:
        - port: "80"
          protocol: TCP
        - port: "443"
          protocol: TCP
        - port: "5556"
          protocol: TCP
        - port: "5559"
          protocol: TCP
        - port: "8080"
          protocol: TCP
        - port: "9080"
          protocol: TCP
        - port: "50051"
          protocol: TCP
        - port: "9200"
          protocol: TCP
        rules:
          http:
          - {}
          EOF
```
2. The `dex` pod probes will start failing.
3. Check the `cilium-agent` container logs on the same node with the `dex` pod.

### Additional Information

I tried to deploy the upstream version of the agent ([v1.11.10](https://hub.docker.com/layers/cilium/cilium/v1.11.10/images/sha256-fbcc8425d5c2acc92d5ce6dbd0cf67bdc93587fe9db24993a6efabdbea9879ec?context=explore)). There were no segfaults, but policies still kept dropping the traffic.

### Logs

```shell
level=info msg="Envoy: Accepted access log connection" subsys=envoy-manager
level=info msg="[lds: add/update listener 'cilium-http-ingress:19976'" subsys=envoy-upstream threadID=2784
level=info msg="[all dependencies initialized. starting workers" subsys=envoy-config threadID=2784
level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=252
level=error msg="[Caught Segmentation fault, suspect faulting address 0x0" subsys=envoy-backtrace threadID=2792
level=error msg="[Backtrace (use tools/stack_decode.py to get line numbers):" subsys=envoy-backtrace threadID=2792
level=error msg="[Envoy version: 9c0d933166ba192713f9e2fc3901f788557286ee/1.21.1/Distribution/RELEASE/BoringSSL" subsys=envoy-backtrace threadID=2792
level=error msg="[#0: [0x55b396efdb10]" subsys=envoy-backtrace threadID=2792
level=error msg="[#1: [0x55b396efdebb]" subsys=envoy-backtrace threadID=2792
level=error msg="[#2: [0x55b396eee2fd]" subsys=envoy-backtrace threadID=2792
level=error msg="[#3: [0x55b396e92454]" subsys=envoy-backtrace threadID=2792
level=error msg="[#4: [0x55b396e94b17]" subsys=envoy-backtrace threadID=2792
level=error msg="[#5: [0x55b396e94d1e]" subsys=envoy-backtrace threadID=2792
level=error msg="[#6: [0x55b39661489a]" subsys=envoy-backtrace threadID=2792
level=error msg="[#7: [0x55b396eee5b3]" subsys=envoy-backtrace threadID=2792
level=error msg="[#8: [0x55b396ef2758]" subsys=envoy-backtrace threadID=2792
level=error msg="[#9: [0x55b39703c162]" subsys=envoy-backtrace threadID=2792
level=error msg="[#10: [0x55b39703c8ef]" subsys=envoy-backtrace threadID=2792
level=error msg="[#11: [0x55b3966fcab3]" subsys=envoy-backtrace threadID=2792
level=error msg="[#12: [0x55b397236639]" subsys=envoy-backtrace threadID=2792
level=error msg="[#13: start_thread [0x7f232e96e609]" subsys=envoy-backtrace threadID=2792
level=info msg="Envoy: Closing access log connection" subsys=envoy-manager
```

**Comment by nabokihms** [comment]
It seems like DNS policies also do not work but cause no traffic loss
https://docs.cilium.io/en/v1.12/policy/language/#dns-policy-and-ip-discovery

**Comment by fl64** [comment]
L7 rules for http should only apply to the http protocol, it will not work for other protocols. The correct policy in this case looks something like this:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: http-ingress-visibility
  namespace: d8-user-authn
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEntities:
    - all
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "8080"
        protocol: TCP
      - port: "9080"
        protocol: TCP
      rules:
        http:
        - {}
    - ports:
      - port: "50051"
        protocol: TCP
      - port: "5559"
        protocol: TCP
      - port: "5556"
        protocol: TCP
      - port: "443"
        protocol: TCP
      - port: "9200"
        protocol: TCP
```

Regarding stacktrace for envoy. I did an experiment on a clean cluster (without deckhouse) with the following versions of cilium v1.11.5 (similar to the version used in deckhouse) and v1.12.3. For v1.11.5 the problem is present, there are stacktraces in the logs. In v1.12.3 there is no such problem.
