### ISSUE TITLE
[bashible] Send bashible errors and warnings as events to default namespace

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#2827]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes, bashible has error while execution on node. For debug it, we need to connect to node and look at bashible logs via `journalctl -xefu bashible.service`. It is not comfortable and in some closed environments we cannot login on the node.

### Proposed Solution

We can create events in `bb-error` and `bb-warning` bashbooster functions as in the next example:
```
bb-kubectl apply -f - <<EOF
apiVersion: v1
kind: Event
metadata:
  name: CannotApplyKubeletConfiguration
  namespace: default
type: Error
message: 'Blah blah blah'
involvedObject:
    kind: Node
    name: application-nodes-c2311bf3-66f6b-t566g
    uid: application-nodes-c2311bf3-66f6b-t566g
EOF
```
