### ISSUE TITLE
[prometheus] Prometheus may never start due to startupProbe

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#2884]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.38.4

### Expected Behavior

Prometheus starts up all the time. Nothing hinders that assumption.

### Actual Behavior

If a combination of a slow disk and congested CPU is present, Prometheus may spend a lot of time recovering WALs.

### Steps To Reproduce

`kill -9` prometheus process. Ensure that it starts on a slow host system. It'll recover WAL segments longer than 15 minutes and will get forcefully shut down after that. It'll start again and again, never finishing.

### Additional Information

```
    startupProbe:
      failureThreshold: 60
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 3
```
