### ISSUE TITLE
[cni-cilium] Unprivileged mode

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#2961]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The Cilium DaemonSet was always run as containers in privileged mode. Starting with Cilium 1.12, it is now possible to run Cilium as an unprivileged container. By adopting a least-privilege model, we can now give the exact Linux capabilities required by the Cilium DaemonSet instead of full permission. This reduces any potential cyber attack surface.

### Proposed Solution

```yaml
securityContext:
  privileged: false
  capabilities:
    drop:
      - ALL
    add:
      # Use to set socket permission
      - CHOWN
      # Used to terminate envoy child process
      - KILL
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # Used since cilium creates raw sockets, etc...
      - NET_RAW
      # Used since cilium monitor uses mmap
      - IPC_LOCK
      # Used in iptables. Consider removing once we are iptables-free
      - SYS_MODULE
      # We need it for now but might not need it for >= 5.11 specially
      # for the 'SYS_RESOURCE'.
      # In >= 5.8 there's already BPF and PERMON capabilities
      - SYS_ADMIN
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      #- PERFMON
      #- BPF
```

### Additional Information

https://isovalent.com/blog/post/cilium-release-112
