### ISSUE TITLE
[openapi] empty default should not be specified for required fields

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#2987]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

main

### Expected Behavior

OpenAPI cases test should not fail for this setup:

MODULE/openapi/values.yaml
```
type: object
properties:
  internal:
    type: object
    required:
    - someCert
    properties:
      nonRequired:
        type: string
      cert:
        type: object
        default: {}
        required:
          - ca
          - crt
          - key
        properties:
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          crt:
            type: string
            x-examples: [ "YjY0ZW5jX3N0cmluZwo=" ]
          key:
            type: string
            x-examples: [ "YjY0ZW5jX3N0cmluZwo=" ]        
```

MODULE/openapi/openapi-case-tests.yaml
```
negative:
  values:
  - internal:
      nonRequired: "some-value"
```

### Actual Behavior

`make test-openapi` fails because negative case validates successfully.

### Additional Information

The root cause is using `default:{}` and `required` for required object. We think it is a valid schema, and JSON schema spec tells us it is:

> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process.
Source: [JSON Schema spec/Generic keywords](https://json-schema.org/understanding-json-schema/reference/generic.html)

And here is the implementation of the "validation process" in go-openapi/validate:

```
	createdFromDefaults := map[string]bool{}

	// Property types:
	// - regular Property
	for pName := range o.Properties {
		...

		// Recursively validates each property against its schema
		if v, ok := val[pName]; ok {
			...
		} else if pSchema.Default != nil {
			// If a default value is defined, creates the property from defaults
			// NOTE: JSON schema does not enforce default values to be valid against schema. Swagger does.
			createdFromDefaults[pName] = true
			...
		}
	}

	// Check required properties
	if len(o.Required) > 0 {
		for _, k := range o.Required {
IT IS OK IF REQUIRED FIELD IS NOT SPECIFIED BUT HAS DEFAULT
-----------------------------------------------------v
			if v, ok := val[k]; !ok && !createdFromDefaults[k] {
				res.AddErrors(errors.Required(o.Path+"."+k, o.In, v))
				continue
			}
		}
	}
```

Source: [go-openapi/validate/object_validator.go](https://github.com/go-openapi/validate/blob/1bf2a53c9bf94e3e40bbca170946fbaae77c3c8b/object_validator.go#L204-L235)

It seems we need to remove `default: {}` from all required certs and other such properties.
