### ISSUE TITLE
[user-Authn] unknown field "insecureSkipVerify"

### ISSUE THREAD

**Issue by k3NGuru** [deckhouse/deckhouse#3126]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.39.2

### Expected Behavior

When i set insecureSkipVerify: true in DexProvider, Dex skip errors for untrusted domains
`dex failed to initialize server: server: Failed to open connector keycloak-test: failed to open connector: failed to create connector keycloak-test: failed to get provider: Get "https://lk.keycloak.test/auth/realms/master/.well-known/openid-configuration": x509: certificate relies on legacy Common Name field, use SANs instead `

### Actual Behavior

error: error validating "keycloak.yml": error validating data: ValidationError(DexProvider.spec.oidc): unknown field "insecureSkipVerify" in io.deckhouse.v1.DexProvider.spec.oidc; if you choose to ignore these errors, turn validation off with --validate=false

### Steps To Reproduce

my keycloak oidc
```
apiVersion: deckhouse.io/v1
kind: DexProvider
metadata:
  name: keycloak-test
spec:
  type: OIDC
  displayName: Test Keycloak
  oidc:
    issuer: https://lk.keycloak.test/auth/realms/master
    clientID: cpicb-k8s
    clientSecret: dasdsajkdl-dasda-dsadas-dasd
    insecureSkipEmailVerified: true
    insecureSkipVerify: true
    getUserInfo: true
```
