### ISSUE TITLE
No extended monitoring is deployed on EE cluster (alpha channel)

### ISSUE THREAD

**Issue by Nitive** [deckhouse/deckhouse#32]
Hello!

I've setup bare-metal cluster (EE) with Deckhouse but extended monitoring and k8s-image-availability-exporter haven't been created.

```
$ kubectl get po -n d8-monitoring -l app=extended-monitoring-exporter
No resources found in d8-monitoring namespace.
```

There is also `ExtendedMonitoringTargetDown` alert.

How can I enable extended monitoring or disable alert?

<details>
<summary>deckhouse ConfigMap</summary>

```
  certManager: |
    email: [redacted]
  cniFlannel: |
    podNetworkMode: VXLAN
  cniFlannelEnabled: "true"
  deckhouse: |
    bundle: Default
    logLevel: Info
    releaseChannel: Alpha
  flantIntegrationEnabled: "false"
  global: |
    modules:
        publicDomainTemplate: '%s.[redacted]'
  nginxIngressEnabled: "false"
  nodeManagerEnabled: "true"
  prometheusMadisonIntegrationEnabled: "false"
  upmeter: |
    auth:
        status: {}
        webui: {}
  userAuthn: |
    publishAPI:
      enable: true
  userAuthnEnabled: "true"
```

</details>
