### ISSUE TITLE
[Yandex Cloud Provider] Add a setting for CPU generation

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#328]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Cloud instances in Yandex Cloud have an option of CPU generation. The cost of these generations differ. E.g. Ice Lake is cheaper than Cascade Lake (see [pricing](https://cloud.yandex.com/en/docs/compute/pricing#prices-preemptible-instance-resources)). The option might offer a possibility of more cost-effective infrastructure. 

### Proposed Solution

In YandexInstanceClass CRD, we can add a field for the CPU platform. 

For example: 

```yaml
apiVersion: deckhouse.io/v1
kind: YandexInstanceClass
metadata:
  name: worker
spec:
  cores: 4
  memory: 8192
  diskSizeGb: 30
  cpuGeneration: IntelIceLake # enum: IntelBroadwell, IntelCascadeLake, IntelIceLake, AMDEPYC
```
