### ISSUE TITLE
[node-manager] D8NodeIsNotUpdating isn't being fired if bootstrap.sh hasn't finished

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#3300]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.41

### Expected Behavior

When the node is in cluster — it has to be monitored.

### Actual Behavior

If bootstrap.sh have done every step but stuck on some custom one, the node will join the cluster. The problem is — it won't update in future due to lock file occupation.

### Steps To Reproduce

* Deploy the custom step:
```
apiVersion: deckhouse.io/v1alpha1
kind: NodeGroupConfiguration
metadata:
  name: jam.sh
spec:
  weight: 100
  bundles:
  - "*"
  nodeGroups:
  - "worker"
  content: |
    tail -f /dev/null
```
* Scale the NG worker
* New worker will join but won't update and the D8NodeIsNotUpdating alert won't fire.
