### ISSUE TITLE
[dashboard] Impossible to show list of services if there is ingress without http rules in namespace

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3440]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.42.2

### Expected Behavior

List of services in namespace is always accessible

### Actual Behavior

If there is ingress without http rules exists in namespace:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 https://my.another.pretty.domain$request_uri;
  name: my-pretty-ingress
  namespace: my-pretty-namespace
spec:
  ingressClassName: nginx
  rules:
  - host: my.pretty.domain
  tls:
  - hosts:
    - my.pretty.domain
```
there is panic in https://github.com/kubernetes/dashboard/blob/master/modules/api/pkg/resource/ingress/filter.go#L39, because rule.IngressRuleValue is nil.
