### ISSUE TITLE
[virtualization] Implement VirtualMachineImage resource

### ISSUE THREAD

**Issue by kvaps** [deckhouse/deckhouse#3488]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Clone and store local versions of image directly in cluster

### Proposed Solution

They should reuse existing datasource mechanism from cdi

```yaml
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  name: ubuntu-2204
  namespace: default
spec:
  managedDataSource: ubuntu-2204
  schedule: "*/2 * * * *"
  template:
    spec:
      source:
        registry:
          pullMethod: node
          url: docker://dev-registry.deckhouse.io/sys/deckhouse-oss:92d31ba325ce661deddad46aae171db1d64536053b97da1652586e76-1666192123869
      storage:
        resources:
          requests:
            storage: 10Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: disk-mydata2
  namespace: default
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: linstor-thindata-r2
    volumeMode: Block
  sourceRef:
    kind: DataSource
    name: ubuntu-2204
```

### Additional Information

- https://blog.kingj.net/2022/06/02/how-to/auto-updating-vm-os-base-images-with-kubevirts-containerised-data-importer/
- https://github.com/kubevirt/containerized-data-importer/blob/main/doc/os-image-poll-and-update.md
