### ISSUE TITLE
[log-shipper] Vector reads only the first certificate from CA chain

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3547]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.42.3

### Expected Behavior

The `caFile` option works the same way as for the other destinations.

### Actual Behavior

The bug is related to https://github.com/confluentinc/librdkafka/commit/f8830a28652532009e3f16854cb9d5004d9de06b
It is fixed in librdkafka, but the version with the fix has not been released yet.

Users imply that the full chain will be applied.

### Steps To Reproduce

1. Create the following destination with caFile containing base64 and pem encoded CA chain:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLogDestination
metadata:
  name: test-kafka-dest
spec:
  type: Kafka
  kafka:
    bootstrapServers:
    - "192.168.1.1:9200"
    topic: "logs"
    tls:
      caFile: ""
```        
2. Try to request the server that listens using the certificate issued by this chain.
