### ISSUE TITLE
[ingress-nginx] suspected unsafe daemonset upgrades

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#3604]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.42

### Expected Behavior

daemonsets are being upgraded smoothly, one-by-one.

### Actual Behavior

There was a case when during d8 upgrade from 1.41 to 1.42 there were three unready ingress pods out of four.

![image](https://user-images.githubusercontent.com/18152319/214146349-8c641633-2600-4fcc-89aa-66e0a9b30e8a.png)

### Additional Information

```
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: nginx-balancer
spec:
  acceptRequestsFrom:
  - 1.2.3.4/32
  chaosMonkey: false
  config:
    keep-alive-requests: 10000
  disableHTTP2: false
  hostPortWithProxyProtocol:
    httpPort: 8080
    httpsPort: 8443
  hsts: false
  ingressClass: nginx
  inlet: HostPortWithProxyProtocol
  legacySSL: true
  maxReplicas: 1
  minReplicas: 1
  nodeSelector:
    node-role.deckhouse.io/frontend: ""
  resourcesRequests:
    mode: VPA
    vpa:
      cpu:
        max: 100m
        min: 10m
      memory:
        max: 200Mi
        min: 50Mi
      mode: Auto
  tolerations:
  - effect: NoExecute
    key: dedicated.deckhouse.io
    operator: Equal
    value: frontend
  underscoresInHeaders: false
  validationEnabled: false
```
