### ISSUE TITLE
[log-shipper] Add buffer settings

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3636]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Add buffer settings for the ClusterLogDestination.

### Proposed Solution

It is beneficial in two cases:
1. To drop logs if the destination does not respond https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#buffer.when_full
2. To increase the buffer for clusters with high data pressure https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#buffer.max_events

**Comment by nabokihms** [comment]
NOTE!: Do not forget to test behavior for a single source with multiple destinations.

**Comment by nabokihms** [comment]
Related https://github.com/deckhouse/deckhouse/issues/1352

**Comment by nabokihms** [comment]
An example of ClusterLogDestination settings:
```
buffer:
  type: Disk | Memory
  disk:
     maxSizeBytes: 268435488 # 256 Mb
  memory:
     maxEvents: 500
  whenFull: DropNew | Block
```
