### ISSUE TITLE
During installation main queue stucks with upmeter module

### ISSUE THREAD

**Issue by kostik2022** [deckhouse/deckhouse#3704]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v.1.42.6

### Expected Behavior

Going thru quickstart guide for bare-metal solutions and can login to web dashboard

### Actual Behavior

The main queue stucks at upmeter module.

### Steps To Reproduce

Follow quickstart guide (as for bare metal): 
1. Install master node
2. Add NodeGroup
3. Add worker node(s)
4. Add Ingress and User as described
5. Observe stucked main queue 

### Additional Information

Workaround: 
1. Disable upmeter module (using ordinary module config).
2. Drop deckhouse pod, and queue will continue. 

Additional files attached.
[upmeter_module-values.log](https://github.com/deckhouse/deckhouse/files/10547136/upmeter_module-values.log)
[queue.log](https://github.com/deckhouse/deckhouse/files/10547139/queue.log)

**Comment by kostik2022** [comment]
**Btw**, render output of the upmeter module shows "JSON format error" when issue occured.

**Btw2**. Initial config is very simple: 
`apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Static
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: "1.23"
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  releaseChannel: Stable
  configOverrides:
    global:
      modules:
        publicDomainTemplate: "%s.deck.local"
    cniFlannelEnabled: true
    cniFlannel:
      podNetworkMode: VXLAN
---
apiVersion: deckhouse.io/v1
kind: StaticClusterConfiguration
internalNetworkCIDRs:
- X.X.X.X/24`

**Comment by yalosev** [comment]
```
          zone: NONE
```
inside upmeter values

**Comment by shvgn** [comment]
Thanks for the report. The issue seems to be in annotations type casting.

From your upmeter values, smoke mini pods are scheduled on nodes named as numbers.

```yaml

    smokeMini:
      sts:
        a:
          # ...
          node: "564877"
        b:
          # ...
          node: "564863"
        c:
          # ...
          node: "564856"
        d:
          # ...
          node: "564870"
        e:
          # ...
          node: "564856"
```

The error clearly says it is a type conflict in annotations

> unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string

My guess is that the annotation contains unquoted number and it breaks the unmarshalling. Node names are in fact rendered unquoted in annotations ([code](https://github.com/deckhouse/deckhouse/blob/main/modules/500-upmeter/templates/smoke-mini/statefulsets.yaml#L44)).

```helm
  annotations:
    node: {{ $sts.node }}
    {{- if ne ($sts.zone) "NONE" }}
    zone: {{ $sts.zone | quote }}
    {{- end }}
```

If I'm right, the minimal thing you can do is to disable smoke-mini. It will turn off synthetic probe group in Upmeter. All other upmeter probes can continue working. See `smokeMiniDisabled` parameter in the ([doc](https://deckhouse.io/documentation/v1/modules/500-upmeter/configuration.html#parameters-smokeminidisabled)). To achieve that, create Upmeter config of this content

```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: upmeter
spec:
  settings:
    smokeMiniDisabled: false
  version: 2
```
