### ISSUE TITLE
[cloud-provider-yandex] WithNAT layout setup

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#3877]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When we are configuring cluster to be deployed on Yandex cloud with WithNAT layout we have to fill next config:
```yaml
withNATInstance:
  natInstanceExternalAddress: <NAT_INSTANCE_EXTERNAL_ADDRESS>
  internalSubnetID: <INTERNAL_SUBNET_ID>
  externalSubnetID: <EXTERNAL_SUBNET_ID>
```

`withNATInstance` could not be empty.
If we setup cluster with deckhouse, we don't know internal and external subnet ids because they are not created yet.
Also we don't know external IP. Only one way now - is to create external IP before the setup and use it during the installation.

### Proposed Solution

Probably, we can add `Auto` value for `natInstanceExternalAddress`. Deckhouse will create a dynamic IP address and attach it to this field

### Additional Information

https://deckhouse.io/documentation/v1/modules/030-cloud-provider-yandex/layouts.html#withnatinstance
