### ISSUE TITLE
[node-manager] relax restrictions for time.Duration settings, forbid m0sh

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#4199]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.43

### Expected Behavior

I can use mixed time modifiers to set time.Durations: 1h25m or 2h30m.

### Actual Behavior

Some settings restrict time.Duration for one modifier: 1h or 30m.

- [x] 1. modules/010-user-authn-crd/crds/user.yaml 
Addressed in https://github.com/deckhouse/deckhouse/pull/4200

```
spec.ttl field

                ttl:
                  type: string
                  pattern: '^\d+(?:m|h)$'  30d
                  description: |
                    Static user TTL.
                    * It is specified as a string containing the time unit: 30m, 1h, 24h. Either in minutes or hours.
                    * You can only set the TTL once. The `expireAt` date will not be updated if you change it again.
                  example: '24h'
```

- [x] 2. candi/openapi/node_group.yaml
Addressed in https://github.com/deckhouse/deckhouse/pull/4200

CRD NodeGroup

```
spec.chaos.period
                    period:
                      type: string
                      description: |
                        The time interval to use for the chaos monkey (can be specified in the [Go format](https://golang.org/pkg/time/#ParseDuration)).
                      pattern: "^[0-9]+[mh]{1}$"
```

- [x] 3. modules/002-deckhouse/openapi/config-values.yaml
Addressed in https://github.com/deckhouse/deckhouse/pull/4200

```
          minimalNotificationTime:
            type: string
            pattern: '^[0-9]+[mh]{1}$'
            x-doc-example: '6h'
```

- [ ] 4. modules/150-user-authn/openapi/config-values.yaml

```
  idTokenTTL:
    type: string
    pattern: '^[0-9]+[smh]{1}$'
```    

This value goes to dex configuration in expiry section: https://dexidp.io/docs/id-tokens/#expiration-and-rotation-settings

> NOTE: All duration options should be set in the format: number + time unit (s, m, h), e.g., 10m.

It seems a patch for dex is required.

- [ ] 5. modules/040-control-plane-manager/openapi/config-values.yaml

```
      apiserver:
        authn:
          webhookCacheTTL:
            type: string
            pattern: '([0-9]*(\.[0-9]*)?[hms]+)+'
            description: |
              The duration to cache responses from the webhook token authenticator.
            x-examples:
            - "5m"
```

This value goes to `authentication-token-webhook-cache-ttl` setting in kube-apiserver. 
Strange regex: `.s.s.s` and `m0sh` are valid.

- [x] 6. modules/010-prometheus-crd/crds/customalertmanager.yaml

```
spec.internal.route
                        groupInterval:
                          description: |
                            How long to wait before sending an updated notification.

                            Must match the regular expression `[0-9]+(ms|s|m|h)` (milliseconds,
                            seconds, minutes, hours).
                          type: string
                        groupWait:
                          description: |
                            How long to wait before sending the initial notification.

                            Must match the regular expression `[0-9]+(ms|s|m|h)` (milliseconds,
                            seconds, minutes, hours).
                          type: string
                        repeatInterval:
                          description: |
                            How long to wait before repeating the last notification.

                            Must match the regular expression `[0-9]+(ms|s|m|h)` (milliseconds,
                            seconds, minutes, hours).
                          type: string
```

Needs investigation on alert-manager settings

- [ ] 7. modules/040-terraform-manager/openapi/config-values.yaml                          

```
 autoConvergerPeriod:
     type: string
     default: "1h"
     pattern: '^\d+(?:m|h)$'
     description: |
       The time interval after which the state of Terraform is checked and applied.
```

Needs investigation about deprecated state.
