### ISSUE TITLE
[ingress-nginx] Detailed default backend metrics

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4248]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The counter is incremented if a request goes to the default backend.
https://github.com/deckhouse/deckhouse/blob/56398fcf6c910a83a3f2887d5b2e74f6e6b0716c/modules/402-ingress-nginx/images/controller-1-6/rootfs/etc/nginx/lua/pbmetrics.lua#L214-L217

However, the default backend can handle requests to different locations. The following ingress resource will add the `/test` path to it:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: test
            port:
              name: http
        path: /test
        pathType: Prefix
```

### Proposed Solution

Add labels to the default backend request metric, including service, ingress, and location.
