### ISSUE TITLE
[user-authn] Add Group object

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4249]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The list of groups for static users is stored in the User object as its attribute:

```yaml
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: test
spec: 
  groups:
  - team-a
  - team-b
```

It is technically correct but not convenient to manage.

### Proposed Solution

First, we need to define the new object `Group` to fix the problem.

Example:
```yaml
---
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: team-a
members:
- kind: User
  name: test-1
---
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: team-b
members:
- kind: User
  name: test-2
- kind: Group
  name: team-a
status:
  errors:
  - message: User does not exist in the cluster.
    objectRef:
       kind: User
       name: test-2
    
```

With this, treating groups as objects with properties will be possible. 
1. Groups can be nested, e.g., team-a and cluster-administrators.
2. Unknown users will be highlighted and ignored.
3. Groups with the `system:` prefix must be forbidden. 

Users can be added and deleted from the group.

TODO list:
1. Add group subscription to the users hook handler. 
2. Start rendering `Passwords` for the Dex from two resources.
3. Generate the group list according to the group/user matches.
4. Declare a new version of CRD for Users without groups, but do not change the storage version.
5. Delete groups from User objects in the doc.

**Comment by vitaliy-sn** [comment]
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.deckhouse.io
  labels:
    heritage: deckhouse
    module: user-authn
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: groups
    singular: group
    kind: Group
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema: &schema
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              description: |
                Contains information about a user group.
              required:
                - members
              properties:
                members:
                  type: array
                  items:
                    type: object
                    required:
                      - kind
                      - name
                    properties:
                      kind:
                        type: string
                        description: Object type.
                        enum:
                          - User
                          - Group
                      name:
                        type: string
                        description: User or group name.
                status:
                  type: object
                  required: []
                  properties:
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          message:
                            type: string
                          objectRef:
                            type: object
                            properties:
                              kind:
                                type: string
                                enum:
                                  - User
                                  - Group
                              name:
                                type: string

```
