### ISSUE TITLE
[deckhouse] Generate CRDs from Go structures

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4251]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The problem is simple:

CRDs are used for declaring a new object type in Kubernetes. After creation, Deckhouse hooks control these objects.
This pattern requires a developer to write twice the same structure for CRDs and Go structures.

### Proposed Solution

For convenience, Kubernetes community developed a project called [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder). However, to add it to Deckhouse, some special cases should be covered:

1. `oneOf` for required values to only allow one field specified at a time:
```yaml
oneOf:
- required: ["regex"]
- required: ["notRegex"]
```
2. Type structure (type enum and a field with settings for each type):
```yaml
type: CloudEphemeral
cloudEphemeral:
  instanceClassRef: ...
```
```yaml
inlet: HostPort
hostPort:
  http: 80
  https: 443
```

3. Python hooks classes (maybe it is better to generate structs and classes from CRDs, not vice versa).
4. Multilanguage support (for the Russian language).
5. `x-doc-default`, `x-deprecated`, other `x` varibales.

### Additional Information

Funny comment I found on the Internet.
```
// Dear maintainer:
//
// Once you are done trying to 'optimize' this routine,
// and have realized what a terrible mistake that was,
// please increment the following counter as a warning
// to the next guy:
//
// total_hours_wasted_here = 42
```

**Comment by shvgn** [comment]
> `oneOf` for required values to only allow one field specified at a time

How does kubernetes cope with it?

> Type structure (type enum and a field with settings for each type)

Type/inlet can be deduced from present named field (e.g `hostPort: {}` in ingress controller CRD). So, type/inlet can be omitted at all. It would be necessary to have type if we had `type`+`data`, where `data` had varying schema depending on `type`. But it is not the case.

**Comment by nabokihms** [comment]
> How does kubernetes cope with it?

This is valid, Kubernetes does not restrict oneOf for required fields. Such schemas are considered as structured.

> Type/inlet can be deduced from present named field

The approach to writing specs this way was proposed at the early ages of Deckhouse, because there are similar constructions in Kubernetes API, e.g., deployment rolling update settings

```yaml
type: RollingUpdate
rollingUpdate:
  maxSurge: 3
  maxUnavailable: 1
  timeoutSeconds: 100
```
