### ISSUE TITLE
[global] Automatic node selector and tolerations behavior

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4313]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is a problem that the automatic calculation of node selectors and taints is puzzling.

1. It can either be a string or an object, which is difficult to handle in statically typed languages, e.g., Go.
2. Meaning of the variants to specify is obscure:
    * No `nodeSelector` provided = automatic node selector calculation is used.
    * `nodeSelector: false` = empty node selector
    * `nodeSelector: {"frontend": "true"}` = custom node selector

### Proposed Solution

1. New API, e.g., 
```yaml
nodeSelector:
  type: Auto (default) | Manual
  manual:
    node-role.kubernetes.io/master: ""   
tolerations:
  type: Auto (default) | Manual
  manual:
  - operator: Exists   
``` 
or
```yaml
placement:
  nodeSelectorAuto: true
  nodeSelector: {}
  tolerationsAuto: false
  tolerations: []
```
(nodeSelectorAuto and nodeSelector are mutually exclusive).
 
2. Migration

### Additional Information

https://deckhouse.io/documentation/v1/#advanced-scheduling
```
If no nodeSelector/tolerations are explicitly specified in the module parameters, the following strategy is used for all modules:
* If the nodeSelector module parameter is not set, then Deckhouse will try to calculate the nodeSelector automatically. Deckhouse looks for nodes with the specific labels in the cluster (see the list below). If there are any, then the corresponding nodeSelectors are automatically applied to module resources.
* If the tolerations parameter is not set for the module, all the possible tolerations are automatically applied to the module’s Pods (see the list below).
* You can set both parameters to false to disable their automatic calculation.

You cannot set nodeSelector and tolerations for modules:
- that involve running a DaemonSet on all cluster nodes (e.g., cni-flannel, monitoring-ping);
- designed to run on master nodes (e.g., prometheus-metrics-adapter or some vertical-pod-autoscaler components).
```
