### ISSUE TITLE
[ingress-nginx] Add status to IngressNginxController CRD

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#4344]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is much more convenient to see importatn parts in the same CR as the configurations. Otherwise, the state of the contreoller must be dedicated from service (in case Loadbalancer) or DaemonSet pods in case of workload issues.

Also, some of the configuration is configured automatically, but it can be seen only from workload manifests, and it can be unobvious. 

### Proposed Solution

Add status to IngressNginxController CRD with this content

```yaml
status:  
  loadBalancer:
    # the state of the load balancer in cloud provider 
    # for inlets LoadBalancer and LoadBalancerWithProxyProtocol
    state: Pending | Ready | Error
    # if state==Error
    error: quota exceeded 
    address?: 1.2.3.4
    id?: lb-abracadabra012355.aws.whatever.here
 
  workloads: 
    # If not configured by user, this spec is calculated in helm templates. 
    # We want to show them in any case. If this config is not common for controllers, 
    # it should be placed under `controllers.<name>` fields
    nodeSelector:
      ...
    tolerations: 
      ...

    controllers:
      # It does not matter which controller is used
      main:
        podStats:
          # deduced from DaemonSet status
          ready: 2
          desired: 3
          # updating counter can be deduced from DaemonSet hash
          updating: 1

      # If there is second controller
      failover:
        podStats:
          ready: 3
          desired: 3
          updating: 0
```
