### ISSUE TITLE
[deckhouse] Module CRD

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#4421]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to add new module CRD. When addon-operator is registering a module, new crd must be created in the cluster.
It shouldn't be updated by user, only by controller.
We need to add more information to the each module, something like `module.yaml` with extra information, which will be used or copied to the module

### Proposed Solution

I assume all of these should be implemented in the addon-operator, to work natively with Modules:
- Read `module.yaml` on a module startup
- Register module inside
- Create module CRD on registering
- Calculate the map of uniqueness
- Sort modules
- Start module with the respect of unique key and order

Also we have to realize validation webhook in the addon operator, to prohibit module crd change by user

### Additional Information

`module.yaml` structure:
```yaml
name: "my-super-module" # same name as in Chart.yaml, we have to sync or validate it with Chart.yaml
namespace: "my-ns" # instead of .namespace
disableImpact: "Some description why we can not do this"
dependencies: # skip on the first phase
  modules: ["module-1", "module-2"] 
enableOnBoostrap: true # **boolean**: can be used instead of enabled scripts
!!!Think more uniqueKey: "cni" # some unique key for the category. Only one module with this key must be enabled
labels: ["crd", "cni"] # tags for filtering, when can move it to the Module CRD label
weight: 100 # module weight, instead of number in the module name
```

`Module` CRD example:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: Module
metadata:
  name: my-super-module
  labels:
    module.deckhouse.io/crd: ""
    module.deckhouse.io/cni: ""
properties:
  weight: 100
#  namespace: "my-ns" # 2 wave
#  uniqueKey: "cni" 
#  disable:
#    impact: "critical" 
```
