### ISSUE TITLE
[user-authn] ClusterAuthorizationRule with no subjects blocks deckhouse main queue with render error

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#4460]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45

### Expected Behavior

Deckhouse queue is not stuck	

### Actual Behavior

Deckhouse main queue stops with following error

```
ModuleRun:main:user-authz:Kubernetes-Change-ModuleValues:failures 7:YAML parse error on user-authz/templates/cluster-role-bindings.ya
ml: error converting YAML to JSON: yaml: line 14: could not find expected ':'
```

Adding a subject fixes the error.

### Steps To Reproduce

Create ClusterAuthorizationRule with empty subjects list

```yaml
apiVersion: deckhouse.io/v1
kind: ClusterAuthorizationRule
metadata:
  name: something
spec:
  accessLevel: User
  additionalRoles: []
  allowAccessToSystemNamespaces: false
  allowScale: false
  limitNamespaces: []
  portForwarding: false
  subjects: []
```

### Additional Information

I know it is pointless to have rules for nobody, but it would be simpler to automate this CR generation (less if's) and it is valid from the API perspective.
