### ISSUE TITLE
[multitenancy-manager] New module

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4488]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Utility clusters are an accepted practice in many large companies (also thanks to its popularizers such as OpenShift). Users want to be able to get isolated environments.

### Proposed Solution

It is proposed to take the two-stage logic of creating projects as a basis.

1. Create a type of Project.
2. Create a Project of the specific type.

Two cluster-wide CRDs:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ProjectType  
metadata:
  name:  default
spec:
  subjects: # from this block, the AuthorizationRule will be deployed https://github.com/deckhouse/deckhouse/issues/4484 
  - kind: ServiceAccount | User | Group 
    name: <subject name>
    namespace: <only for service accounts>
    role: User | PrivilegedUser | Editor | Admin
  namespaceMetadata:
    labels:
      security.deckhouse.io/pod-policy: ”Baseline”
    annotations: {}
  openAPI:
    cpuRequests:
      oneOf:
      - type: int
      - type: string
        pattern: '^[0-9]+m?$'
    memoryRequests:
      oneOf:
      - type: int
      - type: string
        pattern: '^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$'
  resourcesTemplate: | # use sprig functions for templating http://masterminds.github.io/sprig/
    ---
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: isolate-ns
    spec:
      podSelector:
        matchLabels:
          ingress:
          - from:
            - podSelector: {}
    ---
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: requests
    spec:
      hard:
        requests.cpu: {{ .params.cpuRequests }}
        requests.memory: {{ .params.memoryRequests }}
```

```yaml
apiVersion: deckhouse.io/v1alpha1
kind: Project  
metadata:
  name:  backend
spec: 
  description: <description of the purpose of what this project does>
  template:
    name: default
    params:
      cpuRequests: “1000”
      memoryRequests: “200Gi” 
status:
  conditions:
  - name: Sync
    status: true
  - name: Error
    status: true
    message: “<if occurred, the error message>”    
```
