### ISSUE TITLE
[multitenancy-manager] Dedicated nodes / node groups for the Project

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4530]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For the maximum level of isolation, it is better to give a team a set of dedicated nodes. In Kubernetes it is partially solved with the [`PodNodeSelector`](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector) admission controller.

### Proposed Solution

The pod node selector admission controller is still in alpha since the very beginning of Kubernetes. The main problem is that it does not set tolerations to pods, only selectors. Assuming that dedicated nodes are tainted, it is impossible to deploy workloads on them without tolerating the taint. A team should know the taint and add tolerations on their side, which is not usually convenient.

The best way to write our own podnodeselector-like controller is with the help of the admission-policy-engine module.

```yaml
apiVersion: deckhouse.io/v1alpha1
kind: EnforceNodesForNamespacePolicy
metadata:
  name: <name>
  namespace: <namespace>
spec:  
  nodeSelector:
    dedicated: backend
  tolerations: # should be appended to original tolerations
  - key: dedicated
    operator: Equal
    value: "backend"
```

or deploy a dedicated mutating webhook, or anything else.
