### ISSUE TITLE
Some deckhouse components cannot work if selinux in enforced mode

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#4563]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45

### Expected Behavior

All deckhouse components should work properly.

### Actual Behavior

Some of deckhouse components cannot work with selinux = enforcing.
1. Deckhouse-controller
2. Cilium
3. Linstor

### Steps To Reproduce

bootstrap node with selinux=enforcing

### Additional Information

Possible solution:
use 
```
securityContext:
          privileged: false
          seLinuxOptions:
            level: 's0'
            type: 'spc_t'
```
in components manifests.
