### ISSUE TITLE
[log-shipper] Remove namespace selectors by name

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4587]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are three types of selectors for namespaces in ClusterLoggingConfig for KubernetesPods:
1. Match names
2. Exclude names
3. Label selector

Actually, this is a tech dept because the label selector was introduced recently before we added the other two options to Deckhouse.

### Proposed Solution

Leave only the label selector option.

Match names and exclude names can be converted to a label selector. All namespaces have the label `kubernetes.io/metadata.name=` with the actual name of the namespace.

1. To convert match names to a label selector:
```yaml
labelSelector:
  matchExpressions:
  - key: "kubernetes.io/metadata.name"
    operator: In
    values: [default, kube-system]
```

2. To convert exclude names to a label selector:
```yaml
labelSelector:
  matchExpressions:
  - key: "kubernetes.io/metadata.name"
    operator: NotIn
    values: [default, kube-system]
```

### Additional Information

Do not forget to change examples.
