### ISSUE TITLE
[namespace-configurator] Migrate to MutatingWebhook

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4634]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

As of today, labels and annotations are set on namespaces after creating by a Deckhouse hook. All configuration is stored in a single module config. However, this approach is not suitable for some cases:
1. ArgoCD relies on mutating webhooks and doesn't allow you to change resources after deploying them.
2. OPA gatekeeper validates resources after mutation. With the current schema, it is not possible to check that all required labels are present while creating a namespace.
3. To combine it with the label selector of other CRDs, e.g., ClusterLoggingConfig, OperationPolicy, it is not convenient to store configuration in a single place because all deployments should modify it.

### Proposed Solution

The first thing is to migrate to the MutatingWebhook solution.

1. Add a cluster-wide CRD for `NamespaceConfig`:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: some-name
spec:
  assignMetadata:
    labels:
      foo: bar
    annotations:
      extended-monitoring.flant.com/enabled: "true"
  matchNames:
  - include:
    - "^prod" # regex
    - "^infra" 
  - exclude:
    - "infra-test"
```  
2. Add a Deckhouse hook that collects all CRs and composes a config.
3. Add a go-based admission webhook that accepts the config and does mutations.
4. Deploy this webhook on master nodes.
