### ISSUE TITLE
[flant-integration] Create additional parametrization fields for module flant-integration 

### ISSUE THREAD

**Issue by arens-space** [deckhouse/deckhouse#4660]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We don't have the functionality to provide a custom domain name for sending alerts to the customer gateway. Moreover, the name of the module is a hardcoded value - it would be great to have the ability to change this name from flant-integration to something more general.

### Proposed Solution

Provide an ability to specify domainName in the ModuleConfig object and change the name of the module:

```
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: external-integration
spec:
  enabled: true
  settings:
    kubeall:
      host: host.com
      kubeconfig: /etc/kubernetes/admin.conf
    madisonDomainName: example.com
```
