### ISSUE TITLE
[istio] automatically create istio Sidecar default with a list of ns that have istio-proxy 

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#4711]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

This change will reduce the memory consumption of istio-proxy and probably will not affect the visibility of services in the cluster for istio-proxy.

### Proposed Solution

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: d8-istio
spec:
  egress:
  - hosts:
    - "d8-istio/*"
    - "d8-ingress-nginx/*"
  ...
```
