### ISSUE TITLE
[alertmanager] Incorrect СR example for ignoring allerts

### ISSUE THREAD

**Issue by Sprait** [deckhouse/deckhouse#4851]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46.5

### Expected Behavior

Current example in documenation:

```
route:
  routes:
  - match:
      alertname: DeadMansSwitch
    receiver: blackhole
  - match_re:
      service: ^(foo1|foo2|baz)$
    receiver: blackhole
  - receiver: some-other-receiver
```
generates a wrong config and allerts will not be ignored:
```
~ $ cat /etc/alertmanager/config_out/alertmanager.env.yaml
route:
  receiver: d8-monitoring/debug/blackhole
  routes:
  - receiver: d8-monitoring/debug/blackhole
  - receiver: d8-monitoring/debug/blackhole
  - receiver: d8-monitoring/debug/some-other-receiver
receivers:
- name: d8-monitoring/debug/blackhole
- name: d8-monitoring/debug/some-other-receiver
templates: []
```

### Actual Behavior

need to update the documentation, correct example for ignoring some alert looks something like this:
```
  internal:
    receivers:
    - name: blackhole
    - name: some-other-receiver
    route:
      receiver: some-other-receiver
      routes:
      - matchers:
        - matchType: =
          name: alertname
          value: DeadMansSwitch
        - matchType: =~
          name: service
          value: ^(foo1|foo2|baz)$
        receiver: blackhole
      - receiver: some-other-receiver
```
resulting config:
```
~ $ cat /etc/alertmanager/config_out/alertmanager.env.yaml
route:
  receiver: d8-monitoring/debug/some-other-receiver
  routes:
  - receiver: d8-monitoring/debug/blackhole
    matchers:
    - alertname="DeadMansSwitch"
    - service=~"^(foo1|foo2|baz)$"
  - receiver: d8-monitoring/debug/some-other-receiver
receivers:
- name: d8-monitoring/debug/blackhole
- name: d8-monitoring/debug/some-other-receiver
templates: []
```
