### ISSUE TITLE
[log-shipper] Add destination socket sink to vector

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#4861]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Delivering logs to remote socket endpoints is often requested feature

### Proposed Solution

Add feature to configure destination socket sink for log-shipper mc

**Comment by meatuses** [comment]
https://vector.dev/docs/reference/configuration/sinks/socket/

**Comment by meatuses** [comment]
sample config
```
    sinks:
      uib_siem:
        address: *****:514
        encoding:
          codec: json
        inputs:
        - cloud_kuber_audit
        mode: udp
        type: socket
```
