### ISSUE TITLE
[runtime-audit-engine] unset FALCO_BPF_PROBE env var

### ISSUE THREAD

**Issue by artbin** [deckhouse/deckhouse#4930]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47.0

### Expected Behavior

The Falco container starts without error `Error: You can not specify more than one of -e, -u (--userspace), -g (--gvisor-config), --modern-bpf, --nodriver, and the FALCO_BPF_PROBE env var`

### Actual Behavior

The Falco container starts with error `Error: You can not specify more than one of -e, -u (--userspace), -g (--gvisor-config), --modern-bpf, --nodriver, and the FALCO_BPF_PROBE env var`

### Steps To Reproduce

Enable `runtime-audit-engine` module:
```
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: runtime-audit-engine
spec:
  enabled: true
```

### Additional Information

After bump Falco version to v0.35.0 in #4894 the Falco container failed to start.
