### ISSUE TITLE
[cloud-provider-aws] After adding etcdDisk the diskSizeGB parameter for CloudPermanent stopped working

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#4956]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46.8

### Expected Behavior

etcdDisk should not be inherited from the master ng and diskSizeGB should be taken into account.

### Actual Behavior

The server is created with the root disk of the default size, regardless of the specified size.

### Steps To Reproduce

kubectl -n d8-system exec -ti deploy/terraform-auto-converger -- dhctl config edit provider-cluster-configuration
```
piVersion: deckhouse.io/v1alpha1
kind: AWSClusterConfiguration
layout: WithoutNAT
masterNodeGroup:
  instanceClass:
    additionalSecurityGroups:
    - sg-.....
    ami: ami-0ec7f9846da6b0f61
    diskSizeGb: 50
    etcdDisk:
      sizeGb: 150
      type: gp3
    instanceType: m5.xlarge
  replicas: 3
nodeGroups:
- instanceClass:                                                      
    ami: ami-0ec7f9846da6b0f61                                        
    diskSizeGB: 50                                                    
    diskType: gp3                                                                                                        
    instanceType: t2.medium                                           
  name: etcd                                                          
  nodeTemplate:                                                       
    labels:                                                           
      node-role.flant.com/etcd: ""                                    
      node-role.kubernetes.io/etcd: ""                                
    taints:                                                           
    - effect: NoExecute                                               
      key: dedicated                                                  
      value: etcd                                                     
  replicas: 1                                                         
  zones:                                                              
  - eu-central-1a  
```
