### ISSUE TITLE
[user-authn] Validate that Group is linked to an existing User / Group

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#5123]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is a possibility to have a `Group` including another `Group`, e.g.
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: group-1
spec:
  name: group-1
  members:
  - kind: User
    name: m-nabokikh
---
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: group-2
spec:
  name: group-2
  members:
  - kind: Group
    name: group-1
```

However, it is not guaranteed that the `group-1` group from the example above exists.

### Proposed Solution

Validate the following conditions utilizing the deckhouse validating webhook:

1. If a `Group` is created or updated, check that all nested user / groups exist.
2. If a `Group` or `User` is deleted, check that other groups do not have references to the deleted one.
