### ISSUE TITLE
[node-manager] alert on impossible node drain

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5173]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When a node is not drained we create [log and event](https://github.com/deckhouse/deckhouse/blob/879577391cbddca3daef6e7125a16f9115aa9790/modules/040-node-manager/hooks/handle_draining.go#L184) with an error.
But drain could be impossible due to user reasons. Invalid PDB for example.
We will have an alert `D8NodeIsNotUpdating` but no info about failed drain.
I think we have to add metric and alert about failed node.

We have the [DisruptionApproval alert](https://github.com/deckhouse/deckhouse/blob/9a1102edc4e076039b8af5bc9f15e8e4bf3a2fa0/modules/040-node-manager/monitoring/prometheus-rules/node-update.yaml#L172) but it seems not informative and will not work for user-called drains.

### Proposed Solution

We can add a metric [here](https://github.com/deckhouse/deckhouse/blob/main/modules/040-node-manager/hooks/handle_draining.go#L184) and replace [alert NodeStuckInDrainingForDisruptionDuringUpdate](https://github.com/deckhouse/deckhouse/blob/9a1102edc4e076039b8af5bc9f15e8e4bf3a2fa0/modules/040-node-manager/monitoring/prometheus-rules/node-update.yaml#L172) with a new dedicated.

**Comment by Horiodino** [comment]
hey @yalosev i would like too contribute is there any more info you can provide regarding this issue.

**Comment by alexey-gavrilov-flant** [comment]
```
apiVersion: deckhouse.io/v1
kind: YandexInstanceClass
metadata:
  name: test
spec:
  cores: 2
  memory: 4096
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: test
spec:
  cloudInstances:
    zones:
      - ru-central1-a
    classReference:
      kind: YandexInstanceClass
      name: test
    maxPerZone: 2
    minPerZone: 1
  nodeTemplate:
    labels:
      node-role.deckhouse.io/test: ""
    taints:
    - effect: NoExecute
      key: dedicated.deckhouse.io
      value: test
  nodeType: CloudEphemeral
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node-role.deckhouse.io/test: ""
      tolerations:
      - key: dedicated.deckhouse.io
        operator: Equal
        value: test
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: nginx
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test
  namespace: test
spec:
  minAvailable: 1
  #maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx
```
