### ISSUE TITLE
[cluster-api] static provider

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#5178]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Join cluster static nodes very different from join cloud nodes. In case of cloud nodes we have cloud controller, which create new vm in the cloud, bootstrap them and join to the cluster. In the static nodes case we should manually start bootstrap script on every static node to bootstrap them and join.
We want to work with static nodes similar to work with cloud nodes (automatic bootstrap and join, change nodegroup size) 

### Proposed Solution

Create cluster-api infrastructure provider Static.

### Additional Information

Create cluster resources:
```
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
   name: hv-1
   labels:
     node-group: worker
spec:
   address: 2.2.2.2
   credentialsRef:
     Name: bootstrap-ssh 
status:
 ## Node group
 ## Status (node bootstrapped and joined or in the wait list)
---  
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstanceCredentials
metadata:
   name: bootstrap-ssh 
spec:
   user: ubuntu
   privateSSHKey: <b64-encoded-private-key>
   sudoPassword: <encrypted password>
   …
```

Write cluster-api inrfastructure provider which implements resources:
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StaticCluster
metadata:
  name: static
  namespace: d8-cloud-instance-manager
  ownerReferences:
    - kind: Cluster
      name: dev
      apiVersion: cluster.x-k8s.io/v1beta1
      uid: ab0374ed-9169-44d6-9881-bc579cb5d7c2
```
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StaticMachineTemplate
metadata:
  name: worker
  namespace: d8-cloud-instance-manager
spec:
  labelSelector:
  - nodegroup: worker
  template:
    spec:
      labels:
      taints:
```
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StaticMachine
metadata:
   name: hv-1
   labels:
     node-group: worker
spec:
   address: 2.2.2.2
   credentialsRef:
     Name: bootstrap-ssh 
status:
 ## Status
```

Controller should implement:
* If the number of ready machines is less than the desired number, select non-bootstrapped machines from StaticInstances and bootstrap them.
* If the number of ready machines is more than the desired number, clean up bootstrapped machines.
* If labels on StaticInstances have changed and Staticinstance has left the MachineDeployment selector, clean up the machine (transfer the node to another nodegroup).
* Set taints and labels passed from StaticMachineTemplate for the Node object.

Also we need to do:
* migration for current static nodes. The bootstrap.sh and cleanup.sh scripts should be removed from the cluster.
