### ISSUE TITLE
[candi][cloud-provider-yandex] Ubuntu 22.04 bootstrap fails in the case of additionalNetworks is present

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#5229]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47

### Expected Behavior

Cloud node with two or more network interfaces should bootstrap normally.

### Actual Behavior

Various problems with access to repositories, basshible apiserver etc., due to network route misconfiguration.

### Steps To Reproduce

1. Create instance Class
```
apiVersion: deckhouse.io/v1
kind: YandexInstanceClass
metadata:
  generation: 2
  name: test-a
spec:
  cores: 4
  diskSizeGB: 93
  diskType: network-ssd-nonreplicated
  memory: 8192
  networkType: Standard
  mainSubnet: e9bsia4kmfj8bt0r0vvn
  additionalSubnets:
  - e9bark874u9aqu3r02f6
```
2. Create nodeGroup
```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: test-a
spec:
  cloudInstances:
    classReference:
      kind: YandexInstanceClass
      name: test-a
    maxPerZone: 1
    minPerZone: 1
  nodeType: CloudEphemeral
```
3. Check logs on the created node.

### Additional Information

cloud init correctly initialize interfaces:
```
cat /etc/netplan/50-cloud-init.yaml
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        eth0:
            dhcp4: true
            dhcp4-overrides:
                route-metric: 100
            dhcp6: false
            match:
                macaddress: d0:0d:18:57:55:ec
            set-name: eth0
        eth1:
            dhcp4: true
            dhcp4-overrides:
                route-metric: 200
            dhcp6: false
            match:
                macaddress: d0:1d:18:57:55:ec
            set-name: eth1
    version: 2
```
AditionalNetwork default gw is added with less priority than mainNetwork.
But ubuntu 22.04 contains `/etc/netplan/00-installer-config.yaml` which applies first and configures interfaces by the improper way:
```
# This is the network config written by 'subiquity'
network:
  ethernets:
    any:
      dhcp4: true
      dhcp6: true
      match:
        name: e*
  version: 2
```

For every cloud provider we have `bootstrap-networks.sh.tpl`, problem should be solved there.
