### ISSUE TITLE
[delivery] Module does not work with CustomCertificate https mode

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5238]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47.3

### Expected Behavior

Custom certificate should be copied and module should start gracefully with Dex auth.

### Actual Behavior

Module `delivery` tries to copy custom certificate but fails with:
```
1. ModuleRun:main:delivery:doStartup:ReloadAllModules:failures 15:helm upgrade failed: failed to create resource: Secret "ingress-tls-argocd-customcertificate" is invalid: [data[tls.crt]: Required value, data[tls.key]: Required value]
```

module values are empty

### Steps To Reproduce

1. Create global ModuleConfig with the next settings:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  settings:
    modules:
      https:
        customCertificate:
          secretName: foobar
        mode: CustomCertificate
      publicDomainTemplate: '%s.example.com'
  version: 1
```

2. Enable ModuleConfig `delivery`
