### ISSUE TITLE
[grafana] error sending grafana alerts after creation new grafanaalertschannel

### ISSUE THREAD

**Issue by EvgeniiAl** [deckhouse/deckhouse#5265]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47.4

### Expected Behavior

grafana's alert sent through the notification channel to alertmanager

### Actual Behavior

Grafana is attempting to render an image for alert despite the corresponding checkbox being unchecked in the notification channel settings

### Steps To Reproduce

1. Create grafanaalertschannel
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: GrafanaAlertsChannel
metadata:
  name: telegram
spec:
  alertManager:
    address: http://alertmanager-telegram-0
  description: Channel to send alerts to somewhere
  disableResolveMessage: false
  isDefault: true
  type: PrometheusAlertManager
```
2. Verify that `include image` checkbox is empty in notification channel settings  https://grafana.kube.domain/alerting/notification/1/edit
3. Create a dashboard with alert
4. Look at grafana pod logs for error
```
logger=alerting.notifier.prometheus-alertmanager t=2023-07-18T16:22:31.32+0000 lvl=info msg="Sending Alertmanager alert" ruleId=1 notification=telegram
logger=rendering renderer=plugin t=2023-07-18T16:22:41.28+0000 lvl=info msg=Rendering path="d-solo/6gCf4sC4y/new-dashboard?orgId=1&panelId=2"
logger=plugin.grafana-image-renderer t=2023-07-18T16:22:41.3+0000 lvl=eror msg="Render request failed" url="http://127.0.0.1:3000/d-solo/6gCf4sC4y/new-dashboard?orgId=1&panelId=2&render=1" error="Error: Failed to launch the browser process!\n/etc/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"
logger=alerting.notifier t=2023-07-18T16:22:41.3+0000 lvl=eror msg="Failed to render and upload alert panel image." ruleId=1 error="rendering failed: Error: Failed to launch the browser process!\n/etc/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"
```
5. Check and uncheck `include image` checkbox  in notification channel settings 
6. Alert successfully sent without errors
