### ISSUE TITLE
[log-shipper] Deckhouse panics if a labelSelector is invalid

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#5382]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

![image](https://github.com/deckhouse/deckhouse/assets/32434187/cb1063ed-3ead-46ea-9ee6-ba2bc503b632)

### Proposed Solution

Use the following OpenAPI snippet in all label selectors (for matchExpressions):
```yaml
oneOf:
- properties:
    operator:
      enum: [Exists, DoesNotExist]
  required: [key, operator]
  not:
    required: [values]
- properties:
    operator:
      enum: [In, NotIn]
  required: [key, operator, values]
  ```
