### ISSUE TITLE
[candi][cloud-provider-openstack] Ubuntu 20.04/22.04 node bootstrap with additionalNetwork creates more than one default route

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#5452]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.49.2

### Expected Behavior

Cloud node with two or more ipv4 network interfaces configured for DHCP should not have ambiguous default routes

### Actual Behavior

Various network accessibility problems due to two or more default routes configured via DHCP

### Steps To Reproduce

1. Create OpenstackInstanceClass 
```
apiVersion: deckhouse.io/v1
kind: OpenStackInstanceClass
metadata:
  annotations:
  labels:
  name: test-routes
spec:
  additionalNetworks:
  - stage-kube
  flavorName: t-c4m12
  imageName: ubuntu-20-04-cloud-amd64
  mainNetwork: BGP-VLAN-1234
  rootDiskSize: 30
```
2. Create Nodegroup
```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: test-routes
spec:
  chaos:
    mode: Disabled
  cloudInstances:
    classReference:
      kind: OpenStackInstanceClass
      name: test-routes
    maxPerZone: 1
    minPerZone: 1
    zones:
    - TEST_ZONE_1
  cri:
    type: Containerd
  disruptions:
    approvalMode: Automatic
  kubelet:
    containerLogMaxFiles: 4
    containerLogMaxSize: 50Mi
    resourceReservation:
      mode: "Off"
  nodeTemplate:
    labels:
      node-role/loadbalancer: ""
    taints:
    - effect: NoExecute
      key: node-role/test-routes
      value: ""
  nodeType: CloudEphemeral
```
3. Check `ip route` on created node to see 2 default routes, one for each interface

### Additional Information

Cloud init script that configures network interfaces https://github.com/deckhouse/deckhouse/blob/main/ee/candi/cloud-providers/openstack/bashible/bundles/ubuntu-lts/bootstrap-networks.sh.tpl

`50-cloud-init.yaml` file on the affected node:
```
$ cat /etc/netplan/50-cloud-init.yaml
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        ens3:
            dhcp4: true
            match:
                macaddress: fa:16:3e:12:23:34
            mtu: 9000
            set-name: ens3
        ens4:
            dhcp4: true
            match:
                macaddress: fa:16:3e:23:34:45
            mtu: 8950
            set-name: ens4
```
Due to Ubuntu configuring both interfaces as DHCP on first boot, script linked above skips configuring additional interfaces to `use-routes: false`, not creating `/etc/netplan/100-cim-"$ifname".yaml` file
