### ISSUE TITLE
[node-manager] Consider removing misleading "Ready" condition type from NodeGroup

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#5513]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.50.0

### Expected Behavior

When upscaling a nodegroup from 1 to 2 the group should probably be "Ready"

### Actual Behavior

When upscaling a nodegroup from N>1 to N++ the group condition of type "Ready" becomes "False"

It is "Ready" when incrementing minPerZone from 0.

### Additional Information

To be honest, the 'readiness' condition is completely unclear. The confusion is this as follows:

* Is it about nodes readiness? How is it calculated across nodes? What is the interpretation?
  * (I saw the code, it is very specific, and it ignores availability zones while accounting minPerZone parameter) 
* Is it about a cloud API availability meaning node upscaling should work? 
* Is it about cluster-autoscaler availability meaning node downscaling should work? 
* It is about Deckhouse availability meaning node updates are ready to reach all nodes? Or bashible-apiserver availability?

The term "ready" does no make sense, gives no specific interpretation and becomes "False" under conditions where it would not be expected to. I thing the problem is more in the interpretation of "Readiness" then a the specific bug.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
Status was refactored and now it reflects the most important information about readiness of NG.
Example:
```yaml
status:
  conditionSummary:
    ready: "True"
    statusMessage: ""
  conditions:
  - lastTransitionTime: "2024-04-04T13:01:08Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-10-30T11:31:06Z"
    status: "False"
    type: Updating
  - lastTransitionTime: "2024-04-04T13:01:08Z"
    status: "False"
    type: WaitingForDisruptiveApproval
  - lastTransitionTime: "2024-04-04T13:01:08Z"
    status: "False"
    type: Error
  deckhouse:
    observed:
      checkSum: 46cb91d14388662125
```
