### ISSUE TITLE
PodLoggingConfig has wrong field definition spec.multilineParser.custom

### ISSUE THREAD

**Issue by HeyLazySunnyKid** [deckhouse/deckhouse#5516]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.49.3

### Expected Behavior

Pod logging created with custom multilineparser

### Actual Behavior

Validation error ( more info in logs )

### Steps To Reproduce

```
---
apiVersion: deckhouse.io/v1alpha1
kind: PodLoggingConfig
metadata:
  name: pod-logging-example
  namespace: example
spec:
  multilineParser:
    type: Custom
    custom:
      startsWhen:
        regex: '['
  clusterDestinationRefs:
    - kafka
```

### Additional Information

ClusterLoggingConfigs  (right defenition):
```
 oneOf:
                    - required:
                      - startsWhen
                    - required:
                      - endsWhen
```
PodLoggingConfigs (bad defenition):
```
oneOf:
                        - required:
                          - regex
                        - required:
                          - notRegex
```

### Logs

```shell
* <nil>: Invalid value: "": "spec.multilineParser.custom" must validate one and only one schema (oneOf). Found none valid
* spec.multilineParser.custom.regex: Required value
```
