### ISSUE TITLE
[user-authn] Allow using Base64 encoded password in the User CRD

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#5587]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Dex [allows](https://github.com/dexidp/dex/blob/a9d1fd31c329157efd388769f76cd2c6455bfc13/cmd/dex/config.go#L111-L126) using password encoded in Base64 (after it was bcrypt'ed).

Curent validation pattern in the User [spec.password](https://deckhouse.io/documentation/v1/modules/150-user-authn/cr.html#user-v1-spec-password) parameter don't allow using Base64.

### Proposed Solution

- Fix User OpenAPI spec for the [spec.password](https://deckhouse.io/documentation/v1/modules/150-user-authn/cr.html#user-v1-spec-password) parameter (validation pattern and description);
- Update documentation (examples, etc.);
- Update Getting Started.

**Comment by yalosev** [comment]
1. Remove [this](https://github.com/deckhouse/deckhouse/blob/main/modules/010-user-authn-crd/crds/user.yaml#L50) pattern
2. Fix [description](https://github.com/deckhouse/deckhouse/blob/main/modules/010-user-authn-crd/crds/user.yaml#L48)
3. Add test, create user like:
```yaml
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: tmp
spec:
  email: tmp@yourcompany.com
  password: YTAK # Base64 password
  userID: tmp
  ttl: 6h
```
4. Check, that user can login to grafana
