### ISSUE TITLE
[candi] classReference does not have required for kind and name

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#5604]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

I can create a nodegroup with ephemeral nodes, and so spec
```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: w
spec:
  cloudInstances:
    classReference:
      name: w
    maxPerZone: 0
    minPerZone: 0
  cri:
    type: Containerd
  nodeType: CloudEphemeral
```
in this case it will be created, but I will get it in the events 
Wrong classReference: Kind is not allowed, the only allowed kind is *InstanceClass.

### Proposed Solution

Add for crd node_group.yaml in classreferenae required for kind and name
