### ISSUE TITLE
[user-authz] subjects field in ClusterAuthorizationRule/AuthorizationRule is counterintuitive

### ISSUE THREAD

**Issue by asviel** [deckhouse/deckhouse#5621]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When an administrator creates a static user (`User`) and wants to grant privileges via ClusterAuthorizationRule/AuthorizationRule resources he uses following resources:

```
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: admin
spec:
  email: jane.doe@example.com
  password: $2a$10$etblbZ9yfZaKgbvysf1qguW3WULdMnxwWFrkoKpRH1yeWa5etjjAa
  userID: some-unique-user-id
  ttl: 24h
---
apiVersion: deckhouse.io/v1
kind: ClusterAuthorizationRule
metadata:
  name: jane
spec:
  subjects:
    - kind: User
      name: jane.doe@example.com
  accessLevel: User
  limitNamespaces:
  - review-.*
```

The fact that you **MUST** use the `User`'s email in the subjects section is counterintuitive. The existing structure assumes a binding to `kind` by its `name`. And the administrator, expecting this behavior (quite reasonably), tries to specify in the following way, which doesn't work:

```
subjects:
  - kind: User
    name: admin
```

The note in the documentation about the need to use email as a name doesn't help for the reasons described above.

### Proposed Solution

Use name of `User` resource instead of email
