### ISSUE TITLE
[prometheus] alertmanager in the HA mode

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5707]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If we set alertmanager in the HA mode, traffic to it will be balanced via the ingress
but according to the documentation, we have to push traffic into the each alertmanager instance
```
Important: Do not load balance traffic between Prometheus and its Alertmanagers, but instead point Prometheus to a list of all Alertmanagers. The Alertmanager implementation expects all alerts to be sent to all Alertmanagers to ensure high availability.
```

So we have to fix the HA mode

### Proposed Solution

Probably...

For each alertmanager instance create a Service:

```
CLUSTER-IP       EXTERNAL-IP   PORT(S)                        AGE
alertmanager-operated-0      ClusterIP   None             <none>        9093/TCP,9094/TCP,9094/UDP                      9m12s
alertmanager-operated-1      ClusterIP   None             <none>        9093/TCP                       9m1s
```

Create ingress with:

```
  rules:
  - host: grafana.myhost.com
    http:
      paths:
      - backend:
          service:
            name: alertmanager-operated-0
            port:
              name: https
        path: /alertmanager/webhook/replica-0(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: alertmanager-operated-1
            port:
              name: https
        path: /alertmanager/webhook/replica-1(/|$)(.*)
        pathType: ImplementationSpecific
```

and pass it to the Grafana  alerting (with CR) via the comma join: `https://grafana.myhost.com/alertmanager/webhook/replica-0,https://grafana.myhost.com/alertmanager/webhook/replica-1`
