### ISSUE TITLE
[module] Add dependency on other modules

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5774]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have to make dependencies between modules

### Proposed Solution

In the `module.yaml` add

```yaml
dependency:
  modules:
    - module1
    - module2
    - module3
```

or 

```yaml
dependency:
  modules:
    module1: >=1.25
    module2: ==1.33
    module3: > 0.0.0
```

We don't have module versions at the moment, but it could be useful in the future.

We will need to build dependency tree to prevent cycle dependencies.
Enable modules based on their dependencies
