### ISSUE TITLE
MetalLB IP is unavailable until the speakers are restarted

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#5816]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

fe:v1.50.6

### Expected Behavior

MetalLB IP is available after service creation.

### Actual Behavior

MetalLB IP is not available after service creation.

### Steps To Reproduce

* Selectel servers in 3 zones
* Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: tfprod-c-load-balancer
  namespace: d8-ingress-nginx
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.222.176.5
  clusterIPs:
  - 10.222.176.5
  externalTrafficPolicy: Local
  healthCheckNodePort: 32639
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31401
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30250
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: controller
    name: tfprod-c
  sessionAffinity: None
  type: LoadBalancer
```
* After the service was created, a public IP was assigned, but was not accessible from the Internet.
* Access appeared after restarting the MetalLB speaker pods in zone c.

### !!! If the problem happens again, please leave a comment on this issue. !!!

logs befor restart
```json
root@a-hv-1 ~ # kubectl -n d8-metallb logs -l app=speaker --tail 999999 | grep 1.2.3.4
{"IPAdvertisement":{},"caller":"layer2_controller.go:142","ips":["1.2.3.4"],"level":"warn","localIfs":[],"msg":"the specified interfaces used to announce LB IP don't exist","op":"SetBalancer","pool":"tfrontend-pool-c","protocol":"layer2","service":"d8-ingress-nginx/tfprod-c-load-balancer","ts":"2023-09-13T13:25:50Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T13:25:50Z"}
{"IPAdvertisement":{},"caller":"layer2_controller.go:142","ips":["1.2.3.4"],"level":"warn","localIfs":[],"msg":"the specified interfaces used to announce LB IP don't exist","op":"SetBalancer","pool":"tfrontend-pool-c","protocol":"layer2","service":"d8-ingress-nginx/tfprod-c-load-balancer","ts":"2023-09-13T13:25:50Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T13:25:50Z"}
{"IPAdvertisement":{},"caller":"layer2_controller.go:142","ips":["1.2.3.4"],"level":"warn","localIfs":[],"msg":"the specified interfaces used to announce LB IP don't exist","op":"SetBalancer","pool":"tfrontend-pool-c","protocol":"layer2","service":"d8-ingress-nginx/tfprod-c-load-balancer","ts":"2023-09-13T13:25:50Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T13:25:50Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T13:25:46Z"}
{"caller":"main.go:389","event":"serviceWithdrawn","ip":null,"ips":["1.2.3.4"],"level":"info","msg":"withdrawing service announcement","pool":"tfrontend-pool-c","protocol":"layer2","reason":"notOwner","ts":"2023-09-13T13:25:47Z"}
```

logs after restart
```json
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T14:50:55Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T14:50:55Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T14:50:55Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["1.2.3.4"],"level":"info","msg":"service has IP, announcing","pool":"tfrontend-pool-c","protocol":"layer2","ts":"2023-09-13T14:50:55Z"}
```

[more details in slack](https://flant.slack.com/archives/CML93AWG2/p1694618803792659?thread_ts=1694614176.869819&cid=CML93AWG2)
