### ISSUE TITLE
Descheduler: options from `removeDuplicates` are used for all strategies

### ISSUE THREAD

**Issue by Nitive** [deckhouse/deckhouse#5844]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.50.6

### Expected Behavior

It should be possible to modify `Descheduler` options according to documentation

### Actual Behavior

Parameters provided for strategy `removeDuplicates` are used instead of parameters for specific strategy

### Steps To Reproduce

1. Apply Descheduler policy
```
apiVersion: deckhouse.io/v1alpha1
kind: Descheduler
metadata:
  name: high-node-utilization
spec:
  deschedulerPolicy:
    strategies:
      highNodeUtilization:
        enabled: true
        nodeFit: true
```

2. ```kubectl get configmap -n d8-descheduler -o yaml -l module=descheduler | yq '.items[].data["policy.yaml"]'```
3. `nodeFit` param is not there
4. Update Descheduler policy
```
apiVersion: deckhouse.io/v1alpha1
kind: Descheduler
metadata:
  name: high-node-utilization
spec:
  deschedulerPolicy:
    strategies:
      removeDuplicates:
        enabled: false
        nodeFit: true
      highNodeUtilization:
        enabled: true
```
5. ```kubectl get configmap -n d8-descheduler -o yaml -l module=descheduler | yq '.items[].data["policy.yaml"]'```
6. `nodeFit` param is there

### Additional Information

It's bug in code. `removeDuplicates` params are used everywhere. https://github.com/deckhouse/deckhouse/blob/v1.49.3/modules/400-descheduler/templates/configmap.yaml#L58
![image](https://github.com/deckhouse/deckhouse/assets/6770225/34235b99-a312-4f07-a70f-da22154906ae)
