### ISSUE TITLE
[candi][cloud-provider-openstack] Instances of permanent nodes don't contain allowed_address_pairs in resource openstack_networking_port_v2

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#5963]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.51.6

### Expected Behavior

When we create permanent nodes for OpenStack with enabled option `DirectRoutingWithPortSecurityEnabled`, terraform resources for these instances have to contain resource `openstack_networking_port_v2` with block `allowed_address_pairs`

### Actual Behavior

Resources `openstack_networking_port_v2` don't contain block `allowed_address_pairs`. This disrupts network connectivity within the cluster. It works only for master nodes

### Steps To Reproduce

1. Create cluster in OpenStack cloud with permanent nodes with option
```
simpleWithInternalNetwork:
  externalNetworkName: ext-net-name
  internalSubnetName: net_internal
  masterWithExternalFloatingIP: false
  podNetworkMode: DirectRoutingWithPortSecurityEnabled
```

### Additional Information

Difference in creation.
For masters:
```
allowed_address_pairs {
    ip_address = local.pod_subnet_cidr
  }
```
For permanent nodes:
```
dynamic "allowed_address_pairs" {
    for_each = local.internal_network_security_enabled && local.networks[count.index] == local.prefix ? list(local.pod_subnet_cidr) : []

    content {
      ip_address = allowed_address_pairs.value
    }
  }
```
