### ISSUE TITLE
[log-shipper] add option to use TLS from secret

### ISSUE THREAD

**Issue by ishtarov** [deckhouse/deckhouse#6114]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When configuring a module, the section `log-shipper.spec.elasticsearch.tls.client.[crtFile/keyFile]` must by explicitly specified as base64. But they may contain certificates issued within the cluster cert-manager (and used by elasticsearch, configured to use those certs). If certificates change, additional configuration will be required.

### Proposed Solution

Make an option (maybe, in tls.[crtFile/keyFile] sections used in all configs) - "use certificate from secret", something like it used in following example:

```
        volumeMounts:
        - mountPath: /usr/share/opensearch/config/elk-key.pem
          name: opendistro-certs
          subPath: tls.key
          readOnly: true
        - mountPath: /usr/share/opensearch/config/elk-root-ca.pem
          name: opendistro-certs
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: opendistro-certs
        secret:
          defaultMode: 420
          secretName: opendistro-certs
```
