### ISSUE TITLE
Logos for deckhouse-admin

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#6206]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The ability to whitelabel Deckhouse web interfaces where Deckhouse logo is met

### Proposed Solution

It is necessary to parameterize

- Logo in Grafana
- Two pictures in the dex: logo and signature under the logo
- Deckhouse Admin logo (the logo should be assumed in this repo, while the end using part is outside of it)

**Comment by yalosev** [comment]
1. Add ConfigMap to the `d8-system` namespace:
```yaml
apiVersion: v1
data:
  grafanaLogo: |
    xxx
  dexLogo: |
    xxx
  dexTitle: |
    xxx
  deckhouseAdminLogo: |
    xxx
kind: ConfigMap
metadata:
  name: whitelabel-custom-logo
  namespace: d8-system
  labels:
    area: whitelabel
```
`xxx` - is a base64 encoded svg

2. Add hook to copy ConfigMap to the `d8-monitoring` and `d8-user-authn` namespaces
3. Mount ConfigMap key `grafanaLogo` to the grafana container
4. Mount ConfigMap key `dexXXXz to the dex container
