### ISSUE TITLE
[cloud-provider] Custom StorageClass can't be set as default through cloud-provider mc

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#6213]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.52.7

### Expected Behavior

Add a new custom storageClass and set it as default in `mc cloud-provider-[yandex|openstack]` `storageClass.default` and it becomes default SC with `storageclass.kubernetes.io/is-default-class: "true"` annotation set automatically
Should be managed automatically according to docs https://deckhouse.io/documentation/v1/modules/030-cloud-provider-yandex/configuration.html#parameters-storageclass-default

### Actual Behavior

After adding a custom storageClass, setting it as default in `mc cloud-provider-[yandex|openstack]` `storageClass.default` unsets the `storageclass.kubernetes.io/is-default-class: "true"` annotation on previous storageClass, but does not apply it on new custom storageClass. Results in absence of default storageClass in the cluster. 
There seems to be no issue in setting built-in storageClasses that were created by deckhouse as default.
Tested in clusters deployed to YC and Openstack

### Steps To Reproduce

1. Cluster deployed in YC or Openstack.
2. Add custom storageClass
3. Set `storageClass.default` in `mc cloud-provider-{cloud} `to new custom storageClass
4. Wait for all tasks in Deckhouse queues to pass
5. Annotation `storageclass.kubernetes.io/is-default-class: "true"` disappears from previously default storageClass. Not added to new custom storageClass
6. No default storageClass in cluster as a result.

### Additional Information

WORKAROUND: set annotation `storageclass.kubernetes.io/is-default-class: "true"` manually for a desired storageClass

Tested custom storageClass in Openstack:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
  name: ceph-ssd-new
parameters:
  type: ceph-ssd
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

Tested custom StrageClass in YC:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  name: gpu-sc
parameters:
  typeID: network-ssd
provisioner: yandex.csi.flant.com
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
