### ISSUE TITLE
[node-manager] Kubelet restart sometimes leads to cephfs mounts error

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#631]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.27

### Expected Behavior

Kubelet restart is absolutely safe operation. We want to be sure that patch update and even minor version kubelet updates can be done on production environments without disruptions.

### Actual Behavior

We received information from one of Deckhouse customers.
If there are mounts of cephfs that done like [this](https://github.com/kubernetes/examples/blob/master/volumes/cephfs/cephfs.yaml).
```
apiVersion: v1
kind: Pod
metadata:
  name: cephfs
spec:
  containers:
  - name: cephfs-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 10.16.154.78:6789
      - 10.16.154.82:6789
      - 10.16.154.83:6789
      # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
      # path: /some/path/in/side/cephfs
      user: admin
      secretFile: "/etc/ceph/admin.secret"
      readOnly: true
```
After kubelet restart we receive error on operations with mounted volume `Transport endpoint is not connected`. There is similar issue https://github.com/kubernetes/kubernetes/issues/77209 in Kubernetes.

### Steps To Reproduce

Collecting more information about ceph, OS, kernel and kubelet versions.
