### ISSUE TITLE
deleting values from d8-ingress-nginx.spec.additionalHeaders not removing references from configmaps custom-headers

### ISSUE THREAD

**Issue by ishtarov** [deckhouse/deckhouse#6588]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.53.3

### Expected Behavior

Removing records from d8-ingress-nginx.spec.additionalHeaders remove according records from configmaps

### Actual Behavior

customHeader not removed from configmaps

### Steps To Reproduce

1. Add customHeaders to ingressnginxcontroller:
`kubectl edit ingressnginxcontrollers.deckhouse.io -n d8-ingress-nginx main`
add 
```
spec:
  additionalHeaders:
    CF-Connecting-ip: $http_x_qrator_ip_source
    CF-IPCountry: $geoip2_country_code
```
2. check customheaders in configmaps:
`kubectl get configmaps -n d8-ingress-nginx main-custom-headers -oyaml`
```
apiVersion: v1
data:
  CF-Connecting-ip: $http_x_qrator_ip_source
  CF-IPCountry: $geoip2_country_code
```
3. remove customHeaders from ingresscontroller:
`kubectl edit ingressnginxcontrollers.deckhouse.io -n d8-ingress-nginx main`
```
spec:
  additionalHeaders:
    CF-Connecting-ip: $http_x_qrator_ip_source
```
4. check customheaders in configmaps
`kubectl get configmaps -n d8-ingress-nginx main-custom-headers -oyaml`
```
apiVersion: v1
data:
  CF-Connecting-ip: $http_x_qrator_ip_source
  CF-IPCountry: $geoip2_country_code
```
result - configmap not changed.

### Additional Information

adding new records to ingressnginxcontrollers or editing existing - correctly changing configmap
only deleting is broken
