### ISSUE TITLE
[prometheus] CronJobFailed alert is not firing

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#6669]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.54.5

### Expected Behavior

Version of kubernetes is 1.25.15. When a CronJob execution fails, we expect to see the _CronJobFailed_ alert in _Prometheus_.

### Actual Behavior

Version of kubernetes is 1.25.15. When a CronJob execution fails, there is not any _CronJobFailed_ alert in _Prometheus_.

### Steps To Reproduce

1. Install Deckhouse v1.54.5 with kubernetes 1.25.15
2. Create CronJob which will failed with
_kubectl apply -f_ 
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-fail-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fail-container
            image: busybox
            command: ["sh", "-c", "exit 1"] # always exit with non-zero code
          restartPolicy: Never
      backoffLimit: 2
```
3. Check alerts in cluster with
`kubectl get clusteralerts.deckhouse.io`
or in Prometheus' Alerts Tab
