### ISSUE TITLE
[multitenancy-manager] Remove namespaced resource prefix

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#6688]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.55.x

### Expected Behavior

Resource should be rendered without prefix
`foo` cm should like like:
```
# kubectl -n test-project get cm

NAME               DATA   AGE
foo                    0          6h54m
```

### Actual Behavior

At the moment all namespaced resources have prefix.
For example, cm `foo` will be rendered as `test-project-foo`
```
# kubectl -n test-project get cm

NAME               DATA   AGE
test-project-foo   0      6h54m
```

### Steps To Reproduce

1. Create ProjectTemplate with resources like deployment, configmap, secret, etc
2. Create Project
3. Lookup for resources names

### Additional Information

This is really weird. Imagine, that we have some pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: TEST_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-username
              key: username
```

and cm

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-username
data:
  username: foobar
```

And you want to create multiply projects for your developers with already prepared db connector.

At the moment, you are unable to do that, because you will have configmaps:
- project-1-db-username
- project-2-db-username
- project-3-db-username

And you have to parametrize it somehow in the Pod spec.
Also, it really looks weird, why we have to set prefix for incapsulated namespaced resources

**NOTE**
It will be a BREAKING CHANGE
