### ISSUE TITLE
[monitoring] Changing the configuration of prometheus resources

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#6805]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Add prometheus configuration
prometheuses.monitoring.coreos.com
```
    resources:
      ``` limits:
        cpu: "6"
        memory: 24Gi
      requests:
        cpu: "6"
        memory: 24Gi
```
the resources of prometheus itself are changed
and then we already have a vpa configuration for these resources.
```
    vpa:
      longtermMaxCPU: 6
      longtermMaxMemory: 24Gi
      maxCPU: 6
      maxMemory: 24Gi
      updateMode: Auto
```
these parameters allowed the service to survive and operate without the increasing the size of VM resources
### Proposed Solution

Adding the prometheus resource configuration in the prometheus module
