### ISSUE TITLE
[VPA] vpa recomender vpa updater

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#6806]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is no way to configure vpa-updater and vpa-recomender in deckhouse
There are cases where it is needed.

vpa updater - parameters are needed for vpa to work properly, so that it is not blocked by services with one replica, does not kill many pods of the service at the same time 
```
      containers:
      - args:
        - --address=:9090 --- diff address=:8943
        - --eviction-rate-limit=1 --- same
        - --eviction-tolerance=0.1. --- same 
        - --in-recommendation-bounds-eviction-lifetime-threshold=0h30m0s
        - --min-replicas=0
        - --stderrthreshold=0
        - --updater-interval=600s
```
`in-recommendation-bounds-eviction-lifetime-threshold` added [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L208)
`min-replicas`  changed for updater default 2 min replicas [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L211)
`updater-interval` changed, deckhouse default 30 sec [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L210)

vpa recomender - These parameters allowed the Prometheus service to survive and run without the increase in CPU and Memory in the virtual machine recommended by Flant.
```
    spec:
      containers:
      - args:
        - --address=:9090 --- diff address=:9090
        - --cpu-histogram-decay-half-life=20m --- added var
        - --history-length=120m --- added var
        - --history-resolution=5m --- added var 
        - --kube-api-burst=100 --- same
        - --kube-api-qps=50 --- same 
        - --memory-aggregation-interval=60m --- added var 
        - --memory-histogram-decay-half-life=20m --- added var 
        - --pod-recommendation-min-cpu-millicores=25 --- same
        - --pod-recommendation-min-memory-mb=50 --- same
        - --recommendation-margin-fraction=0.5 --- added var 
        - --recommender-interval=5m --- changed 
```
`cpu-histogram-decay-half-life=20m` The amount of time it takes a historical CPU usage sample to lose half of its weight [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L198)
`history-length` default 8d [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L184)
`history-resolutionz` default 1h [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L185)
`memory-aggregation-interval` The length of a single interval, for which the peak memory usage is computed [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L195)
`memory-histogram-decay-half-life` The amount of time it takes a historical memory usage sample to lose half of its weight [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L197)
`recommendation-margin-fraction` default 0.15sec [var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L169)
`recommender-interval` in client case changed for 5m, deckhouse use 30 seconds.[var](https://github.com/kubernetes/autoscaler/blob/b4586f9b4468f595ac81632d55a1eda4a415dc99/vertical-pod-autoscaler/FAQ.md?plain=1#L175)
### Proposed Solution

Perhaps consider adding configurations for vpa-recomender and vpa-updater to the vpa module
