### ISSUE TITLE
[node-manager] Reference StaticInstance in Node

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#6841]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

From StaticInstance, one has a reference to a Node bootstrapped on it (StaticInstance has `status.nodeRef` field). But one cannot find out the reference back, from a Node to its StaticInstance. 

### Proposed Solution

To the Node object, add an annotation referring to StaticInstance name. For example,

```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    cluster.x-k8s.io/cluster-name: static
    cluster.x-k8s.io/cluster-namespace: d8-cloud-instance-manager
    cluster.x-k8s.io/labels-from-machine: ""
    cluster.x-k8s.io/machine: worker-wqh9f-4r8gr
    cluster.x-k8s.io/owner-kind: MachineSet
    cluster.x-k8s.io/owner-name: worker-wqh9f
    # ↓↓↓↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓  THIS ONE ↓↓↓↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓ 
    # ↓↓↓↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓  THIS ONE ↓↓↓↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓ ↓↓↓ 
    node.deckhouse.io/static-instance: some-static-instance-name-static-worker-2  
  creationTimestamp: "2023-12-12T07:02:01Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: static-worker-2
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.deckhouse.io/group: worker
    node.deckhouse.io/type: Static
  name: static-worker-2
```
