### ISSUE TITLE
[openstack] Bastion rootDiskSize is required

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#6867]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.55

### Expected Behavior

`rootDiskSize` for bastion is said to be optional in docs https://deckhouse.io/documentation/v1.55/modules/030-cloud-provider-openstack/layouts.html

### Actual Behavior

Using disked flavor and omitting rootDiskSize parameter for bastion result in error:
```
Error: Incorrect attribute value type

  on deckhouse/candi/cloud-providers/openstack/layouts/standard/base-infrastructure/main.tf line 93, in resource                           ↵
"openstack_blockstorage_volume_v3" "root":
  93:   size        = local.root_disk_size
    |----------------
    | local.root_disk_size is ""

Inappropriate value for attribute "size": a number is required.
```

### Steps To Reproduce

1. Prepare config.yml for cluster setup, set bastion with disked flavor and omit rootDiskSize parameter
2. Start bootstrapping with said config
3. Bootstrap fails with error

### Additional Information

setup config that produces the error:

```
apiVersion: deckhouse.io/v1
kind: OpenStackClusterConfiguration
layout: Standard
standard:
  bastion:
    zone: ru-7a                                
    volumeType: fast.ru-7a                     
    instanceClass:
      flavorName: c2m2-d20                
      imageName: ubuntu-22-04   
...
```   

Could be worked around by using diskless flavor and setting the `rootDiskSize` parameter
