### ISSUE TITLE
[runtime-audit-engine] Conditions in some rules will never be true

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#6961]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.55.3

### Expected Behavior

1. Enable module `runtime-audit-engine`
2. Create SA with 
```
kubectl  -n kube-public  create sa bro4 
serviceaccount/bro4 created
```
3. There should be events from falco with `Service account created in kube namespace...`

### Actual Behavior

1. Enable module `runtime-audit-engine`
2. Create SA with 
```
kubectl  -n kube-public  create sa bro4
serviceaccount/bro4 created
```
3. There aren't any event from falco with `Service account created in kube namespace...`

### Additional Information

In Falco rule:
   ```yaml
 - rule:
        name: ServiceAccount created in a system namespace
        condition: |
          kevt and serviceaccount and kcreate and system_namespace and response_successful and not trusted_sa
        desc: Detect any attempt to create a serviceaccount in the kube-system or kube-public namespaces
        output: Service account created in kube namespace (user=%ka.user.name serviceaccount=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace)
        priority: Warning
        tags:
          - fstec
          - rbac_drift
        source: K8sAudit
```
part of condition `not trusted_sa` will never be true because
```yaml
- macro:
    name: trusted_sa
    condition: (always_true)
```
