### ISSUE TITLE
[deckhouse-controller] ModuleConfig validation without settings with required params

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#6973]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.0

### Expected Behavior

ModuleConfig should not be created

### Actual Behavior

Deckhouse creates ModuleConfig, fail with hook execution and after restart got fatal error

### Steps To Reproduce

1. Create ModuleConfig
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: network-gateway
spec:
  enabled: true
```
2. Restart deckhouse
3. Enjoy fatal error

### Additional Information

Problem, that some parameter are [required](https://github.com/deckhouse/deckhouse/blob/main/ee/modules/450-network-gateway/openapi/config-values.yaml#L2)
But deckhouse dont validate them
