### ISSUE TITLE
addon-operator: config values for dynamic enabled modules (via global hooks)

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#7034]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.X

### Expected Behavior

Module config should be loaded

### Actual Behavior

Module config is not loaded for module which is enabled by global hook

### Steps To Reproduce

1. Create MC
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cloud-provider-openstack
spec:
  settings:
    storageClass:
      default: foobar
  version: 1
```

2. Wait for it:
```
$ kubectl get mc cloud-provider-openstack
NAME                       STATE     VERSION   AGE    TYPE   STATUS
cloud-provider-openstack   Enabled   1         3m9s          Ready
```
module is enabled by global hook

3. But module config is not loaded:
```
$ deckhouse-controller module config cloud-provider-openstack
{}
```

### Additional Information

Problem in addon-operator, somewhere in module loading
