### ISSUE TITLE
[dhctl] Unexpected preflight checks about proxy and registry

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#7045]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.55.7

### Expected Behavior

dhctl install skip preflight check about registry-through-proxy because address of registry exists in no_proxy subnet

### Actual Behavior

dhctl fails with
```
│ ┌ Checking registry access through proxy
│ │ ️:umbrella_on_ground:️ Attempt #1 of 1 |
│ │     Checking registry access through proxy failed, next attempt will be in 10s"
│ │     Error: Could not reach registry over proxy: got 500 status code from the container registry API, this is not a valid registry API     ↵
│ │ response.
│ │ Check if container registry address is correct and if there is any reverse proxies that might be misconfigured.
│ │
│ └ Checking registry access through proxy (0.39 seconds) FAILED
└ :balloon: ~ Common: Preflight checks for static-cluster (1.11 seconds) FAILED

Installation aborted: timeout while "Checking registry access through proxy": last error: Could not reach registry over proxy: got 500     ↵
status code from the container registry API, this is not a valid registry API response.
Check if container registry address is correct and if there is any reverse proxies that might be misconfigured.
Please fix this problem or skip it if you're sure with preflight-skip-registry-through-proxy flag
```

### Steps To Reproduce

Run setup with this config
```
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Static
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: "Automatic"
clusterDomain: "cluster.local"
proxy:
  httpProxy: http://proxyuser:proxypassword@192.168.199.236:8888
  httpsProxy: http://proxyuser:proxypassword@192.168.199.236:8888
  noProxy: ["127.0.0.1", "192.168.199.0/24"]
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: 192.168.199.129/d8/deckhouse/ee
  registryDockerCfg: eyJhdXRocyI6eyIxOTIuMTY4LjE5OS4xMjkiOnsiYXV0aCI6ImEyOTJZV3hyYjNZNldHVnBiamxoWm1VPSJ9fX0K
  registryScheme: HTTP
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    bundle: Default
    releaseChannel: Stable
    logLevel: Info
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  version: 1
  settings:
    modules:
      publicDomainTemplate: "%s.domain.my"
      https:
        certManager:
          clusterIssuerName: selfsigned
    storageClass: localpath-deckhouse-system
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: user-authn
spec:
  version: 1
  enabled: true
  settings:
    controlPlaneConfigurator:
      dexCAMode: FromIngressSecret
    publishAPI:
      enable: true
      https:
        mode: Global
        global:
          kubeconfigGeneratorMasterCA: ""
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cert-manager
spec:
  version: 1
  enabled: true
  settings:
    disableLetsencrypt: true
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cni-flannel
spec:
  version: 1
  enabled: true
  settings:
    podNetworkMode: VXLAN
---
apiVersion: deckhouse.io/v1
kind: StaticClusterConfiguration
internalNetworkCIDRs:
- 192.168.199.0/24
```

### Additional Information

If set `noProxy` with exactly IP of registry dhctl works as expected
`noProxy: ["127.0.0.1", "192.168.199.0/24", "192.168.199.129"]`
