### ISSUE TITLE
[candi] If imagesRepo set with protocol installation failed

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#7046]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.55.7

### Expected Behavior

Do not pass imagesRepo with URL schema

### Actual Behavior

Value like `imagesRepo: http://192.168.199.129/d8/deckhouse/ee` accepted and install fails with strange errors like
```
│ │ bb-rp [INFO] 'jq:sha256:3c27dae8f3124bd65635cd3793ff1e9c83e98207d4025a092bebd778a7aac1bb' package not found locally
│ │ bb-rp [INFO] Fetching manifests: jq
│ │ bb-exit [ERROR] couldn't find bearer realm parameter, consider enabling bearer token auth in your registry, returned header:
│ │ Failed to execute step /var/lib/bashible/bundle_steps/003_install_mandatory_packages.sh ... retry in 10 seconds.
│ └ Run step 003_install_mandatory_packages.sh (41.01 seconds) FAILED
```

because it parsed to
```
┌ ⛵ ~ Bootstrap: Prepare Bashible Bundle
│ ┌ kubeadm data
│ │ bashible: <hidden>
│ │ clusterConfiguration:
│ │   apiVersion: deckhouse.io/v1
│ │   clusterDomain: cluster.local
│ │   clusterType: Static
│ │   defaultCRI: Containerd
│ │   kind: ClusterConfiguration
│ │   kubernetesVersion: "1.25"
│ │   podSubnetCIDR: 10.111.0.0/16
│ │   podSubnetNodeCIDRPrefix: "24"
│ │   proxy:
│ │     httpProxy: http://proxyuser:proxypassword@192.168.199.236:8888
│ │     httpsProxy: http://proxyuser:proxypassword@192.168.199.236:8888
│ │   serviceSubnetCIDR: 10.222.0.0/16
│ │ extraArgs: {}
│ │ images: <hidden>
│ │ k8s: <hidden>
│ │ nodeIP: $MY_IP
│ │ registry:
│ │   address: 'http:'
│ │   auth: ""
│ │   ca: ""
│ │   dockerCfg: eyJhdXRocyI6eyIxOTIuMTY4LjE5OS4xMjkiOnsiYXV0aCI6ImEyOTJZV3hyYjNZNldHVnBiamxoWm1VPSJ9fX0K
│ │   path: //192.168.199.129/d8/deckhouse/ee
│ │   scheme: http
│ │ runType: ClusterBootstrap
│ └ kubeadm data (0.00 seconds)
```

More verbose step 003_install_mandatory_packages.sh looks like
```
│ │ +++ echo -e bb-rp '[INFO]' Fetching manifests: jq
│ │ bb-rp [INFO] Fetching manifests: jq
│ │ ++ bb-rp-fetch-manifests PACKAGES_MAP
│ │ ++ local TOKEN=
│ │ +++ bb-rp-get-token
│ │ +++ local AUTH=
│ │ +++ local AUTH_HEADER=
│ │ +++ local AUTH_REALM=
│ │ +++ local AUTH_SERVICE=
│ │ +++ [[ -n '' ]]
│ │ ++++ bb-rp-curl --retry 3 -sSLi http://http:/v2/
│ │ ++++ command -v d8-curl
│ │ ++++ grep -i www-authenticate
│ │ ++++ curl --retry 3 -sSLi http://http:/v2/
│ │ +++ AUTH_HEADER=
│ │ ++++ grep -oE 'Bearer realm="http[s]{0,1}://[a-z0-9\.\:\/\-]+"'
│ │ ++++ cut -d '"' -f2
│ │ +++ AUTH_REALM=
│ │ ++++ cut -d '"' -f2
│ │ ++++ sed 's/ /+/g'
│ │ ++++ grep -oE 'service="[[:print:]]+"'
│ │ +++ AUTH_SERVICE=
│ │ +++ '[' -z ']'
│ │ +++ bb-exit 1 'couldn'\''t find bearer realm parameter, consider enabling bearer token auth in your registry, returned header: '
│ │ +++ local CODE=1
│ │ +++ local 'MSG=couldn'\''t find bearer realm parameter, consider enabling bearer token auth in your registry, returned header: '
```

### Steps To Reproduce

Run setup with config
```
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Static
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: "Automatic"
clusterDomain: "cluster.local"
proxy:
  httpProxy: http://proxyuser:proxypassword@192.168.199.236:8888
  httpsProxy: http://proxyuser:proxypassword@192.168.199.236:8888
  noProxy: ["127.0.0.1", "192.168.199.0/24", "192.168.199.129"]
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: http://192.168.199.129/d8/deckhouse/ee
  registryDockerCfg: eyJhdXRocyI6eyIxOTIuMTY4LjE5OS4xMjkiOnsiYXV0aCI6ImEyOTJZV3hyYjNZNldHVnBiamxoWm1VPSJ9fX0K
  registryScheme: HTTP
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    bundle: Default
    releaseChannel: Stable
    logLevel: Info
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  version: 1
  settings:
    modules:
      publicDomainTemplate: "%s.domain.my"
      https:
        certManager:
          clusterIssuerName: selfsigned
    storageClass: localpath-deckhouse-system
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: user-authn
spec:
  version: 1
  enabled: true
  settings:
    controlPlaneConfigurator:
      dexCAMode: FromIngressSecret
    publishAPI:
      enable: true
      https:
        mode: Global
        global:
          kubeconfigGeneratorMasterCA: ""
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cert-manager
spec:
  version: 1
  enabled: true
  settings:
    disableLetsencrypt: true
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cni-flannel
spec:
  version: 1
  enabled: true
  settings:
    podNetworkMode: VXLAN
---
apiVersion: deckhouse.io/v1
kind: StaticClusterConfiguration
internalNetworkCIDRs:
- 192.168.199.0/24
```

### Additional Information

Looks like we need add validation for `imagesRepo`

Possible fix is
```
diff --git a/candi/openapi/init_configuration.yaml b/candi/openapi/init_configuration.yaml
index adace785a..0b5e879c1 100644
--- a/candi/openapi/init_configuration.yaml
+++ b/candi/openapi/init_configuration.yaml
@@ -40,6 +40,7 @@ apiVersions:
         properties:
           imagesRepo:
             type: string
+            pattern: '^[0-9a-zA-Z\.\-\/]+$'
             description: |
               Address of a container registry with Deckhouse images.
```

Also, maybe as variant, we can trim http://|https:// (but do not pass looks better for me)
