### ISSUE TITLE
Deckhouse installation does not have 'deployed' deckhouse release, only 'pending' one 

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#7133]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56

### Expected Behavior

A 'Deployed' deckhouse release (`deckhouserelease` resource) should be created on finished installation. 

### Actual Behavior

Only 'Pending' deckhouse release is created whereas deckhouse Pod is up and running

### Steps To Reproduce

IDK exact steps. Deckhouse update settings were applied to default values (not set). After ~2hr I noticed the 'update' was actually applied, and the release became 'Deployed'. 

### Additional Information

During installation, current configuration was applied. ModuleConfig/deckhouse was not specified.

```
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: registry.deckhouse.io/deckhouse/ee
  registryDockerCfg: eyJhd.....
  releaseChannel: EarlyAccess
```
