### ISSUE TITLE
[cloud-provider-aws] Hook doesn't match nodes from NG with more than one taints with same key:effect

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#7142]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.5

### Expected Behavior

1. In cluster with AWS cloud provider create NodeGroup with 
```
nodeTemplate:
    ...
    taints:
    - effect: NoExecute
      key: dedicated
      value: production
    - effect: NoExecute
      key: dedicated
      value: static
```
2. Nodes in NG become ready and CSI will deployed on them

### Actual Behavior

Nodes stay without CSI. They contain taints:
```
 node.deckhouse.io/csi-not-bootstrapped:NoSchedule
 node.deckhouse.io/uninitialized:NoSchedule
```

### Additional Information

// MatchTaint checks if the taint matches taintToMatch. Taints are unique by key:effect,
// if the two taints have same key:effect, regard as they match.
