### ISSUE TITLE
Missing SMTP smarthost in generated configuration for custom alert manager

### ISSUE THREAD

**Issue by kevrat** [deckhouse/deckhouse#7455]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.57.3 CE

### Expected Behavior

Aletmanager contains the specified smtp smarthost in the generated config.

### Actual Behavior

There is an error in `alertmanager` container of `alertmanager` pod when using SMTP receiver:

> caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="no global SMTP smarthost set"

### Steps To Reproduce

Using this config:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: smtp
spec:
  internal:
    receivers:
      - emailConfigs:
          - authPassword:
              key: password
              name: smtp-secret
            authUsername: sender
            from: sender@example.com
            smarthost: mail.example.com
            to: receiver@example.com
        name: smtp
    route:
      groupBy:
        - job
      groupInterval: 5m
      groupWait: 30s
      receiver: smtp
      repeatInterval: 12h
  type: Internal
```

You get this generated config:
```yaml
route:
  receiver: d8-monitoring/smtp/smtp
  group_by:
  - job
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: d8-monitoring/smtp/smtp
  email_configs:
  - to: receiver@example.com
    from: sender@example.com
    auth_username: sender
    auth_password: ***
templates: []
```

The generated config itself can be viewed with:
```bash 
kubectl -n d8-monitoring get secret alertmanager-smtp-generated -o json | jq -r '.data."alertmanager.yaml.gz"' | base64 -d | gunzip
```

It's missing smarthost details as stated in the error message.
