### ISSUE TITLE
TLS config for CustomAlertmanager is not being created

### ISSUE THREAD

**Issue by kevrat** [deckhouse/deckhouse#7475]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.57.3 CE

### Expected Behavior

When you specify `emailConfigs.tlsConfig` in `CustomAlertmanager`, the specified configmap/secret must be mounted in the alertmanager pod

### Actual Behavior

The configmap/secret with the tls config is not mounted or is empty.

There is an error in logs:
`ts=2024-02-13T06:32:09.300Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="d8-monitoring/smtp/smtp/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: parse TLS configuration: unable to load specified CA cert /etc/alertmanager/certs/configmap_d8-monitoring_smtp-ca.crt_ca.crt: open /etc/alertmanager/certs/configmap_d8-monitoring_smtp-ca.crt_ca.crt: no such file or directory"
`

I found that it's mounted from the `tls-assets` volume:
```yaml
      volumeMounts:
        - name: tls-assets
          readOnly: true
          mountPath: /etc/alertmanager/certs
```
which it gets from the `alertmanager-smtp-tls-assets-0` secret:
```yaml
  volumes:    
    - name: tls-assets
      projected:
        sources:
          - secret:
              name: alertmanager-smtp-tls-assets-0
        defaultMode: 420
```

But the `alertmanager-smtp-tls-assets-0` secret is empty (`data:{}`).

The generated config for the Alert Manager looks fine:
```yaml
route:
  receiver: d8-monitoring/smtp/smtp
  group_by:
  - job
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: d8-monitoring/smtp/smtp
  email_configs:
  - to: receiver@example.com
    from: sender@example.com
    auth_username: sender
    auth_password: ***
    tls_config:
      ca_file: /etc/alertmanager/certs/configmap_d8-monitoring_smtp-ca.crt_ca.crt
      insecure_skip_verify: false
templates: []

```

### Steps To Reproduce

1. Create ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-ca.crt
  namespace: d8-monitoring
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIG0zCCBbugAwIBAgIME49AFm7rr4SKZiJnMA0GCSqGSIb3DQEBCwUAMFAxCzAJ
    ...
    -----END CERTIFICATE-----
binaryData: {}

```
2. Create CustomAlertmanager:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: smtp
spec:
  internal:
    receivers:
      - emailConfigs:
          - authPassword:
              key: password
              name: smtp-secret
            authUsername: sender
            from: sender@example.com
            smarthost: mail.example.com
            to: receiver@example.com
            tlsConfig:
              ca: 
                configMap:
                  name: 'smtp-ca.crt'
                  key: 'ca.crt'
        name: smtp
    route:
      groupBy:
        - job
      groupInterval: 5m
      groupWait: 30s
      receiver: smtp
      repeatInterval: 12h
  type: Internal
```

### Additional Information

I've tried both `emailConfigs.tlsConfig.ca.configMap`/`secret`, tried encoding it with `base64`, using `data`/`binaryData`, but no luck.
Also tried specifying `emailConfigs.tlsConfig.cert`/`keySecret` - same behaviour.
