### ISSUE TITLE
[user-authn] kubeconfig-generator does not use port from IngressNginxController

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#7604]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.57.5

### Expected Behavior

If we move `publishAPI.ingressClass` to ingress class with different port (something like `HostPort` with `7443` port) `kubeconfig-generator` must to generate kubeconfig with port
```
kubectl config set-cluster api.kube.kovalkoff.ru \
    --certificate-authority=${HOME}/.kube/certs/api.kube.kovalkoff.ru/k8s-ca.crt \
    --server=https://api.kube.kovalkoff.ru:7443
```

### Actual Behavior

It does not respect port
```
kubectl config set-cluster api.kube.kovalkoff.ru \
    --certificate-authority=${HOME}/.kube/certs/api.kube.kovalkoff.ru/k8s-ca.crt \
    --server=https://api.kube.kovalkoff.ru
```

### Steps To Reproduce

1. Add `IngressNginxController`
```
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: host-port
spec:
  ingressClass: host-port
  inlet: HostPort
  hostPort:
    httpsPort: 7443
  nodeSelector:
    node.deckhouse.io/group: master
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
```
2. Setting it in `user-authn` mc
```
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: user-authn
spec:
  version: 1
  enabled: true
  settings:
    publishAPI:
      enable: false
      ingressClass: host-port
```
3. Go to kubeconfig-generator and get kubeconfig
