### ISSUE TITLE
[ingress-nginx] fails to remove the httpsPort field for hostPort

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#7657]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.57.5

### Expected Behavior

The validator must allow this action

### Actual Behavior

I cannot remove the httpsPort field for hostPort, but the documentation says that it can be done. 

### Steps To Reproduce

1. kube add
```
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: test
spec:
  inlet: HostPort
  hostPort:
    httpPort: 80
    httpsPort: 443
    realIPHeader: X-Forwarded-For
  ingressClass: nginx
```
2. `k edit IngressNginxController test` and remove  line httpsPort

### Additional Information

https://github.com/deckhouse/deckhouse/blob/7f414414b8d4199a5963753519742441814657b3/modules/402-ingress-nginx/crds/ingress-nginx.yaml#L206C6-L208C53

### Logs

```shell
# ingressnginxcontrollers.deckhouse.io "nginx" was not valid:
# * spec.hostPort: Invalid value: "object": no such key: httpsPort evaluating rule: .spec.httpsPort can't be 6443, it's reserved for kube-apiserver
```
