### ISSUE TITLE
[helm_lib] make helm_lib_module_pod_security_context_run_as_user_deckhouse compatible with the restricted mode in the admission-policy-engine module.

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#7680]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We use helm_lib_module_pod_security_context_run_as_user_deckhouse in some containers, but now it's look like
```
{{- /* Template context with .Values, .Chart, etc */ -}}
securityContext:
  runAsNonRoot: true
  runAsUser: 64535
  runAsGroup: 64535
```
and don't pass check by admission-policy-engine in baseline or restricted mode

### Proposed Solution

Template 
```
{{- /* Template context with .Values, .Chart, etc */ -}}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - all
  runAsNonRoot: true
  runAsUser: 64535
  runAsGroup: 64535
  seccompProfile:
    type: RuntimeDefault
```
works fine

### Additional Information

We define `module_pod_security_context_run_as_user_deckhouse` and `module_init_container_check_linux_kernel` for workaround in `modules/110-istio/templates/control-plane/iop.yaml`
