### ISSUE TITLE
[node-manager] Wrong UpToDate status calculations for Static NG

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#769]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.29

### Expected Behavior

After creating NodeGroup there should be zero UpToDate nodes in status.

### Actual Behavior

After creating Static NodeGroup there is non-zero value in UpToDate field:
```
# kubectl get ng
NAME           TYPE     READY   NODES   UPTODATE   INSTANCES   DESIRED   MIN   MAX   STANDBY   STATUS   AGE
...
stateful       Static   0       0       1                                                               9s
...
```

### Steps To Reproduce

Create NodeGroup:
```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: stateful
spec:
  chaos:
    mode: Disabled
  disruptions:
    approvalMode: Manual
  nodeTemplate:
    annotations:
      node.deckhouse.io/nodeport-bind-internal-ip: "false"
    labels:
      node-role/stateful: ""
    taints:
    - effect: NoExecute
      key: dedicated
      value: stateful
  nodeType: Static
```

And watch ng statuses:
```
kubectl get ng
```
