### ISSUE TITLE
[ingress-nginx] Show IP in controller status

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#7718]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

-

### Proposed Solution

1. Add status field for [IngressNginxController CRD](https://github.com/deckhouse/deckhouse/blob/main/modules/402-ingress-nginx/crds/ingress-nginx.yaml)
Something like:
```yaml
status:  
  loadBalancer:
    address: 1.2.3.4
    id: lb-abracadabra012355.aws.whatever.here
```
2. Add it to the AdditionalPrinterColumns
3. Create a hook, subscribe to a service for LB
4. Fetch an IP and pass it to the CRD Status

### Additional Information

Only for inlets `LoadBalancer` and `LoadBalancerWithProxyProtocol`
