### ISSUE TITLE
[okmeter] Tolerations from ModuleConfig doesn't apply to daemonSet

### ISSUE THREAD

**Issue by cds111** [deckhouse/deckhouse#7886]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.57.5

### Expected Behavior

All tolerations for example from ModuleConfig:
```  
     tolerations:
    - key: dedicated
      value: dev-sts
    - key: dedicated
      value: testdb
```
apllied in daemonSet

### Actual Behavior

In reality daemonSet looks like this:
```
tolerations:
      - key: node-role.kubernetes.io/master
      - key: node-role.kubernetes.io/control-plane
      - key: dedicated.deckhouse.io
        operator: Exists
      - key: dedicated
        operator: Exists
      - key: DeletionCandidateOfClusterAutoscaler
      - key: ToBeDeletedByClusterAutoscaler
      - key: dedicated.sweedpos.com
        operator: Exists
      - key: drbd.linbit.com/lost-quorum
      - key: drbd.linbit.com/force-io-error
      - key: drbd.linbit.com/ignore-fail-over
```
