### ISSUE TITLE
[deckhouse] changing ModuleSource credentials doesn't affect modules

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#8053]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.59.X

### Expected Behavior

Module must be reloaded with a new credentials

### Actual Behavior

Nothing happens

### Steps To Reproduce

1. CreateModuleSource and pull the module

2. Change ModuleSource with a wrong credentials:
```yaml
apiVersion: deckhouse.io/v1alpha1
kind: ModuleSource
metadata:
  name: deckhouse-test
spec:
  registry:
    dockerCfg: ${CREDS}
    repo: registry.deckhouse.io/deckhouse/fe/modulez # some misspell here
    scheme: HTTPS
```

3. Change values for the existing module:
```bash
# cat /var/lib/deckhouse/external-modules/modules/900-deckhouse-admin/openapi/values.yaml  | grep registry
        default: registry.deckhouse.io/deckhouse/fe/modulez
```

4. Restart deckhouse
Module will be in the broken state:
```yaml
# kubectl -n d8-system get pods
NAME                                               READY   STATUS             RESTARTS        AGE
admin-backend-857cff578d-4fwm8                     0/1     ImagePullBackOff   0               18m
admin-frontend-6d66bb8c55-pv8n6                    0/1     ImagePullBackOff   0               18m
admin-grafana-76d79989d8-shnvk                     0/2     ImagePullBackOff   0               18m
```

5. Change ModuleSource with the valid credentials
```yaml
...
  registry:
    repo: registry.deckhouse.io/deckhouse/fe/modules
    scheme: HTTPS
```

6. Nothing happens
7. Restart Deckhouse
8. Still nothing happens:
```yaml
# kubectl -n d8-system exec -it deployment/deckhouse -- deckhouse-controller queue list
Defaulted container "deckhouse" out of: deckhouse, kube-rbac-proxy, init-external-modules (init)
Summary:
- 'main' queue: empty.
- 85 other queues (0 active, 85 empty): 0 tasks.
- no tasks to handle.

# kubectl get ms deckhouse-test -o yaml
spec:
  registry:
    repo: registry.deckhouse.io/deckhouse/fe/modules
    scheme: HTTPS
status:
  message: ""
  moduleErrors: []
  modules:
  - name: deckhouse-admin
    policy: deckhouse-test

cat /var/lib/deckhouse/external-modules/modules/900-deckhouse-admin/openapi/values.yaml  | grep registry
  registry:
        default: registry.deckhouse.io/deckhouse/fe/modulez

# kubectl -n d8-system get pods
NAME                                               READY   STATUS             RESTARTS        AGE
admin-backend-857cff578d-4fwm8                     0/1     ImagePullBackOff   0               18m
admin-frontend-6d66bb8c55-pv8n6                    0/1     ImagePullBackOff   0               18m
admin-grafana-76d79989d8-shnvk                     0/2     ImagePullBackOff   0               18m
```

### Additional Information

Linked with https://github.com/deckhouse/deckhouse/pull/7096
