### ISSUE TITLE
[prometheus] Provide ability to set disk size for Prometheus

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#8213]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The main goal is to be able to set an arbitrary size for Prometheus disks, including when bootstrapping a cluster
In some cases (including small clusters) we do not need such big disks

Now our disks are created with a default value of 40GiB and to reduce them, you need to do a lot of manual squats, disable mc prometheus and precreate PVC or scale operator and prometheus sts pods

Example of steps:
Scale to zero
```
kubectl -n d8-operator-prometheus scale deployment prometheus-operator --replicas 0
kubectl -n d8-monitoring scale statefulset prometheus-main --replicas 0
```
Delete PVC
```
kubectl -n d8-monitoring delete pvc prometheus-main-db-prometheus-main-0
```
Create PVC with needed size
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    prometheus: main
  name: prometheus-main-db-prometheus-main-0
  namespace: d8-monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: network-ssd
  volumeMode: Filesystem
```
Scale up
```
kubectl -n d8-monitoring scale statefulset prometheus-main --replicas 2
kubectl -n d8-operator-prometheus scale deployment prometheus-operator --replicas 1
```
Bruh, too much manual work

### Proposed Solution

Add parameter to MC that we can use to bootstrap cluster with needed disk size for prometheus
