### ISSUE TITLE
machine-controller-manager panic after deleting node groups

### ISSUE THREAD

**Issue by borg-z** [deckhouse/deckhouse#8240]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.10

### Expected Behavior

machine-controller-manager pod works as usual.

### Actual Behavior

When deleting several NodeGroup (YandexInstanceClass) mcm crashes with the error "panic: runtime error: invalid memory address or nil pointer dereference"

### Steps To Reproduce

1. Create multiple NodeGroups: `kubectl apply -f test.yaml`.
2. Wait for Node to be created
3. Delete several NodeGroups simultaneously: `kubectl delete -f test.yaml`.
4. Watching pods: `kubectl -n d8-cloud-instance-manager logs -f machine-controller-manager-***`.
5. Pod will crash and restart

test.yaml example:
```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker17
spec:
  cloudInstances:
    classReference:
      kind: YandexInstanceClass
      name: worker
    maxPerZone: 1
    minPerZone: 1
    zones:
    - ru-central1-a
  disruptions:
    approvalMode: Automatic
  nodeType: CloudEphemeral

---

apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker18
spec:
  cloudInstances:
    classReference:
      kind: YandexInstanceClass
      name: worker
    maxPerZone: 1
    minPerZone: 1
    zones:
    - ru-central1-a
  disruptions:
    approvalMode: Automatic
  nodeType: CloudEphemeral

---

apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker19
spec:
  cloudInstances:
    classReference:
      kind: YandexInstanceClass
      name: worker
    maxPerZone: 1
    minPerZone: 1
    zones:
    - ru-central1-a
  disruptions:
    approvalMode: Automatic
  nodeType: CloudEphemeral
  ```

### Logs

```shell
I0422 15:43:13.132122       1 machine.go:888] Machine "zykov-yc-dh-worker20-1eaeb73e-68f85-pw2wk" deleted successfully
Namespace: d8-cloud-instance-manager, Name: worker21-1eaeb73e
I0422 15:43:13.252359       1 machine.go:888] Machine "zykov-yc-dh-worker21-1eaeb73e-b4866-lg4m7" deleted successfully
Namespace: d8-cloud-instance-manager, Name: worker24-1eaeb73e
Namespace: d8-cloud-instance-manager, Name: worker19-1eaeb73e
Namespace: d8-cloud-instance-manager, Name: worker20-1eaeb73e
E0422 15:43:13.706085       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 699 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x296ad40, 0x4e66c50)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x296ad40, 0x4e66c50)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).getSecretData(0xc00048a380, 0xc000b8cb40, 0x11, 0xc001225900, 0x2, 0x2, 0xc0010705b8, 0x0, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_util.go:619 +0x13d
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkMachineClass(0xc00048a380, 0x2f995e0, 0xc0010707a0, 0xc000a41220, 0x0, 0xc000b8cb40, 0x11, 0xc000b8c760, 0x12)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:586 +0xb7
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkYandexMachineClass(0xc00048a380)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:567 +0x114
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkVMObjects(0xc00048a380)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:414 +0x93
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).reconcileClusterMachineSafetyOrphanVMs(0xc00048a380, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:56 +0x185
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1.1(0x34548a0, 0xc00095dde0, 0xc000f37dd0, 0x1, 0xf, 0x306b2ad, 0x1d, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:635 +0xf0
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1()
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:652 +0xab
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000d07100)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d07100, 0x3b9aca00, 0x0, 0x1, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/gardener/machine-controller-manager/pkg/controller.createWorker.func1(0x34548a0, 0xc00095dde0, 0x306b2ad, 0x1d, 0xf, 0x1, 0xc000f37dd0, 0x0, 0xc000828620)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:614 +0x9f
created by github.com/gardener/machine-controller-manager/pkg/controller.createWorker
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:613 +0xbe
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2453bfd]

goroutine 699 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x296ad40, 0x4e66c50)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).getSecretData(0xc00048a380, 0xc000b8cb40, 0x11, 0xc001225900, 0x2, 0x2, 0xc0010705b8, 0x0, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_util.go:619 +0x13d
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkMachineClass(0xc00048a380, 0x2f995e0, 0xc0010707a0, 0xc000a41220, 0x0, 0xc000b8cb40, 0x11, 0xc000b8c760, 0x12)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:586 +0xb7
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkYandexMachineClass(0xc00048a380)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:567 +0x114
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkVMObjects(0xc00048a380)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:414 +0x93
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).reconcileClusterMachineSafetyOrphanVMs(0xc00048a380, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:56 +0x185
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1.1(0x34548a0, 0xc00095dde0, 0xc000f37dd0, 0x1, 0xf, 0x306b2ad, 0x1d, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:635 +0xf0
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1()
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:652 +0xab
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000d07100)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d07100, 0x3b9aca00, 0x0, 0x1, 0x0)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/gardener/machine-controller-manager/pkg/controller.createWorker.func1(0x34548a0, 0xc00095dde0, 0x306b2ad, 0x1d, 0xf, 0x1, 0xc000f37dd0, 0x0, 0xc000828620)
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:614 +0x9f
created by github.com/gardener/machine-controller-manager/pkg/controller.createWorker
	/go/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:613 +0xbe
```
```
