### ISSUE TITLE
[monitoring-custom] scrape metrics an additional port 

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#8263]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Monitoring-custom module
When an application has multiple ports for metrics and I need to scrape them, at the same time using 1 service with an additional scraping port
example 
```
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-namespace
  labels:
    prometheus.deckhouse.io/custom-target: my-app
  annotations:
    prometheus.deckhouse.io/port: "8061"                      # by default, either the http-metrics or https-metrics service port is used
    prometheus.deckhouse.io/additional-port: "8062"   <----- additional port
    prometheus.deckhouse.io/path: "/my_app/metrics"           # /metrics by default
    prometheus.deckhouse.io/query-param-format: "prometheus"  # '' by default
    prometheus.deckhouse.io/allow-unready-pod: "true"         # by default, NON-ready Pods are ignored
    prometheus.deckhouse.io/sample-limit: "5000"              # by default, the sample is limited to 5000 metrics for a single Pod
spec:
  ports:
  - name: my-app
    port: 8060
  - name: http-metrics
    port: 8061
    targetPort: 8061
  - name: http-metrics-additional
    port: 8062
    targetPort: 8062
  selector:
    app: my-app
```

### Proposed Solution

may you add additional annotation for service/deployment for scrape few port at the same time
