### ISSUE TITLE
[cloud-provider-gcp] replicated disks cannot work

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#8298]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.10

### Expected Behavior

when we create pvc with replicated storage class appropriate PV should be created in the several zones.

### Actual Behavior

When we create pvc with replicated storage class appropriate PV cannot creates.

### Steps To Reproduce

1. Install deckhouse.
2. Create STS with PVC with replicated storage class:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: test-sc
spec:
  minReadySeconds: 10
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-05-02T11:59:47Z"
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.gke.io/zone
                operator: In
                values:
                - us-central1-a
                - us-central1-b
      containers:
      - image: registry.k8s.io/nginx-slim:0.8
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: www
    spec:
      storageClassName: pd-balanced-replicated
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
```
3. Describe pvc.

### Logs

```shell
Events:
  Type     Reason                Age                 From                                                                     Message
  ----     ------                ----                ----                                                                     -------
  Normal   WaitForFirstConsumer  115s                persistentvolume-controller                                              waiting for first consumer to be created before binding
  Normal   Provisioning          37s (x8 over 115s)  pd.csi.storage.gke.io_k8s-master-0_5019dcfe-a1b7-405e-bb7e-3b7a2d1489fd  External provisioner is provisioning volume for claim "stage/persistence-rabbitmq-stage-server-2"
  Warning  ProvisioningFailed    37s (x8 over 115s)  pd.csi.storage.gke.io_k8s-master-0_5019dcfe-a1b7-405e-bb7e-3b7a2d1489fd  failed to provision volume with StorageClass "pd-balanced-replicated": rpc error: code = InvalidArgument desc = CreateVolume failed to pick zones for disk: failed to pick zones from topology: need 2 zones from topology, only got 1 unique zones
  Normal   ExternalProvisioning  9s (x9 over 115s)   persistentvolume-controller                                              waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator
```
```
