### ISSUE TITLE
Deckhouse tries to roll back the current version to the previous ones during the update

### ISSUE THREAD

**Issue by hugik-88** [deckhouse/deckhouse#8299]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v.1.57.6

### Expected Behavior

There is a cluster in a closed environment with its own image registry. I am uploading a bundle of images to registry using dhctl mirror and want to update the deckhouse version using the deckhousereleases.yaml file.

I expect deckhouse to update to the next version

### Actual Behavior

Deckhouse consistently tries to update the release from the oldest version to the newest. 
```bash
kubectl get deckhousereleases.deckhouse.io
NAME       PHASE        TRANSITIONTIME   MESSAGE
v1.45.11   Pending      2s               Waiting for manual approval
v1.46.12   Pending      2s
v1.47.5    Pending      2s
v1.48.9    Pending      2s
v1.49.6    Pending      2s
v1.50.6    Pending      2s
v1.51.10   Pending      2s
v1.52.10   Pending      2s
v1.53.3    Pending      2s
v1.54.7    Pending      2s
v1.55.7    Pending      2s
v1.56.9    Superseded   39m
v1.57.6    Deployed     39m
v1.58.6    Pending      2s
```
If there is a manual update mode, then restarting the deckhouse pod puts the old releases in the Skipped state and suggests updating to the next newest minor version. 
```bash
kubectl get deckhousereleases.deckhouse.io
NAME       PHASE        TRANSITIONTIME   MESSAGE
v1.45.11   Skipped      41s              Skipped by cleanup hook
v1.46.12   Skipped      41s              Skipped by cleanup hook
v1.47.5    Skipped      41s              Skipped by cleanup hook
v1.48.9    Skipped      41s              Skipped by cleanup hook
v1.49.6    Skipped      41s              Skipped by cleanup hook
v1.50.6    Skipped      41s              Skipped by cleanup hook
v1.51.10   Skipped      41s              Skipped by cleanup hook
v1.52.10   Skipped      41s              Skipped by cleanup hook
v1.53.3    Skipped      41s              Skipped by cleanup hook
v1.54.7    Skipped      41s              Skipped by cleanup hook
v1.55.7    Skipped      41s              Skipped by cleanup hook
v1.56.9    Superseded   41m
v1.57.6    Deployed     41m
v1.58.10   Pending      39s              Waiting for manual approval
v1.58.6    Pending      2m39s
```

If there is an automatic update mode, then the deckhouse starts a sequential update, starting with the oldest version specified in the deckhousereleases.yml file
```bash
kubectl get deckhousereleases.deckhouse.io
NAME       PHASE        TRANSITIONTIME   MESSAGE
v1.45.11   Deployed     55s
v1.46.12   Pending      5m25s
v1.47.5    Pending      5m25s
v1.48.9    Pending      5m25s
v1.49.6    Pending      5m25s
v1.50.6    Pending      5m25s
v1.51.10   Pending      5m25s
v1.52.10   Pending      5m25s
v1.53.3    Pending      5m25s
v1.54.7    Pending      5m25s
v1.55.7    Pending      5m25s
v1.56.9    Superseded   16h
v1.57.6    Superseded   14h
v1.58.10   Pending      4m40s
v1.58.6    Pending      5m25s
```

### Steps To Reproduce

1. Upload a bundle of images 1.45-1.58 to the custom registry
2. Install cluster version 1.56
3. Switch the cluster to manual update mode
4. Upgrade to version 1.57
5. Apply the deckhousereleases.yml file 
```yaml
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.57.6
spec:
  changelog:
    deckhouse:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7866
        summary: Сhange the way the `deckhouse` pod readiness is determined during
          the minor version update.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.57.6
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    istioVer: "1.16"
    k8s: 1.24.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.57.6
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.45.11
spec:
  changelog:
    helm:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/4751
        summary: Fix deprecated k8s resources metrics.
    ingress-nginx:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/4734
        summary: Add protection for ingress-nginx-controller daemonset migration.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.45.11
  requirements:
    ingressNginx: "1.1"
    k8s: 1.22.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.45.11
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.56.9
spec:
  changelog:
    external-module-manager:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7228
        summary: Fix multiple symlinks for a single module in the symlink folder.
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7222
        summary: Fix outdated module versions in multi-master environment.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.56.9
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.24.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.56.9
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.58.6
spec:
  changelog:
    cloud-provider-vcd:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7875
        summary: Change the default network mode for new VMs.
    control-plane-manager:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7861
        summary: Fix error when `d8-cluster-configuration` secret is missing.
    deckhouse:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7867
        summary: Сhange the way the `deckhouse` pod readiness is determined during
          the minor version update.
    go_lib:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7884
        summary: Use a few requirement functions for one key.
    istio:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7879
        summary: Wiped `istioVer` requirement from `release.yaml`.
    multitenancy-manager:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7876
        summary: Fix Project rendering in some cases for embedded templates.
    node-manager:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/7893
        summary: Add permission for _cluster API_ resources for a cluster.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.58.6
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.25.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.58.6
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.49.6
spec:
  changelog:
    metallb:
      fixes:
      - impact: metallb pods should restart
        pull_request: https://github.com/deckhouse/deckhouse/pull/5572
        summary: fix error in speaker leader-election
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.49.6
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.23.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.49.6
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.54.7
spec:
  changelog:
    flant-integration:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/6763
        summary: Fix grafana agent config.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.54.7
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.24.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.54.7
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.51.10
spec:
  changelog:
    prometheus:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/6091
        summary: fix fix-permissions init-container to run under kesl security.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.51.10
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.23.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.51.10
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.50.6
spec:
  changelog:
    candi:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/5746
        summary: Fix migration of cluster from one edition to another.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.50.6
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.23.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.50.6
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.53.3
spec:
  changelog:
    common:
      fixes:
      - impact: '`csi-controller` pod will restart.'
        pull_request: https://github.com/deckhouse/deckhouse/pull/6378
        summary: Fix build of `csi-external-*` images.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.53.3
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.24.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.53.3
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.46.12
spec:
  changelog:
    kube-proxy:
      fixes:
      - impact: NodePort services on a nodes without annotation were open to the world.
        pull_request: https://github.com/deckhouse/deckhouse/pull/5199
        summary: Fix `node.deckhouse.io/nodeport-bind-internal-ip` annotation behavior
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.46.12
  requirements:
    ingressNginx: "1.1"
    k8s: 1.22.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.46.12
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.48.9
spec:
  changelog:
    user-authn:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/5424
        summary: Add custom certificate for kubeconfig generator.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.48.9
  requirements:
    ingressNginx: "1.1"
    k8s: 1.23.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.48.9
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.52.10
spec:
  changelog:
    candi:
      fixes:
      - pull_request: https://github.com/deckhouse/deckhouse/pull/6329
        summary: Fix deckhouse containerd start after installing new containerd-deckhouse
          package.
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.52.10
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.23.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.52.10
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.47.5
spec:
  changelog:
    kube-proxy:
      fixes:
      - impact: NodePort services on a nodes without annotation were open to the world.
        pull_request: https://github.com/deckhouse/deckhouse/pull/5199
        summary: Fix `node.deckhouse.io/nodeport-bind-internal-ip` annotation behavior
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.47.5
  requirements:
    ingressNginx: "1.1"
    k8s: 1.22.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.47.5
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
---
apiVersion: deckhouse.io/v1alpha1
approved: false
kind: DeckhouseRelease
metadata:
  creationTimestamp: null
  name: v1.55.7
spec:
  changelogLink: https://github.com/deckhouse/deckhouse/releases/tag/v1.55.7
  requirements:
    containerdOnAllNodes: "true"
    ingressNginx: "1.1"
    k8s: 1.24.0
    nodesMinimalOSVersionUbuntu: "18.04"
  version: v1.55.7
status:
  approved: false
  message: ""
  transitionTime: "0001-01-01T00:00:00Z"
```
6. Watch for incorrect updates
