### ISSUE TITLE
[descheduler] does not transfer pods to another node for the removePodsViolatingInterPodAntiAffinity strategy

### ISSUE THREAD

**Issue by raabdullaev** [deckhouse/deckhouse#8473]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v.1.59

### Expected Behavior

-

### Actual Behavior

Descheduler does not transfer pods to another node for the removePodsViolatingInterPodAntiAffinity strategy with this config:
```
apiVersion: deckhouse.io/v1alpha1
kind: Descheduler
metadata:
  name: descheduler
spec:
  deschedulerPolicy:
    globalParameters:
      ignorePvcPods: true
      maxNoOfPodsToEvictPerNamespace: 1
    strategies:
      removePodsViolatingInterPodAntiAffinity:
        enabled: true
        nodeFit: true
```
