### ISSUE TITLE
[node-manager]  Cluster API Provider Static and master node-group

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#8494]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When bootstraping a cluster with CAPS and needing 3 master nodes
I boot one of them with `dhctl boostrap`, for the rest of the master nodes I need to create a additional master `node group` and `StaticInstance`.
This solution seems inconsistent. It turns out that I will have a StaticInstance for two masters and no StaticInstance for the third master.
In our quickstart, we suggest using StaticInstance resources and there is no mention of `manual-bootstrap-for-master`. We are switching from these scripts to StaticInstance, and commander doesn't know how to work with these scripts.

### Proposed Solution

we have hack, but count = 2 is not 3 master nodes in cluster

```yaml
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: master
spec:
  disruptions:
    approvalMode: Manual
  nodeTemplate:
    labels:
      node-role.kubernetes.io/control-plane: ""
      node-role.kubernetes.io/master: ""
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  nodeType: Static
  staticInstances:
    count: 2   # <------------------------------ 
    labelSelector:
      matchLabels:
        type: master
```
