### ISSUE TITLE
[control-plane-manager] Another alert for D8KubeEtcdDatabaseSize

### ISSUE THREAD

**Issue by hugik-88** [deckhouse/deckhouse#8604]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In the case when the etcd base grows exponentially, we need to pay close attention to this alert and quickly respond to the anomaly. If the alert has severity s6, then the alert may remain on all weekend and by Monday the cluster will be broken

### Proposed Solution

```yaml
- alert: D8KubeEtcdDatabaseSizeCriticalCloseToTheLimit
      expr: max by (node) (etcd_mvcc_db_total_size_in_bytes{job="kube-etcd3"}) >= scalar(max(d8_etcd_quota_backend_total) * 0.95)
      labels:
        severity_level: "3"
        tier: cluster
      for: "10m"
      annotations:
        plk_protocol_version: "1"
        plk_markup_format: "markdown"
        plk_create_group_if_not_exists__kube_etcd_malfunctioning: "KubeEtcdMalfunctioning,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__kube_etcd_malfunctioning: "KubeEtcdMalfunctioning,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
        description: |
          The size of the etcd database on `{{ $labels.node }}` has almost exceeded.
          Possibly there are a lot of events (e.g. Pod evictions) or a high number of other resources are created in the cluster recently.
```
          Possible solutions:
          - You can do defragmentation. Use next command:
          `kubectl -n kube-system exec -ti etcd-{{ $labels.node }} -- /usr/bin/etcdctl --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/ca.key --endpoints https://127.0.0.1:2379/ defrag --command-timeout=30s`
          - Increase node memory. Begin from 24 GB `quota-backend-bytes` will be increased on 1G every extra 8 GB node memory.
            For example:
            Node Memory  quota-backend-bytes
            16GB         2147483648 (2GB)
            24GB         3221225472 (3GB)
            32GB         4294967296 (4GB)
            40GB         5368709120 (5GB)
            48GB         6442450944 (6GB)
            56GB         7516192768 (7GB)
            64GB         8589934592 (8GB)
            72GB         8589934592 (8GB)
            ....
