### ISSUE TITLE
`node-role.kubernetes.io/${roleName}` with a non-empty value

### ISSUE THREAD

**Issue by borg-z** [deckhouse/deckhouse#8634]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It seems that AWS EKS currently does not allow labels with empty values. I think this is to make the labeling rules consistent for EKS and other AWS resources.
https://github.com/aws/aws-sdk-go-v2/issues/2267

### Proposed Solution

We could add an additional label, for example:

```yaml
node-role.deckhouse.io/system: ""
node-role.deckhouse.io/system: "true"
```

Or use nodeAffinity:

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.deckhouse.io/system
              operator: Exists
```
