### ISSUE TITLE
d8-control-plane-manager crashes when trying to update admin.conf

### ISSUE THREAD

**Issue by borg-z** [deckhouse/deckhouse#8653]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.60.0

### Expected Behavior

`d8-control-plane-manager` successfully updates admin.conf

### Actual Behavior

If `admin.conf` has an incorrect format, `d8-control-plane-manager` might go into a crash loopback.

### Steps To Reproduce

1. set `/var/lib/kubernetes/admin.conf` value:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDR
    server: https://127.0.0.1:6445
  name: kubernetes
- cluster:
    server: https://api.bob.com
  name: sandbox
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
- context:
    cluster: sandbox
    user: gitlab-runner-deploy.sandbox
  name: sandbox-gitlab-runner-deploy.sandbox
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: gitlab-runner-deploy.kubernetes
  user:
    token: eyJhbGciOiJ
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJU
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJV
- name: gitlab-runner-deploy.sandbox
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZ
```

2. restart `d8-control-plane-manager` pod
3. `d8-control-plane-manager` will attempt to retrieve the value of the `client-certificate-data` field from the first user in the users array (`currentKubeconfig.AuthInfos[0].AuthInfo.ClientCertificateData`). The first user only has the token field. As a result, d8-control-plane-manager will go into a crash loopback.

### Logs

```shell
{"level":"info","msg":"[kubeconfig] Writing \"admin.conf\" kubeconfig file","time":"2024-06-06T08:16:59Z"}
{"level":"info","msg":"","time":"2024-06-06T08:16:59Z"}
{"level":"error","msg":"client-certificate-data field of kubeconfig /etc/kubernetes/admin.conf is empty","time":"2024-06-06T08:16:59Z"}
```
