### ISSUE TITLE
[prometheus] Add additional configuration for probeSelector and probeNamespaceSelector [monitoring.coreos.com/v1]

### ISSUE THREAD

**Issue by cds111** [deckhouse/deckhouse#8664]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Currently, metrics collecting are realized through the following configuration:

```shell
$ kubectl -n d8-monitoring get prometheuses.monitoring.coreos.com main -o jsonpath='{.spec.probeSelector} {.spec.probeNamespaceSelector}'
{"matchLabels":{"prometheus":"main"}} {"matchLabels":{"heritage":"deckhouse"}}
```
For example, if you want to create a probe for the blackbox exporter using Deckhouse Prometheus, you need to add an additional label prometheus: main:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    app: prometheus
    component: probes
    prometheus: main # <--- Additional label
```
Additionally, you must label the namespace you want to monitor with `heritage: deckhouse`.

### Proposed Solution

Provide the ability to add or edit `spec.probeSelector` and `spec.probeNamespaceSelector` to enhance clarity and simplicity for probes and service monitors. This change will also reduce the number of blackbox-exporter and serviceMonitor services necessary for cluster use.
