### ISSUE TITLE
Empty /var/lib/bashible/bashible.sh

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#8960]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.61.4

### Expected Behavior

All works fine

### Actual Behavior

**Sporadic** problem, after install BareMetal-cluster with StaticInstances got alert `D8NodeIsNotUpdating` on 1 node. Check the status of node gives information that `/var/lib/bashible/bashible.sh` is empty:
<img width="1577" alt="Screenshot 2024-07-09 at 01 33 00" src="https://github.com/deckhouse/deckhouse/assets/742504/4585440f-1704-40a5-a9ff-0d072ea57bb4">

### Steps To Reproduce

Used config
```
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Static
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: "Automatic"
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: registry.deckhouse.ru/deckhouse/ee
  registryDockerCfg: ***DELETED***
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    bundle: Default
    releaseChannel: Stable
    logLevel: Info
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  version: 1
  settings:
    modules:
      publicDomainTemplate: "%s.domain.my"
      https:
        certManager:
          clusterIssuerName: selfsigned
    storageClass: localpath-system
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: user-authn
spec:
  version: 2
  enabled: true
  settings:
    controlPlaneConfigurator:
      dexCAMode: FromIngressSecret
    publishAPI:
      enabled: true
      https:
        mode: Global
        global:
          kubeconfigGeneratorMasterCA: ""
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cert-manager
spec:
  version: 1
  enabled: true
  settings:
    disableLetsencrypt: true
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cni-cilium
spec:
  version: 1
  enabled: true
  settings:
    tunnelMode: VXLAN
---
apiVersion: deckhouse.io/v1
kind: StaticClusterConfiguration
internalNetworkCIDRs:
- 10.128.0.0/24
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: master
spec:
  nodeTemplate:
    labels:
      node-role.kubernetes.io/control-plane: ""
      node-role.kubernetes.io/master: ""
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  nodeType: Static
  staticInstances:
    count: 2
    labelSelector:
      matchLabels:
        role: master
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: system
spec:
  nodeTemplate:
    labels:
      node-role.deckhouse.io/system: ""
    taints:
    - effect: NoExecute
      key: dedicated.deckhouse.io
      value: system
  nodeType: Static
  staticInstances:
    count: 2
    labelSelector:
      matchLabels:
        role: system
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: frontend
spec:
  nodeTemplate:
    labels:
      node-role.deckhouse.io/frontend: ""
    taints:
    - effect: NoExecute
      key: dedicated.deckhouse.io
      value: frontend
  nodeType: Static
  staticInstances:
    count: 2
    labelSelector:
      matchLabels:
        role: frontend
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker
spec:
  nodeType: Static
  staticInstances:
    count: 1
    labelSelector:
      matchLabels:
        role: worker
---
apiVersion: deckhouse.io/v1alpha1
kind: LocalPathProvisioner
metadata:
  name: localpath-system
spec:
  nodeGroups:
    - system
  path: "/opt/local-path-provisioner"
  reclaimPolicy: Delete
---
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: nginx
spec:
  ingressClass: nginx
  inlet: HostPort
  hostPort:
    httpPort: 80
    httpsPort: 443
  nodeSelector:
    node-role.kubernetes.io/frontend: ""
  tolerations:
  - operator: Exists
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: chrony
spec:
  enabled: true
  settings:
    ntpServers:
      - pool.ntp.org
      - ntp.ubuntu.com
      - time.google.com
  version: 1
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: console
spec:
  enabled: true
---
apiVersion: deckhouse.io/v1alpha1
kind: SSHCredentials
metadata:
  name: ssh-credentials
spec:
  user: yc-user
  privateSSHKey: "***DELETED***"
---
# HOSTS master
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: master-2
  labels:
    role: master
spec:
  address: "10.128.0.59"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
---
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: master-3
  labels:
    role: master
spec:
  address: "10.128.0.71"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
---
# HOSTS system
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: system-1
  labels:
    role: system
spec:
  address: "10.128.0.40"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
---
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: system-2
  labels:
    role: system
spec:
  address: "10.128.0.16"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
---
# HOSTS frontend
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: frontend-1
  labels:
    role: frontend
spec:
  address: "10.128.0.52"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
---
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: frontend-2
  labels:
    role: frontend
spec:
  address: "10.128.0.53"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
---
# HOSTS worker
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: worker-1
  labels:
    role: worker
spec:
  address: "10.128.0.68"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
---
apiVersion: deckhouse.io/v1alpha1
kind: StaticInstance
metadata:
  name: worker-2
  labels:
    role: worker
spec:
  address: "10.128.0.5"
  credentialsRef:
    kind: SSHCredentials
    name: ssh-credentials
```
