### ISSUE TITLE
[loki] Add retention period depending on selector labels

### ISSUE THREAD

**Issue by drblack666** [deckhouse/deckhouse#8976]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It's important to be able to store logs in different namespaces for different periods of time. For example, create different retention period for dev and production namespaces.

### Proposed Solution

Add `limits_config.retention_stream` for [compactor](https://grafana.com/docs/loki/latest/operations/storage/retention/#configuring-the-retention-period). Example from documentation:
```
limits_config:
  retention_period: 744h
  retention_stream:
  - selector: '{namespace="dev"}'
    priority: 1
    period: 24h
```
