### ISSUE TITLE
[cloud-provider-openstack] After bootstrap cluster in VKCloud we have not StorageClasses from cloud

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#8998]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.61.4

### Expected Behavior

After bootstrap we have storageClasses from cloud and our modules, especial prometheus, have PVC

### Actual Behavior

We have not SC and prometheus works on emptyDir
```
~ $ kubectl get storageclasses.storage.k8s.io
No resources found
~ $ kubectl -n d8-monitoring describe pods prometheus-main-0
...
Volumes:
  prometheus-main-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
...
```

Restart deployments in `d8-cloud-provider-openstack` create storageClasses immediately
```
~ $ kubectl get sc
NAME                 PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ceph-hdd (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   0s
ceph-ssd             cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   0s
dp1-high-iops        cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   0s
high-iops            cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   0s
```

### Steps To Reproduce

Bootstrap by config
```
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Cloud
cloud:
  provider: OpenStack
  prefix: test
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: "Automatic"
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: registry.deckhouse.ru/deckhouse/ee
  registryDockerCfg: **HIDDEN**
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    bundle: Default
    releaseChannel: Stable
    logLevel: Info
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  version: 1
  settings:
    modules:
      publicDomainTemplate: "%s.example.com"
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: user-authn
spec:
  version: 1
  enabled: true
  settings:
    controlPlaneConfigurator:
      dexCAMode: DoNotNeed
    publishAPI:
      enable: true
      https:
        mode: Global
        global:
          kubeconfigGeneratorMasterCA: ""
---
apiVersion: deckhouse.io/v1
kind: OpenStackClusterConfiguration
layout: Standard
standard:
  externalNetworkName: ext-net
  internalNetworkCIDR: 192.168.198.0/24
  internalNetworkDNSServers:
    - 8.8.8.8
    - 8.8.4.4
  internalNetworkSecurity: true
provider:
  authURL: https://infra.mail.ru:35357/v3/
  domainName: users
  password: **HIDDEN**
  region: RegionOne
  tenantID: **HIDDEN**
  username: **HIDDEN**
masterNodeGroup:
  replicas: 1
  volumeTypeMap:
    ME1: ceph-ssd
  instanceClass:
    flavorName: Standard-4-8-80
    imageName: ubuntu-22-202404160933.gitd6495fe9
    rootDiskSize: 40
sshPublicKey: '**HIDDEN**'
---
apiVersion: deckhouse.io/v1
kind: OpenStackInstanceClass
metadata:
  name: worker
spec:
  flavorName: Standard-4-8-80
  rootDiskSize: 30
  imageName: ubuntu-22-202404160933.gitd6495fe9
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker
spec:
  cloudInstances:
    classReference:
      kind: OpenStackInstanceClass
      name: worker
    maxPerZone: 1
    minPerZone: 1
    zones:
    - ME1
  disruptions:
    approvalMode: Automatic
  nodeType: CloudEphemeral
---
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: nginx
spec:
  ingressClass: nginx
  inlet: LoadBalancer
  nodeSelector:
    node.deckhouse.io/group: worker
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: cloud-provider-openstack
spec:
  version: 1
  enabled: true
  settings:
    ignoreVolumeMicroversion: true
```
