### ISSUE TITLE
Error in `040-node-manager/hooks/get_crds.go` hook

### ISSUE THREAD

**Issue by Nitive** [deckhouse/deckhouse#9]
Hi! I spinned out a bare metal cluster and got this error in deckhouse logs

```
Module hook start '040-node-manager/hooks/get_crds.go'
Module hook start
Module hook failed, requeue task to retry after delay. Failed count is 1435. Error: 7 errors occurred:
	* cannot apply values patch for module values
	* nodeManager.internal.nodeGroups.static.internalNetworkCIDRs in body must be of type array: "object"
	* nodeManager.internal.nodeGroups.static.internalNetworkCIDRs.Index in body is a forbidden property
	* nodeManager.internal.nodeGroups.static.internalNetworkCIDRs.Num in body is a forbidden property
	* nodeManager.internal.nodeGroups.static.internalNetworkCIDRs.Raw in body is a forbidden property
	* nodeManager.internal.nodeGroups.static.internalNetworkCIDRs.Str in body is a forbidden property
	* nodeManager.internal.nodeGroups.static.internalNetworkCIDRs.Type in body is a forbidden property
```

Looks like I've got corrupted internal hook state
```yaml
$ deckhouse-controller module values node-manager
...
nodeManager:
  ...
  internal:
    ...
    standbyNodeGroups: []
    static: # <- No nodeGroups there
      internalNetworkCIDRs:
        - 192.168.5.0/24
  ...
```
