### ISSUE TITLE
[ingress-nginx] Support nodeaffinity for IngressNginxController

### ISSUE THREAD

**Issue by wowsel** [deckhouse/deckhouse#9309]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Currently, it is only possible to specify nodeSelector in CRD, which limits the ability to deploy to two node groups simultaneously with different labels. 
For example, now I have a task to transfer product ingresses from dedicated frontend nodes to product worker nodes. Since the ingress is deployed without any selectors now and uses automation - replacing labels with product ones simply turned off the old ones and the aws will not have time to switch the balancer to product nodes. We will get downtime.

### Proposed Solution

If there was a way to specify nodeaffinity I could add two node groups there at once, deploy ingress, give aws time to connect new targets and then remove the old group from affinity. It seems that this could work without downtime.

### Additional Information

i'm using AWS ALB and 
```
  inlet: LoadBalancer
  loadBalancer:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-type: none
    realIPHeader: X-Forwarded-For
    behindL7Proxy: true
```
