### ISSUE TITLE
[user-authz] auth webhook error

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#9474]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.63.X

### Expected Behavior

Command returns without error

### Actual Behavior

Command `kubectl --as=admin@flant.com auth can-i list namespaces -A` returns the error:
```
no - webhook: kubernetes api request error
```

### Steps To Reproduce

1. Enable MultiTenancy
```
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: user-authz
spec:
  enabled: true
  settings:
    enableMultiTenancy: true
  version: 1
```

2. Create user
```
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: admin
spec:
  email: admin@flant.com
  password: $2a$xcvxcvxcvcxv
```

3. Create CAR
```yaml
apiVersion: deckhouse.io/v1
kind: ClusterAuthorizationRule
metadata:
  name: admin
spec:
  accessLevel: SuperAdmin
  allowAccessToSystemNamespaces: true
  allowScale: true
  portForwarding: true
  subjects:
  - kind: User
    name: admin@flant.com
```

4. Run `kubectl --as=admin@flant.com auth can-i list namespaces -A`

### Additional Information

without multitenancy it works ok

### Logs

```shell
user-authz-webhook logs


2024/08/23 13:51:07 renew namespaced cache: kube response error: 404 404 page not found
```
```
2024/12/25 10:58:20 renew namespaced cache: kube response error: 404 {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
: exceeded retry limit
```
