### ISSUE TITLE
[loki] RBAC is missed for grafana service account 

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#9518]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.63.3 CE

### Expected Behavior

Working with loki log storage from grafana without any problems

### Actual Behavior

RoleBingins for RBAC proxy is missing [here](https://github.com/deckhouse/deckhouse/blob/main/modules/462-loki/templates/rbac-to-us.yaml)

Possible solution
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-access-to-loki-from-http
  namespace: d8-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-to-loki-from-http
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: d8-monitoring
```

### Steps To Reproduce

# Upgrade to actual D8 version
# Enable Loki module
# Try to get logs in Explore page in Grafana
