### ISSUE TITLE
[global] Add lintignore files support for modules

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#96]
# What

Introduce special 'ignore' file format for the module linter.

## Motivation

For now in linter we hardcode modules we want to ignore for special linting rules or even globally. A dedicated lintignore file should be more obvious, convenient and scalable tool that makes possible using the linter for custom modules.

Examples of the hardcoded exclusions:

- [Validation of ClusterRoles ignores user-authz module](https://github.com/deckhouse/deckhouse/blob/main/testing/matrix/linter/rules/roles/binding-subject.go#L29)
- [Validation of oss.yaml ignores ones which would repeat already mentioned projects](https://github.com/deckhouse/deckhouse/blob/main/testing/matrix/linter/rules/modules/oss.go#L151)
- [Modules ignored as a whole](https://github.com/deckhouse/deckhouse/blob/f96ec4c4d32924616348e3776a5460476390490e/testing/matrix/linter/rules/modules/modules.go#L50)
- [VPA rule ignores modules which use other mechanisms to control resources](https://github.com/deckhouse/deckhouse/blob/main/testing/matrix/linter/rules/resources/vpa.go#L63)
- [Image validation ignores images that are meant for removal](https://github.com/deckhouse/deckhouse/blob/main/testing/matrix/linter/rules/modules/images.go#L30)
- [CRD validation skips *.deckhouse.io manifests](https://github.com/deckhouse/deckhouse/blob/f96ec4c4d32924616348e3776a5460476390490e/testing/matrix/linter/rules/modules/crds.go#L37)

## High level idea

With the lintignore file one should be able to tell the linter to skip

### Per module

- skip the module as whole 
- skip module file
- skip module subdirectory
- skip files and directories matching path wildcard relative to the module root
- (questionable) skip text files with content matching a regex pattern (can be covered by explicit path entries)
- ignore single or multiple linter rules

### Globally

The lintignore.yaml in the repository root might contain global entries containing paths relative to module root. Per each module, global lintitgnore is merged with the module lintignore to construct the final set of ingnored entries.

## Example / proposal

```yaml
# File modules/xxx/lintignore.yaml
# All root keys are optional, arrays can be empty

# To skip the linting for the whole module, uncomment the line 
# all: true 

# Ignore file paths
paths:
  - images/app/Dockerfile.test
  - templates/examples/       # trailing slash is optional
  - crds/specific-thing-*.yaml  

# Ignore files by the contents
contents:
  - ^name: \w+.deckhouse.io$   # can be covered by explicit path entries

# Skip linting rules
rules:
  - VPA
  - OSS # can also be covered in paths as "oss.yaml"
```
