### ISSUE TITLE
[cloud-provider-openstack](Selectel Cloud) CloudEphemeral nodes can't create if not on A-zone

### ISSUE THREAD

**Issue by haosb** [deckhouse/deckhouse#9662]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Right now, if we want to create `CloudEphemeral` nodes in `B zone` our nodes cannot create with error log:
```
 Message:Build of instance b4b49b8e-5471-44e1-9afe-097a16cc8ed4 aborted: Invalid input received: Availability zone 'ru-3b' is invalid. (HTTP 400)
```
It happens because the `A zone` is default zone, and MCM trying to create VM in `B zone`, but disk creates at `A zone`.

The **workaround** for this is modifying the flavor of node and change disk zone. But for `CloudPermanent` we have a settings to choose disk zone in `OpenstackClusterConfiguration`:
```
...
  volumeTypeMap:
    # <availability zone>: <volume type>
    ru-2b: "fast.ru-2b"
```

### Proposed Solution

I think that we need to automatically create disks in zone where node want to create.

### Additional Information

Part of `config.yml`, cluster bootstrapped with this config have problems:
```
apiVersion: deckhouse.io/v1
kind: OpenStackClusterConfiguration
layout: Standard
standard:
  bastion:
    zone: ru-2b
    volumeType: basic.ru-2b
    instanceClass:
      flavorName: c1r2
      imageName: ubuntu-22.04-cloud-amd64
      rootDiskSize: 20
  externalNetworkName: external-network
  internalNetworkCIDR: 10.241.32.0/20
  internalNetworkDNSServers:
    - 1.1.1.1
    - 8.8.4.4
  internalNetworkSecurity: false
provider:
  authURL: 'REDACTED'
  domainName: 'REDACTED'
  password: 'REDACTED'
  region: 'ru-2'
  tenantID: 'REDACTED'
  username: 'REDACTED'
masterNodeGroup:
  replicas: 1
  volumeTypeMap:
    ru-2b: "fast.ru-2b"
  instanceClass:
    flavorName: c8r8
    imageName: ubuntu-22.04-cloud-amd64
    rootDiskSize: 60
sshPublicKey: "KEY"
```
