### ISSUE TITLE
[dex] Login error if the group name consists of numbers

### ISSUE THREAD

**Issue by marriva** [deckhouse/deckhouse#9706]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.63.8

### Expected Behavior

I want to use deckhouse user group with name `916531`. User can login to dex.

### Actual Behavior

When a user who is a member of the group `916531` tries to log in, he receives an error:

```
Login error: get password: json: cannot unmarshal number into Go struct field Password.groups of type string
```

### Steps To Reproduce

Create user and group

```yaml
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: test
spec:
  email: test@deckhouse.io
  password: JDJ5JDEwJDBEenJRUVo4Q1FZVy4zRnNndXJYYk9TUmt5anN4WTJsZ2hGbjNlbnN0OThWM1hsSFIzSVFXCgo=
---
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: "916531"
spec:
  members:
  - kind: User
    name: test
  name: "916531"
  ```
  
  Login to `grafana.example.com`
  
![Screenshot 2024-09-12 at 15 46 29](https://github.com/user-attachments/assets/735185e1-72ac-479e-9d4b-12d7016dae21)
