### ISSUE TITLE
[deckhouse-conrtoller] change crd's interaction method

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#9790]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

At the moment we have conditions like [this](https://github.com/deckhouse/lib-helm/blob/main/charts/helm_lib/templates/_monitoring_grafana_dashboards.tpl#L45C58-L45C77)
it's not transparent to use, while we can move resources and modules.
We need a more predictable way to manage the resources

### Proposed Solution

We have ensure_crds logic in the addon-operator.
We have to collect installed CRD's, build GVK for them and inject them into the global values, like this:

```
global:
  discovery:
    apiVersions:
      - deckhouse.io/v1/GrafanaDashboardDefinition
      - deckhouse.io/v1alpha1/GrafanaDashboardDefinition
      - monitoring.coreos.com/v1/PrometheusRule
      - deckhouse.io/v1alpha1/NodeGroup
      - deckhouse.io/v1beta1/NodeGroup
      - deckhouse.io/v1/NodeGroup
```

Then we will be able to use constructions like this:
```
{{- if ( $context.Values.global.discovery.apiVersions | has "deckhouse.io/v1/GrafanaDashboardDefinition" ) }}      
apiVersion: deckhouse.io/v1
kind: GrafanaDashboardDefinition
metadata:
  name: foo
spec:
  ...
{{- end }}
```
