### ISSUE TITLE
[ingress-nginx] DNS query errors when ingress to ExternalName service has ClusterIP default-backend

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#9933]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.63.10

### Expected Behavior

`ingress-nginx` doesn't try to resolve `ClusterIP` endpoints as DNS names, but only resolves `ExternalNames`

### Actual Behavior

In some cases, ingress-nginx tries to resolve ClusterIP endpoints and fails.
Relevant for all current versions: v1.6, v1.9, v1.10

This particular case was following:
1. Ingress resources leads to `ExternalName` (`static-test`) service, and has custom `default-backend` set for 5xx errors:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-16
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/custom-http-errors: 500,501,502,503,504
    nginx.ingress.kubernetes.io/default-backend: core-nginx-errors
    nginx.ingress.kubernetes.io/upstream-vhost: static.example.net
  name: external-name-ingress
spec:
  rules:
  - host: static.example.com
    http:
      paths:
      - backend:
          service:
            name: static-test
```
2. `default-backend` is simple ClusterIP, leads to some pod in the same namespace:
```
#svc:
core-nginx-errors         ClusterIP      10.222.91.105   <none>                                80/TCP    63m
```

```
#endpoint:
core-nginx-errors   10.111.0.35:8080   64m
```
3. Despite the endpoint being ClusterIP, nginx tries to resolve `default-backend` it via DNS:
```
2024/10/01 12:50:44 [error] 39#39: *67334 [lua] dns.lua:152: dns_lookup(): failed to query the DNS server for 10.111.0.35:
server returned error code: 3: name error
server returned error code: 3: name error, context: ngx.timer
```

Seems that issue is somewhere in this condition not filtering properly by service type:
https://github.com/kubernetes/ingress-nginx/blob/release-1.10/rootfs/etc/nginx/lua/tcp_udp_balancer.lua#L74-L78
